delta-io/delta-rs

README.adoc
This should make it a little more understandable to newcomers
=> Include a link to Slack in the readme, along with some other changes

CODE_OF_CONDUCT.md
Didn't realize we had missed this before
=> Add a code of conduct for the project

.github/workflows/build.yml, .github/workflows/python_build.yml, README.adoc, python/Cargo.toml, python/README.md, python/deltalake/__init__.py, python/src/lib.rs, python/tests/test_table_read.py, rust/Cargo.toml, rust/src/lib.rs
also throw in code cleanup to remove use on unwrap
=> add time travel to python binding

Cargo.lock, python/Cargo.toml, rust/Cargo.toml
* bump version for rust core
* relax dependency constraints for rust core
* add features for python binding
=> relax dependency constraints and add features in Cargo.toml

.github/workflows/build.yml, Cargo.lock, README.adoc, rust/Cargo.toml, rust/src/delta_datafusion.rs, rust/src/schema.rs, rust/tests/datafusion_test.rs
This has the nice side-effect of making delta.rs no longer require the nightly
compiler
"But Tyler" you say "the master branch is always changing!" To which I grumpily
reply "Cargo dot lock"
(hat tip to @andygrove for the mention that arrow now compiles with stable)
=> Bump the arrow dependencies to master for the ongoing development that's landing there

rust/tests/s3_test.rs
This IAM user basically has all Read/List permissions on the deltars bucket in
an empty account I control.
Fixes #36
=> Introduce a simple S3 integration test for reading from a table

Cargo.lock, python/Cargo.toml, python/src/lib.rs, rust/Cargo.toml, rust/src/action.rs, rust/src/bin/delta-inspect.rs, rust/src/delta.rs
Do not return unrecoverable error on new record fields from future
delta table versions. Fix #54.
=> make snapshot parsing more forward compatible

python/Cargo.toml, rust/Cargo.toml, rust/src/action.rs
=> add support for partitionValues_parsed field

.github/workflows/python_build.yml, .github/workflows/python_release.yml, Cargo.lock, python/Cargo.toml, python/deltalake/__init__.py, python/src/lib.rs, python/tests/test_table_read.py, python/tests/test_version.py, rust/src/delta.rs
also switch pyo3 to build abi3 wheels
=> expose rust crate version to python binding

.github/workflows/python_build.yml, python/Cargo.toml, python/README.md, python/src/lib.rs, python/tests/conftest.py, python/tests/test_table_read.py
=> Avoid tokio runtime blocking table load from python binding

rust/src/delta.rs, rust/src/storage/file.rs, rust/src/storage/mod.rs
Proposal for better handling path in a platform-safe manner (#39, #40)
=> Refactoring Path Management in storage_backend

rust/tests/read_simple_table_test.rs
A little fix in the test for joining Path
=> Quick fix on Path in tests

Cargo.lock, python/Cargo.toml, ruby/Cargo.toml, ruby/src/lib.rs, rust/Cargo.toml, rust/src/bin/delta-inspect.rs, rust/src/delta_datafusion.rs, rust/src/storage/azure.rs, rust/src/storage/file.rs, rust/src/storage/mod.rs, rust/tests/azure_test.rs, rust/tests/datafusion_test.rs
datafusion tests are expected to fail until we pick up https://github.com/apache/arrow/pull/9230.
=> bump tokio to 1.0

Cargo.lock, rust/Cargo.toml, rust/src/delta_arrow.rs, rust/src/lib.rs
Handle decimal type on a delta table schema #91
=> Handle decimal type in arrow schema

.github/workflows/build.yml, Cargo.lock, rust/src/action.rs, rust/src/bin/delta-inspect.rs, rust/src/delta.rs, rust/src/delta_arrow.rs, rust/src/lib.rs, rust/src/storage/file.rs, rust/src/storage/mod.rs, rust/tests/delta_arrow_test.rs, rust/tests/s3_test.rs, rust/tests/simple_commit_test.rs, rust/tests/write_exploration.rs
say good bye to arguing about coding style in code reviews.
=> enforce rustfmt in CI

rust/src/storage/s3.rs, rust/tests/s3_test.rs
Turns out list_objs method in S3 backend never worked
=> fix load s3 table by version

rust/README.md
Make the features section more explicit for those who are new to Rust.
=> Update cargo package features section in readme

rust/src/storage/mod.rs, rust/src/storage/s3.rs
Reduce cfg flags in storage/mod.rs. We can further decouple s3 code from `storage/mod.rs` by introducing a wrapper S3 error enum type, but I will leave it for future clean up.
=> move more s3 specific code into storage/s3.rs

python/Cargo.toml
release python crate for schema and s3 listing bug fix.
=> bump python crate version for release

Cargo.lock, python/Cargo.toml, rust/src/storage/file/mod.rs, rust/src/storage/mod.rs, rust/src/storage/s3.rs, rust/tests/write_exploration.rs
Add join_paths for more efficient path join with multiple components.
Also added document for StorageBackend trait.
=> add join_paths for more efficient path join with multiple components

Cargo.lock, glibc_version/Cargo.toml, glibc_version/README.md, glibc_version/src/lib.rs
Publish libc_version to crates.io
=> publish libc_version in crates.io

Cargo.lock, README.adoc, glibc_version/README.md, rust/Cargo.toml
~~Ever wonder why our CI badge is always green?~~
EDIT: never mind, looks we were covered by github repo redirect :D
=> docs: update readme badges

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml , .github/ISSUE_TEMPLATE/feature_request.md
Add a template for raising an issue in delta-rs
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
=> Add template for an issue

rust/src/delta.rs
Add rustdocs to several public interfaces in `src/delta.rs`
https://github.com/delta-io/delta-rs/issues/155
=> Add rustdocs to delta.rs

rust/src/action.rs, rust/src/delta.rs
Add rustdocs to most public interfaces in `src/actions.rs`
Related to https://github.com/delta-io/delta-rs/issues/155
=> Rustdocs for most of actions.rs

.github/workflows/python_build.yml, rust/tests/s3_test.rs
I may just need to recycle these keys
=> Ignore the S3 acceptance tests until we get a better acceptance test

rust/src/partitions.rs
=> Add rusdocs on partitions

rust/src/delta.rs, rust/src/storage/mod.rs
=> Add rustdocs for the errors

python/Cargo.toml
Bump Python crate version to `0.4.5`
=> Bump Python crate version to v.0.4.5

.github/workflows/python_release.yml, README.adoc
=> Automate python doc releases

python/deltalake/table.py, python/docs/source/usage.rst, python/src/lib.rs, python/tests/test_table_read.py, rust/README.md, rust/src/action.rs, rust/src/delta.rs
Add createdTime in Metadata
closes #195
=> Add createdTime in Metadata

.github/workflows/python_build.yml, .github/workflows/python_release.yml
Fix automated python docs release job.
=> test python doc release

rust/src/storage/azure.rs, rust/src/storage/file/mod.rs, rust/src/storage/mod.rs, rust/src/storage/s3/mod.rs, rust/tests/s3_test.rs
Add delete_obj in StorageBackend
=> Add delete object in StorageBackend

README.adoc
This makes the README a bit more clear on what our project status is.
=> Refactor and clean up the README

Cargo.lock, python/Cargo.toml, rust/Cargo.toml, rust/src/delta.rs, rust/tests/datafusion_test.rs
Get ready for the crates.io release.
closes #211
=> bump arrow and datafusion to 4.x

python/deltalake/table.py
This will help ensure that Python is only loading what's necessary
Fixes #220
=> Allow to_pyarrow_table() to take an optional list of partitions

rust/src/storage/s3/mod.rs
closes https://github.com/delta-io/delta-rs/issues/224.
=> honor AWS_REGION env var for S3 endpoint override

python/Cargo.toml, python/deltalake/schema.py, python/tests/test_schema.py, rust/src/schema.rs
Add valueContainsNull for the MapType in DeltaTable schema
=> Add valueContainsNull for the MapType in DeltaTable schema

.github/workflows/build.yml, Cargo.lock, python/Cargo.toml, rust/Cargo.toml
=> Add back azure support after the crates release

python/Cargo.toml
Add requires for maturin in Python bindings
#234
=> Add requires for maturin in Python bindings

python/Cargo.toml, python/deltalake/table.py, python/src/lib.rs, python/tests/test_table_read.py
Add `get_file_paths_by_partitions()` method in Python bindings
=> Add get_file_paths_by_partitions in Python bindings

rust/tests/azure_test.rs
I deleted these resources in my Azure account :shrug:
=> Disable the Azure integration test

Cargo.lock, python/src/lib.rs, ruby/src/lib.rs, rust/src/bin/delta-inspect.rs, rust/src/delta.rs
Return &str to avoid clone in get_files api.
=> avoid clone in get_files api

.github/workflows/python_build.yml, .github/workflows/python_release.yml, python/.gitignore, python/Cargo.toml, python/Makefile, python/README.md, python/deltalake/__init__.py, python/deltalake/schema.py, python/deltalake/table.py, python/docs/source/_ext/edit_on_github.py, python/docs/source/conf.py, python/mypy.ini, python/pyproject.toml, python/tests/test_schema.py
- Improve Python code quality by using [black](https://github.com/psf/black), [mypy](https://github.com/python/mypy) and [isort](https://github.com/PyCQA/isort) together.
- Create a Makefile to improve the local development with Python binding
- Use Makefile in the CI
=> Improve dev experience with Python binding

rust/src/storage/s3/dynamodb_lock.rs
fix new error from the latest rust release.
=> fix new clippy error

python/Makefile, python/deltalake/table.py, python/docs/source/conf.py, python/setup.cfg, python/tests/conftest.py, python/tests/test_version.py
also extend typechecks to python tests
=> fix python docs build

rust/src/storage/mod.rs
When using the s3-rustls feature instead of s3, the s3 backend module is not compiled.
Import deltalake with:
`deltalake = { git = "https://github.com/delta-io/delta-rs/", rev = "9597c3073fcf5202adf1723cb7a2cdc108820da3", features = ["s3-rustls"] }`
Then try `storage::parse_uri("s3://xxx/yyy")`. It will return an `InvalidScheme` error.
None
=> [fix] s3 code not compiled when using s3-rustls

rust/src/delta.rs, rust/tests/simple_commit_test.rs
While introducing changes from #305 in kafka-delta-ingest, I figured out that it was not enough. Because in previous custom commit loop, the transaction was being created on each retry which was okay. But now, since we try to use the same transaction for each try in order to avoid duplicates of tmp files, we also have to call `table.update()` before each try to get the latest version. However the `DeltaTransaction` holds mutable reference to `DeltaTable` so you cannot call an update on it.  So there's 2 possible ways on achieving that:
- Make `delta_table` public in `DeltaTransaction`. This will allow us to access to table object within transaction to trick borrow checker, this repeats the behaviour in delta-rs commit_loop as it's implemented within `DeltaTransaction` self scope. I don't …
=> Introduce try_commit_transaction in DeltaTable

rust/src/delta_datafusion.rs, rust/tests/datafusion_test.rs
Provide (aggregated) null counts in table provider.
=> Compute null count in table provider

python/Cargo.toml
bump version for new python release
=> prepare for python 0.5.1 release

.github/workflows/build.yml
Run build ci job on release branches
=> run build ci job on release branches

rust/src/delta_datafusion.rs, rust/tests/datafusion_test.rs
This patch adds max and min values to Statistics.
=> Add max and min values to Statistics

rust/Cargo.toml
bump rust version in preparation for the next release
=> bump rust version in preparation for the next release

Cargo.lock, README.adoc, python/Cargo.toml, python/deltalake/table.py, python/src/lib.rs, python/tests/test_table_read.py, rust/src/delta.rs
Expose update_incremental API to python binding. This enables streaming update use-case in python.
=> expose update_incremental API to python binding

.github/workflows/python_release.yml, python/README.md, python/docs/source/usage.rst
* only release new doc after successful pypi release
* document steps for creating new python release
* update docs to reference the new `to_pandas` method
=> update python related docs

Cargo.lock, python/Cargo.toml, rust/Cargo.toml, rust/src/delta_datafusion.rs
Upgrade arrow/parquet/datafusion/py03 versions
Closes #330
=> Upgrade arrow, parquet and datafusion

rust/src/delta.rs
=> perform incremental update after transaction commit

rust/src/delta.rs, rust/tests/read_delta_test.rs
=> Add clear table state in load_version when no checkpoint found.

rust/src/delta.rs, rust/src/partitions.rs, rust/tests/read_delta_test.rs
=> Modify get_files_by_partitions to use partition values

.github/workflows/python_release.yml
This is blocking python binding release
=> fix typo in python release CI config

.github/workflows/build.yml, .github/workflows/ruby_build.yml
Cache cargo builds to speed up CI
=> cache cargo builds

rust/src/storage/file/mod.rs, rust/src/storage/file/rename.rs
Try to implement the same behavior of swap parameter in Windows.
- closes #377
=> Implement consistent behavior in Windows with regard to swap parameter.

README.adoc
Their code has been moved out of arrow to separate repository.
=> Update datafusion and ballista links in README

Cargo.lock, rust/Cargo.toml, rust/src/bin/delta-inspect.rs
=> Upgrade to DataFusion 5.0

Cargo.lock, python/README.md, rust/README.md, rust/examples/read_delta_table.rs
Add examples for reading delta table with Rust API. Might be helpful for newcomers.
=> Add examples for reading delta table with Rust API.

python/pyproject.toml, python/stubs/deltalake/deltalake.pyi
- Following these PR discussions: https://github.com/delta-io/delta-rs/pull/381 and https://github.com/delta-io/delta-rs/pull/378
=> Update pyproject definition in pyproject.toml

.github/workflows/python_build.yml, .github/workflows/python_release.yml, python/Makefile, python/README.md
Add a build makefile task used by the Github Action workflows.
=> Add a Makefile build task in the Python binding

rust/src/delta.rs, rust/tests/simple_commit_test.rs
The goal of this PR is to remove the confusion when working with tx api. The `DeltaTransactionError` is a bloat (imo), most of it is obsolete and the only `VersionAlreadyExists` is used. These changes remove the `DeltaTransactionError` and moves `VersionAlreadyExists` to the `DeltaTableError`.
The main reason why I opened this is when I've started to work on `DynamoError::NonAcquirableLock` in KDI. 
To get this, I need to traverse the 
```
DeltaTableError -> DeltaTransactionError -> StorageError -> DynamoError
```
but there's also possible way is 
```
DeltaTableError -> StorageError -> DynamoError
```
So which one to use? This brings the confusion as users should traverse through the code to figure out. Also the tx api uses  `DeltaTransactionError` on some functions, but `DeltaTableError` …
=> Clean up DeltaTransactionError

.github/workflows/build.yml, Cargo.lock, python/Cargo.toml, python/src/lib.rs, rust/Cargo.toml, rust/src/delta_datafusion.rs, rust/src/lib.rs, rust/tests/datafusion_test.rs
Point datafusion to a temporary fork that's compatible with Arrow 6.x.
cc @Dandandan @viirya
=> reenable datafusion integration with temporary fork

python/Cargo.toml
-  Bump Python binding to 0.5.3
=> Release Python binding version 0.5.3

rust/tests/read_simple_table_test.rs
Fixing test to compare sorted vectors.
[Previous PR #431](https://github.com/delta-io/delta-rs/pull/431)
=> Fixing test to compare sorted vec

rust/README.md, rust/src/lib.rs
=> Update datafusion links

README.adoc
=> README: mark Checkpoint creation as done for Rust

rust/src/storage/file/rename.rs
Seems async rename under Windows is flaky due to no native rename if not exists support.
Use a shared lock to prevent threads renaming at the same time.
=> Try to fix flaky rename under Windows

python/deltalake/fs.py
Trying to fix CI build by fixing some mistakes in docstring
=> Fix python build

rust/src/checkpoints.rs
We notice a huge memory overhead when creating checkpoints in large tables. E.g.:
- table normal state: 3.5GB
- after creating checkpoint: 13.4GB
The cause of the issue is the using single record batch when writing to the parquet file (see changes). When changing it from `total_len` to `5000` we lowered mem consumption just to 400MB, e.g.:
- table normal state: 3.5GB
- after creating checkpoint: 3.9GB
The use of 5k rows per batch was suggested by @nevi-me (cc @xianwill) for kafka-delta-ingest data files. So they might have more context of that number.
The "downside" of that change is the slight increase in resulting checkpoint size for 275MB to 283MB for the use case above (which is negligible for us at least)
=> Fix memory overhead when creating checkpoint

rust/Cargo.toml
=> Update datafusion version to 6

python/src/lib.rs, rust/src/delta.rs, rust/tests/read_delta_test.rs
=> Return complete history

rust/src/schema.rs
=> Fix Delta metadata transaction schema

.github/workflows/python_release.yml
Adds macOS 11 to python builds
- closes #536
=> add macOS 11

python/Cargo.toml
- Preparing the release of the Python binding version 0.5.5
=> Release of the Python binding version 0.5.5

Cargo.lock, rust/Cargo.toml, rust/src/delta_datafusion.rs
Upgrade datafusion, arrow, parquet to get new functionality, performance improvements and fixes into delta-rs.
=> Upgrade DataFusion, Arrow, Parquet dependencies

rust/src/delta_config.rs, rust/src/storage/s3/mod.rs
Fix new warnings introduced by latest stable rust release.
=> fix clippy warnings

.github/workflows/python_build.yml, .github/workflows/python_release.yml, Cargo.lock, python/Cargo.toml, rust/Cargo.toml, rust/src/delta_datafusion.rs
Upgrade the packages.
```
arrow 9 → 11
parquet 9 → 11
datafusion 7 → repository main branch
pyo3 0.15 → 0.16
```
=> Upgrade `arrow, parquet, datafusion` version

Cargo.lock, python/Cargo.toml, python/pyproject.toml
- Bump version of maturin to `0.12.12`
- Prepare the release of the new version of the Python binding `0.5.7`
=> Release of the Python binding version 0.5.7

proofs/src/main.rs
A good suggestion from by the author of stateright :)
=> [proof] make sure lock at least expires once

dynamodb_lock/Cargo.toml, dynamodb_lock/README.md
Prepare dynamodb_lock for crates.io publish.
=> publish dynamodb_lock to crates.io

Cargo.lock, rust/Cargo.toml, rust/src/delta_datafusion.rs
=> upgrade to datafusion 8

.github/workflows/python_release.yml, python/Makefile
- Refactoring of the Python release Github action to use `maturin-action` Github action
- [maturin-action](https://github.com/messense/maturin-action)
=> Refactoring of the Python release Github action

python/deltalake/writer.py, python/tests/test_writer.py
We weren't trimming the paths before creating add actions. When we used an absolute `table_uri`, we used absolute paths. When we used a relative `table_uri`, we would duplicate the root relative path in the add actions, making the table unreadable.
Fixes #617.
=> fix: Use relative paths for add paths

rust/src/storage/s3/mod.rs
- When creating the `Region::default()` with Rusoto in `S3StorageBackend`, we must set the `AWS_REGION` environment variable before
- Little refactoring to regroup all the environment variables 
- closes #559
=> Fix the AWS_REGION environment variable configuration in S3 backend

rust/src/writer/json.rs, rust/src/writer/record_batch.rs, rust/src/writer/utils.rs
Drop partitions columns when writing and add corresponding unit tests.
- closes #657
=> JSON Writer writing partitions values fix

rust/src/writer/stats.rs
Currently builds on main fail because of clippy linting, this PR fixes that
=> Fix linting / build on main

Cargo.lock, rust/Cargo.toml, rust/src/storage/mod.rs, rust/src/storage/s3/mod.rs
Add support for HTTPS_PROXY env var in http client
- closes #637
=> feat: add support for HTTPS_PROXY env var

.github/workflows/build.yml, dynamodb_lock/src/lib.rs, rust/src/lib.rs, rust/src/operations/mod.rs, rust/src/storage/azure/mod.rs, rust/src/storage/mod.rs, rust/src/storage/s3/mod.rs
Docs were not part of CI checks and thus have become broken over time. Keeping them working will make it easier to release.
=> fix: get docs building and add to CI checks

python/src/lib.rs, python/tests/test_table_read.py
Statistics are recorded as JSON, but we need to cast them to the appropriate type when building dataset fragment expressions. We were doing so for the partition values, but not for the minimum and maximum values. This meant that predicate pushdown didn't work on tables that had statistics with values that weren't JSON serializable (timestamps, decimals, dates).
* Fixes #734
=> Cast min and max too when parsing stats

.github/workflows/build.yml, Cargo.lock, Cargo.toml, rust/Cargo.toml, rust/src/builder.rs, rust/src/storage/mod.rs, rust/src/storage/utils.rs, rust/src/test_utils.rs, rust/tests/integration_checkpoint.rs, rust/tests/integration_commit.rs, rust/tests/integration_datafusion.rs, rust/tests/integration_read.rs
Adding integration tests for GCS.
=> feat: add gcs integration tests

python/docs/source/index.rst, python/docs/source/usage.rst
A few minor fixes to the great usage docs @roeap wrote for filesystems.
Also added a short into to the landing page.
=> [Python][Docs] Add description to landing page

.github/workflows/python_build.yml, rust/src/action/parquet_read/mod.rs, rust/src/delta_arrow.rs, rust/src/delta_config.rs, rust/src/operations/create.rs, rust/src/operations/mod.rs, rust/src/operations/write.rs, rust/src/optimize.rs, rust/src/storage/file.rs, rust/src/table_state.rs, rust/src/test_utils.rs, rust/src/writer/stats.rs, rust/tests/checkpoint_writer.rs, rust/tests/command_optimize.rs, rust/tests/command_vacuum.rs, rust/tests/common/adls.rs, rust/tests/common/clock.rs, rust/tests/common/mod.rs, rust/tests/common/s3.rs, rust/tests/datafusion_test.rs, rust/tests/fs_common/mod.rs, rust/tests/read_delta_partitions_test.rs, rust/tests/read_delta_test.rs
Fix new warnings from clippy. 😄
=> Fix warnings

rust/src/delta.rs
=> comment cleanup

CONTRIBUTING.md, README.adoc
This is the published version of the google doc https://docs.google.com/document/d/1iKVdnilMCS6qziBBVohXw2-UX_Ld2K6AAjLTZHcYhQ0/edit#heading=h.iezbyetoxtf
=> Add contributing page with roadmap and good first issues link

.github/workflows/build.yml, .github/workflows/python_release.yml
- Fix the Github Action for releasing the Python binding
=> Fix the Python Release Github Action

Cargo.lock, rust/Cargo.toml, rust/src/builder/mod.rs, rust/src/storage/s3.rs
TODO:
- closes #854
- closes #835
https://github.com/apache/arrow-rs/blob/8a54e95850fe27ac5865a02ef4be2de0937de5b3/object_store/CHANGELOG.md
=> chore: update object-store dependency

.github/workflows/dev_pr.yml, delta-inspect/Cargo.lock, delta-inspect/src/main.rs, rust/src/test_utils.rs
Fix lint issues from latest cargo release.
=> chore: fix new lints from new cargo

dynamodb_lock/Cargo.toml
Bump version for new release in crates.io
blocks #973
=> bump version for dynamodb_lock crate

delta-inspect/src/main.rs
=> Fix typo in delta-inspect

rust/src/delta_datafusion.rs
Adds a simple unit test for `to_scalar_value`
P.S. Rust beginner here, trying to get to know the language a bit better
=> Add test for: to_scalar_value

rust/src/delta_arrow.rs
Adds a test for `null_count_schema_for_fields`
=> add test for null_count_schema_for_fields

rust/Cargo.toml
Cargo will not publish without this.
=> chore: remove star dependencies

rust/src/writer/json.rs
Adds a test for `rust/src/writer/json.rs::extract_partition_values`
=> add test for extract_partition_values

rust/src/lib.rs
Fix out-of-date doc about querying datafusion.
=> fix: update out-of-date doc about datafusion

dynamodb_lock/Cargo.toml
cc @houqp @rtyler  will need one of you to help with publishing a new release.
For example:
- closes #1191
=> chore: increment dynamodb_lock version

README.adoc
Purpose: this adds a badge with the monthly project downloads.  This library gets lots of downloads and it's good to highlight this to users, so they know we have a large userbase.
=> Add monthly PyPi downloads badge to README

python/Cargo.toml, rust/Cargo.toml
Just the bumping the version numbers, but hoping to squeeze this into the next release (#1216)
=> build(deps): bump datafusion

CHANGELOG.md, delta-inspect/Cargo.toml, python/Cargo.toml, rust/Cargo.toml
Update changelog for Rust 0.8.0 release
Closes #1184.
=> docs: update changelog for Rust 0.8.0 release

python/pyproject.toml
This pins pandas to allow the tests in `main` to pass tests
=> Pin pandas for the Python binding to <2

CHANGELOG.md
Update changelog for Rust 0.9.0 release
Closes #1238.
=> docs: update changelog for 0.9.0 release

CHANGELOG.md
Update changelog for Rust 0.10.0 release
Closes #1327.
=> docs: add changelog for rust 0.10.0

python/Cargo.toml
Preparing for release of next Python version.
=> chore: increment python version

rust/Cargo.toml
Just making sure we don't forget this for the next release
=> chore: update Rust package version

.github/workflows/build.yml
Hoping this will mitigate our ci failures for windows.
=> ci: disable full debug symbol generation

python/Cargo.toml, rust/Cargo.toml, rust/examples/recordbatch-writer.rs, rust/src/operations/delete.rs, rust/src/table_state_arrow.rs, rust/tests/add_actions_test.rs
Updates arrow and datafusion to latest dependencies.
=> chore: bump datafusion to 25

README.adoc
Updates the features table in the README to accurately reflect the current status.
- closes #1404 
N/A
=> docs: update features table in README

python/src/lib.rs
https://rust-lang.github.io/rust-clippy/master/index.html#redundant_async_block
N/A
N/A
=> refactor: rewrite redundant_async_block

python/deltalake/writer.py
=> chore: fix mypy failure

python/Cargo.toml
=> chore: bump python version to 0.10.2

python/tests/conftest.py, python/tests/test_fs.py
See if we can prevent this common CI failure.
=> ci: extend azure timeout

.github/workflows/python_release.yml
Fixes failure in: https://github.com/delta-io/delta-rs/actions/runs/6141418893/job/16661692055
This is the same fix we applied for normal ci in https://github.com/delta-io/delta-rs/pull/1615/files
=> ci: fix python release

Cargo.toml, rust/Cargo.toml, rust/src/operations/mod.rs, rust/src/storage/mod.rs, rust/src/writer/record_batch.rs
=> chore: update datafusion to 31, arrow to 46 and object_store to 0.7

Cargo.toml, python/src/filesystem.rs
relax chrono pin to improve downstream compatibility.
=> chore: relax chrono pin to 0.4

README.md, python/docs/source/usage.rst
Documents the newly exposed delete operation that was added by #1687.
I also did some tidying up of the documentation: aligning table columns and removing trailing whitespaces.
=> docs(python): document the delete operation

rust/src/operations/write.rs
Added an example to `write.rs` docs
- closes #1169
=> docs: add a write example to delta.rs

python/Cargo.toml
=> chore: bump the python package version

python/pyproject.toml
Removes the `pandas` pin.
Resolves #1745
=> fix: remove `pandas` pin

Cargo.toml, python/src/error.rs, rust/Cargo.toml, rust/src/operations/optimize.rs, rust/src/writer/record_batch.rs, rust/tests/common/datafusion.rs
Updates arrow and datafusion dependencies to latest.
=> chore: update datafusion

python/Cargo.toml
In preparation for next release.
=> chore: bump Python package version

README.md
This Pull Request fixes a typographical error in the README.md file.
- Corrected "commited" to "committed" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.
=> docs: remove typo

.github/CODEOWNERS
update code owners
- closes #1794
=> chore: update codeowners to reflect new repo struct

CONTRIBUTING.md
=> docs: tell how to claim an issue

crates/deltalake-core/src/operations/transaction/conflict_checker.rs
Just running `cargo clippy --fix` once to get main green again ...
=> chore: clippy

crates/deltalake-core/src/operations/optimize.rs
Enable usage of z-order optimization on columns that have capitalization.
- closes #1586
=> fix: case sensitivity for z-order

crates/deltalake-core/src/test_utils.rs
The GCS tests seem to be failing sometimes, looked around and hoping this change fixes that.
=> fix: flakey gcs test

python/Cargo.toml
preparing for minor fix release
=> chore: bump version python

python/Cargo.toml
=> chore(python): bump version

crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/core/Cargo.toml, crates/deltalake/Cargo.toml, crates/gcp/Cargo.toml
These are some commits that happen to be in the rust-v0.17.0 tagged changes, already published but not yet merged.
=> chore: 0.17.0 publish changes

docs/integrations/delta-lake-dask.md
=> docs: dask integration fix formatting typo

docs/integrations/delta-lake-dagster.md
use `dagster-deltalake-polars ` instead of `dagster-polars`
=> docs: use dagster deltalake polars library

crates/core/src/operations/merge/mod.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/protocol/mod.rs, crates/core/tests/command_merge.rs
reintroduces the concurrency control with fix
=> fix: merge concurrency control

crates/core/src/operations/merge/mod.rs
Fix broken test case with partitions
- fixes https://github.com/delta-io/delta-rs/issues/2158
=> fix: merge pushdown handling

crates/core/src/protocol/checkpoints.rs, python/tests/test_checkpoint.py
We didn't clean up failed commits when possible.
- fixes https://github.com/delta-io/delta-rs/issues/2351
=> fix: remove tmp files in cleanup_metadata

python/Cargo.toml
=> chore: bump python 0.16.4

python/Cargo.toml
=> chore: bump python for 0.17 release

crates/core/Cargo.toml, python/Cargo.toml
=> chore: bump the core crate for its next release

crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/deltalake/Cargo.toml, crates/deltalake/src/lib.rs, crates/gcp/Cargo.toml, python/Cargo.toml, python/src/lib.rs
this is already tagged and pushed :smiling_face_with_three_hearts:
=> chore: a bunch of tweaks to get releases out the door

docs/why-use-delta-lake.md
=> docs: fix typo

python/Cargo.toml
=> chore: bump python 0.17.5

python/Cargo.toml
=> chore: bump python 0.18.2

.github/CODEOWNERS
I would like to have more email. 
Not receiving enough email.
=> ci: update CODEOWNERS

python/Cargo.toml
=> chore: prepare python release 0.18.3

.github/workflows/build.yml, .github/workflows/python_build.yml
may this satisfy the github actions
=> chore: try an alternative docke compose invocation syntax

.github/CODEOWNERS
=> chore: add to code_owner crates

crates/core/Cargo.toml, crates/core/src/operations/optimize.rs
This is currently a work in progress just demonstrating the test failure
* Fixes #1648
=> fix: optimize Spark written tables

crates/core/src/schema/partitions.rs
I actually used this functionality :smile:
It was removed in #2037 but I think it's handy and worth keeping around :shrug:
=> feat: restore the TryFrom for DeltaTablePartition

crates/core/src/operations/optimize.rs
=> fix(rust): `max_spill_size` default value

crates/aws/Cargo.toml, crates/aws/src/lib.rs
This PR will use actively maintained [backon](https://github.com/Xuanwo/backon) to replace backoff.
https://xuanwo.io/2024/08-backon-reaches-v1/
=> chore(aws): use backon to replace backoff

python/Cargo.toml
=> chore: update python

CHANGELOG.md
=> chore: update the changelog with the latest rust merges

docs/usage/merging-tables.md, mkdocs.yml
This PR adds a MERGE guide to the docs. Will close #2915 
Signed-off-by: Avril Aysha <68642378+avriiil@users.noreply.github.com>
=> docs: add merge guide

crates/core/src/kernel/models/actions.rs
Fixes a check so readerFeatures is enabled on version 3 or higher
=> fix: enable readerFeatures in minReaderVersion 3

python/Cargo.toml
this has already been released, woo woo
=> chore: bump the python version for release

docs/usage/merging-tables.md
Forgot a = when I added the rust docs
=> fix: docs rendering

python/Cargo.toml
=> chore: 0.24 py release

Cargo.toml, crates/lakefs/Cargo.toml
:no_entry_sign: `*` :no_entry_sign:
=> chore: minor changes to allow 0.24.0 to be published

docs/integrations/delta-lake-daft.md
=> docs: fix broken links

python/src/schema.rs, python/tests/test_generated_columns.py, python/tests/test_schema.py
=> fix: properly encode metadata field values when creating actions

crates/aws/src/lib.rs
Fixing a documentation typo -- s/implemtnation/implementation/
N/A
N/A
=> fix(typo): s/implemtnation/implementation/

.github/workflows/python_release.yml
I guess it's fine to switch to rustls by default to decrease the binary size
=> chore: use rustls

README.md
Generated columns is supported now.
=> chore: update readme for Generated columns

crates/core/src/operations/write/mod.rs
- supersedes https://github.com/delta-io/delta-rs/pull/2923
=> fix: compare before after schema before creating action

crates/core/src/kernel/snapshot/log_data.rs, python/tests/test_stats.py
When parsing stats during checkpoint creation, the timestamps get truncated see [protocol footnote](https://github.com/delta-io/delta/blob/master/PROTOCOL.md):
> Timestamp columns are truncated down to milliseconds
If min values get truncated this is not an issue, but for max values it is, so when we see possible rounded values we add 1 ms so that we don't incorrectly filter files.
- fixes https://github.com/delta-io/delta-rs/issues/3133
- fixes https://github.com/delta-io/delta-rs/issues/2571
=> fix: timestamp truncation in stats parsed

Cargo.toml, crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/catalog-glue/Cargo.toml, crates/catalog-unity/Cargo.toml, crates/core/Cargo.toml, crates/core/src/operations/convert_to_delta.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/optimize.rs, crates/core/src/writer/json.rs, crates/deltalake/Cargo.toml, crates/gcp/Cargo.toml, crates/hdfs/Cargo.toml, crates/lakefs/Cargo.toml, crates/mount/Cargo.toml, crates/test/Cargo.toml
There are some subsequent failures and changes which need to be made here to go green, but those will come in follow up commits
=> chore: upgrade the kernel version and bump our majorish versions too

crates/core/src/logstore/mod.rs
Why the data is invalid is an exercise left to the reader :smile:
Fixes #3297
=> fix: prevent panics when peek_next_commit() encounters invalid data

crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/logstore/mod.rs
This PR adds some missing delta file types to the check in is_deltatable().
- closes #3314
=> fix: check for all known valid delta files in is_deltatable

docs/integrations/delta-lake-datafusion.md
Update docs to match DataFusion example
- closes #3221
https://datafusion.apache.org/python/user-guide/data-sources.html#delta-lake
=> docs: update dataFusion integration example

python/src/lib.rs, python/src/reader.rs
Returns a lazy recordbatchreader
=> perf: use lazy sync reader

python/pyproject.toml
- closes https://github.com/delta-io/delta-rs/issues/3323
=> chore: remove pyarrow upper

docs/usage/merging-tables.md
Added some best practices which were discussed on Slack for creating efficient merge predicates.
=> docs: update merge-tables.md with "Optimizing Merge Performance" section

crates/core/src/kernel/snapshot/parse.rs
- closes https://github.com/delta-io/delta-rs/issues/3354
=> fix: parse snapshot

docs/usage/optimize/small-file-compaction-with-optimize.md
fix: correct Python docs for incremental compaction on OPTIMIZE
N/A
https://delta-io.github.io/delta-rs/usage/optimize/small-file-compaction-with-optimize/#handling-incremental-updates-with-optimize
=> fix: correct Python docs for incremental compaction on OPTIMIZE

crates/core/src/logstore/config.rs, crates/core/src/logstore/storage/retry_ext.rs
Just noticed these while doing other work
=> chore: put a couple symbols behind the right feature gate

crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/catalog-glue/Cargo.toml, crates/catalog-unity/Cargo.toml, crates/core/Cargo.toml, crates/deltalake/Cargo.toml, crates/gcp/Cargo.toml, crates/hdfs/Cargo.toml, crates/lakefs/Cargo.toml, crates/mount/Cargo.toml, crates/test/Cargo.toml
=> chore: bump versions of rust crates for another release party

crates/core/Cargo.toml, crates/derive/Cargo.toml, crates/hdfs/Cargo.toml, crates/mount/Cargo.toml, dev/publish.sh
A number of minor changes were required in order to get this release published
=> chore: commit the contents of the 0.26.0 release

python/Cargo.toml
Make version ready for a release over the weekend after caching is hooked up by @roeap :)
=> chore: prepare py-1.0 release

crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/tests/integration_datafusion.rs
This is a rebase  of #3377 
Closes #3377
=> feat: optimize datafusion predicate pushdown and partition pruning

Cargo.toml, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/arrow/mod.rs, crates/core/src/kernel/scalars.rs, crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/operations/cast/mod.rs, crates/core/src/operations/convert_to_delta.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/optimize.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write/execution.rs, crates/core/src/operations/write/generated_columns.rs, crates/core/src/operations/write/mod.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/table/state_arrow.rs, crates/core/src/test_utils/factories/data.rs, crates/core/src/writer/json.rs, crates/core/src/writer/record_batch.rs, crates/core/tests/integration_datafusion.rs, crates/deltalake/Cargo.toml, crates/deltalake/examples/recordbatch-writer.rs, python/src/lib.rs, python/src/schema.rs
stacked on: #3461
updating to latest kernel (main) : 0.11 release is imminent.
=> chore: update kernel

.pre-commit-config.yaml, Cargo.toml, docs/usage/examining-table.md, docs/usage/optimize/small-file-compaction-with-optimize.md, python/docs/source/usage.rst
Doing some more config so we can get the typos to pass.
=> chore: more typos

Cargo.toml
Updating to released kernel version.
=> chore: update kernel to 0.11

python/src/writer.rs, python/tests/test_casting.py, python/tests/test_threaded.py
I misinterpreted the safe param, so I inverted it before :P Ooops
=> fix: set casting safe param to False

.github/workflows/python_release.yml
=> chore: update runner

.github/workflows/python_build.yml, python/tests/pyspark_integration/utils.py
=> chore: set java version to 21 for pyspark 4.0

crates/core/src/operations/vacuum.rs
The vacuum operation was not using the correct snapshot for the VacuumEnd operation. It was also returning the original snapshot instead of the latest snapshot.
Before this fix, the following was happening:
- vacuum
- if there was nothing to vacuum, everything was fine, no changes to the DB
- if there were files to delete:
- it did a VacuumStart based on `this.snapshot` (correct)
- it did a VacuumEnd based on `this.snapshot`, which is stale
- e.g. triggered `Attempting to write a transaction 64 but the underlying table has been updated to 64`
- it returned `this.snapshot` which had not been updated
- the next commit was 2 versions behind (the returned table was from before vacuum)
- e.g triggered `Attempting to write a transaction 64 but the underlying table has been updated to 65`
- …
=> fix: use proper DeltaTableState for vacuum commits

crates/core/src/kernel/schema/partitions.rs
Another kernel log replay pre-factor. Kernel contains an advanced implementation to handle file skipping. To leverage this with our current partition filter API, we need to convert `PartitionFilter`s into kernel `Predicate`s, which is what we do in this PR.
=> feat: convert partition filters to kernel predicates

crates/core/src/kernel/arrow/engine_ext.rs, crates/core/src/logstore/config.rs, crates/core/src/logstore/mod.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/update_table_metadata.rs, crates/core/src/operations/write/generated_columns.rs, crates/core/src/table/config.rs, crates/core/tests/dat.rs, crates/core/tests/integration_datafusion.rs, crates/derive/src/lib.rs, crates/lakefs/src/client.rs, crates/lakefs/src/logstore.rs, python/src/datafusion.rs, python/src/error.rs
Seems we are not running clippy against latest rust version - should probably update our CI a bit.
=> chore: latest clippy

crates/core/src/operations/vacuum.rs
Upgrade the vacuum operation to specify versions to retain when performing a vacuum operation.
Closes https://github.com/delta-io/delta-rs/issues/3530
=> feat: vacuum with version retention

crates/core/src/operations/merge/mod.rs, crates/core/src/operations/write/execution.rs, crates/core/src/operations/write/mod.rs, crates/mount/src/lib.rs
Since I can't push updates to #3557, this pull request adds a little test but is otherwise identical
Closes #3557
=> fix: scan time was always 0 for merge metrics

docs/integrations/delta-lake-daft.md, python/Cargo.toml
This pull request should fix the broken links check in our CI, and includes a bonus version bump for another Python release
=> docs: fix broken daft links (how daft)

.github/workflows/python_release.yml
=> feat: build musl wheels upon release

python/Cargo.toml
=> chore: bump python

crates/core/Cargo.toml, crates/deltalake/Cargo.toml
This small release will have a performance fix that we should get into
people's hands now
=> chore: bump to a minor version for a small core release with the new kernel
