crates/deltalake-core/src/data_catalog/mod.rs, crates/deltalake-core/src/lib.rs, python/src/lib.rs
- Improved error message on catalog lookup failure
- Added `native-tls` feature dependency to Glue feature
- Added error preventing using `glue` and `glue-native-tls` in the same build
- closes #1860
=> fix: improve catalog failure error message, add missing Glue native-tls feature dependency

python/src/filesystem.rs
Current implementation of `ObjectOutputStream` does not invoke flush when writing out files to Azure storage which seem to cause intermittent issues when the `write_deltalake` hangs with no progress and no error. 
I'm adding a periodic flush to the write process, based on the written buffer size, which can be parameterized via `storage_options` parameter (I could not find another way without changing the interface). I don't know if this is an acceptable approach (also, it requires string values)
Setting the `"max_buffer_size": f"{100 * 1024}"` in `storage_options` passed to `write_deltalake` helps me resolve the issue with writing a dataset to Azure which was otherwise failing constantly.
Default max buffer size is set to 4MB which looks reasonable and used by other implementations I've …
=> fix: add buffer flushing to filesystem writes

crates/deltalake-core/src/lib.rs
According to the issue test should fail to load table without snapshot (version 0) but test is written to test that it is possible to read and load Delta Table with version 0 into the Rust (functions `open_table` and `open_table_with_version` work)
- closes #1831
=> test: loading version 0 Delta table

crates/deltalake-core/src/operations/optimize.rs, crates/deltalake-core/tests/command_optimize.rs
This PR prunes each merge bin with only 1 file, even though there are multiple merge bins.
- closes #1901 
This PR adds test_idempotent_with_multiple_bins() for testing.
=> fix: prune each merge bin with only 1 file

python/deltalake/table.py
This change is mainly for typing purposes so that downstream usage can supply a Path or PathLike object rather than just Path.
=> fix: support os.PathLike for table references

crates/deltalake-core/Cargo.toml, crates/deltalake-core/src/operations/cast.rs, crates/deltalake-core/src/operations/mod.rs, crates/deltalake-core/src/operations/optimize.rs, crates/deltalake-core/src/operations/write.rs
A dependency from optimize on the cast_record_batch function was added which cannot be met without the `datafusion` feature enabled
See #1926
=> chore: relocate cast_record_batch into its own module to shed the datafusion dependency

crates/deltalake-core/src/data_catalog/unity/models.rs
The Databricks list table summaries API returns an empty 200 `{}` response when you try to list tables in a schema with no tables. This will cause an error in delta-rs during deserialisation because the tables field was requried in the model. 
To fix the issue I have added a default tag to the model and added some tests.
(Hyrum's Law FTW)
=> fix: handle empty table response in unity api

.github/workflows/docs_release.yml
This will trigger a release action for docs when a pull request to docs (`mkdocs.yml` or anything in `docs/` is changed) is merged to main. This would help with more frequent releases to docs without waiting for a full release or bothering admins to run the docs release manually, especially handy at this time when lots of changes are being made to the docs.
One caveat is that this will replace the current public docs (which is what we intend to achieve with this) including the Python API docs which may not be a desirable outcome for API docstrings which are on the `main` branch but not in the latest Python release.
=> docs: add auto-release when docs are merged to main

crates/deltalake-core/src/test_utils.rs, crates/deltalake-core/tests/integration_checkpoint.rs, crates/deltalake-core/tests/integration_concurrent_writes.rs, crates/deltalake-core/tests/integration_s3_dynamodb.rs
tl;dr: this allows the following:
```sh
AWS_ENDPOINT_URL=none AWS_ACCESS_KEY_ID=KEY_ID AWS_SECRET_ACCESS_KEY=SECRET AWS_REGION=eu-central-1 cargo test
```
This allows integration tests for AWS/S3 to talk to a real AWS environment instead of localstack via setting a bunch of environment variables. This didn't previously work because `AWS_ENDPOINT_URL` must be unset for "normal" AWS (or I didn't find a valid `endpoint` setting for this). When not running against localstack, some operations, including DynamoDb table creation, are notably slower, and it's necessary to poll the `describe-table` API until the table is ready to be used.
`AWS_ENDPOINT_URL=none` is a special value that instructs the test to run without an endpoint, talking to AWS proper.
I need this because `localstack` doesn't …
=> fix: enable S3 integration tests to be configured via environment vars

crates/deltalake-core/src/delta_datafusion/expr.rs, crates/deltalake-core/src/delta_datafusion/mod.rs, crates/deltalake-core/src/operations/constraints.rs
Implements consistent formatting for constraint expressions so something like `value      <             1000` is normalized to `value < 1000`
Also includes drive by improvements.
1. Test & Fix that Datafusion expressions can actually be used when adding a constraint
2. Test & Fix that constraints can be added to column with capitalization
- closes #1971
=> fix: implement consistent formatting for constraint expressions

crates/benchmarks/src/bin/merge.rs, crates/deltalake-core/src/delta_datafusion/mod.rs, crates/deltalake-core/src/kernel/arrow/mod.rs, crates/deltalake-core/src/lib.rs, crates/deltalake-core/tests/checkpoint_writer.rs, crates/deltalake-core/tests/command_optimize.rs
Fixed few warnings picked up by lint
=> chore: fix CI breaking lint issues

docs/integrations/delta-lake-arrow.md, docs/integrations/delta-lake-datafusion.md
Purpose: document the DataFusion integration page.
Need to figure out why Delta Lake depends on DataFusion and put a little info in this guide before merging.
=> docs: datafusion integration

crates/deltalake-core/tests/command_restore.rs
Change the logic to get the timestamp to restore to from the commit file timestamp instead of history
https://github.com/delta-io/delta-rs/issues/1925
=> fix: fix the test_restore_by_datetime test

python/deltalake/table.py
This helps to avoid this [error](https://github.com/delta-io/delta-rs/issues/1998 )since you can now set to large_dtypes=False.
Also once upstream in arrow-rs there is better type coercion, this param should be able to be removed completely in the writer and merge operation.
=> feat(python): expose large_dtype param in `merge`

crates/deltalake-core/src/operations/create.rs, python/deltalake/_internal.pyi, python/deltalake/writer.py, python/src/lib.rs
- exposes the custom_metadata to pyarrow and rust writer
- addresses a bug in the create operation, we were not passing the app_metadata to the actual commit
- closes https://github.com/delta-io/delta-rs/issues/1990
=> feat(python): expose custom metadata to writers

docs/api/delta_writer.md, python/deltalake/table.py
Forgot to add WriterProperties to the docs page and mark a deprecation in the docs.
=> docs: add writer properties to docs

docs/api/delta_table/delta_table_alterer.md, mkdocs.yml, python/deltalake/table.py
Again, forgot some docs, and added missing descriptions
=> docs: add alterer

crates/deltalake-core/src/delta_datafusion/mod.rs
The existing implementation for table constrains checks may break during the write if multiple checks are executed in parallel, e.g. in partitioned tables. Using temporary tables names solves that problem
=> fix: use temporary table names during the constraint checks

.github/workflows/docs.yml, .github/workflows/docs_release.yml, .github/workflows/python_release.yml
Added a `write` permission to jobs triggering the docs release process. The job itself already had it but those triggering it did not, which was likely the cause for them faling
#2025
=> fix: github actions for releasing docs

crates/deltalake-core/src/delta_datafusion/mod.rs, crates/deltalake-core/src/kernel/arrow/mod.rs, crates/deltalake-core/src/operations/constraints.rs, crates/deltalake-core/src/operations/delete.rs, crates/deltalake-core/src/operations/merge/mod.rs, crates/deltalake-core/src/operations/optimize.rs, crates/deltalake-core/src/operations/transaction/conflict_checker.rs, crates/deltalake-core/src/operations/transaction/state.rs, crates/deltalake-core/src/operations/update.rs, crates/deltalake-core/src/operations/vacuum.rs, crates/deltalake-core/src/operations/write.rs, crates/deltalake-core/src/protocol/checkpoints.rs, crates/deltalake-core/src/table/mod.rs, crates/deltalake-core/src/table/state.rs, crates/deltalake-core/src/table/state_arrow.rs
In preparation for arrow backed table state and generally reducing our API surface, this PR just updates some call sites to use the raw metadata action and not `DeltaTableMeatadata` in the hopes of removing that all together.
=> refactor: increase metadata action usage

crates/deltalake-aws/Cargo.toml, crates/deltalake-aws/helpers.rs, crates/deltalake-aws/src/errors.rs, crates/deltalake-aws/src/lib.rs, crates/deltalake-aws/src/logstore.rs, crates/deltalake-aws/tests/common.rs, crates/deltalake-aws/tests/integration_s3_dynamodb.rs
We use an external crate, [backoff](https://crates.io/crates/backoff), to retry DynamoDb read and write operations when the error in the response is `ProvisionedThroughPutExceeded`, indicating an overload of DynamoDb wrt to the configured read and write capacity.
=> feat: retry with exponential backoff for DynamoDb interaction

README.md, crates/deltalake-core/src/operations/merge/mod.rs
Update documentation to reflect the current state of merge. Since merge now supports upserts without performing a full rewrite I'd let to mark it as "done".
There is of course further optimizations that can be performed but it is now in a usable state.
- closes #850
=> docs: update docs for merge

crates/deltalake-core/src/protocol/checkpoints.rs, python/tests/test_checkpoint.py
When metadata cleanup is executed on a delta table without checkpoints it will corrupt the table and prevent further loading. This is a high risk for people who use delta-rs since our writers do not automatically create checkpoints.
- closes #2016
=> fix: ensure metadata cleanup do not corrupt tables without checkpoints

python/deltalake/schema.py, python/stubs/pyarrow/__init__.pyi, python/tests/test_schema.py
Map `FixedSizeBinaryType` to `BinaryArray`, since Delta does not support fixed arrays.
None.
N/A
I've noticed this error when doing subsequent calls to like so:
```
import deltalake as dl
import pyarrow as pa
schema = pa.schema([
("field_a", pa.binary(4)),
])
table = pa.Table.from_pylist(
[
{"field_a": val.to_bytes(4, "little")}
for val in range(0, 100)
],
schema=schema
)
dl.write_deltalake(
"bad_table",
data=table,
mode="append",
)
dl.write_deltalake(
"bad_table",
data=table,
mode="append",
)
```
with error:
```
ValueError: Schema of data does not match table schema
Data schema:
field_a: fixed_size_binary[4]
Table Schema:
field_a: binary
```
=> feat(python): add schema conversion of FixedSizeBinaryArray and FixedSizeListType

crates/deltalake-aws/src/storage.rs, crates/deltalake-aws/tests/common.rs, python/deltalake/writer.py, python/docs/source/usage.rst
My attempt at rewording the documentation to address the changes related to `S3DynamoDbLogStore` and its configuration.
Not sure how our documentation works in the first place, and I'm not a word smith either, but at least I hope this makes things factually correct.
=> chore: update documentation for S3 / DynamoDb log store configuration

crates/deltalake-aws/src/lib.rs, crates/deltalake-aws/src/storage.rs
If the `AWS_COPY_IF_NOT_EXISTS` key exists, then we don't require instantiating a lock client or setting allow-unsafe-rename.
=> fix: reinstate copy-if-not-exists passthrough

crates/deltalake-core/Cargo.toml, crates/deltalake-gcp/Cargo.toml, crates/deltalake-gcp/src/config.rs, crates/deltalake-gcp/src/error.rs, crates/deltalake-gcp/src/lib.rs, crates/deltalake-gcp/tests/context.rs, crates/deltalake-gcp/tests/integration.rs, crates/deltalake-test/src/utils.rs, crates/deltalake/Cargo.toml, crates/deltalake/src/lib.rs, python/src/lib.rs
Adds the gcp handler back.
- closes https://github.com/delta-io/delta-rs/issues/2060
=> refactor: add deltalake-gcp crate

python/src/lib.rs
This allows calls to `merge_execute` to release the GIL to allow other python threads to carry on in parallel.
I believe this is safe because every argument is a rust-marshaled type apart from `source` which is pyarrow-marshaled and C under the hood. All pyarrow types are immutable I believe, so by this point it should be safe to read with the GIL unlocked.
it looks like there is a change in the works (https://github.com/PyO3/pyo3/pull/3610) to allow this to be an attribute but it's not ready yet. For now it looks a little ugly putting it in the closure.
=> feat: allow merge_execute to release the GIL

python/deltalake/table.py
There is a print statement in the update method of tables.py. It is not needed now. So I have removed it.
- closes #2110
=> chore: removed unnecessary print statement from update method

crates/deltalake-aws/tests/integration_s3_dynamodb.rs
This unbreaks main, but this does need to get re-enabled as soon as possible
See #2109
=> chore: temporarily ignore the repair on update test

python/Cargo.toml
@rtyler bumping python release so we can release the fix which reintroduces gcp support
=> chore: bump python

python/tests/test_fs.py
Right now we have some [issue](https://github.com/delta-io/delta-rs/pull/2120#issuecomment-1912367573)in how we identify if a location is a delta-table. This disables an affected test so we can merge PRs again without having to ignore requires CI runs.
=> fix: temporarily skip s3 roundtrip test

crates/deltalake-core/src/operations/optimize.rs, crates/deltalake-core/tests/command_optimize.rs
After the table state refactor optimize, compaction, was not writing files to the partition directory properly nor setting the partitionValues field in the Add action.
=> fix: set partition values for added files when building compaction plan

crates/deltalake-core/src/table/builder.rs
This PR make sure we clean up after ourselves when running tests by removing some folder artifacts we create in tests.
=> fix: clean-up paths created during tests

python/deltalake/table.py
Pandas was only imported for static type checking, but was actually used in the code of the module leading to import errors. Added the import similarly to `writer.py`, and updated the pandas alias in the type hints from 'pandas' to 'pd'.
- closes #2112 
x
=> fix: add missing pandas import

crates/deltalake-core/src/table/config.rs
This PR updates the table config to contain newly defined table configuration keys.
Mainly trying to keep things bite-sized for once in updating our check-point creation.
=> feat: update table config to contain new config keys

crates/deltalake-core/src/kernel/snapshot/mod.rs, crates/deltalake-core/src/kernel/snapshot/replay.rs
The new table config `delta.dataSkippingStatsColumns` changes the logic which columns should be considered when computing file statistics. Here we expose (and use) a new method on `Snapshot` which reflects the updated logic.
This PR does not contain any tests for the new code paths, but I'll test this against the reference implementation once the new checkpoint writer lands.
=> feat: expose stats schema on Snapshot

crates/deltalake-core/src/delta_datafusion/mod.rs, crates/deltalake-core/src/table/mod.rs
When using logical plans with DF, the order & location of partitioned columns did not match with physical schema. This would cause errors when logical relations were converted to physical relations.
- closes #2104
=> fix: order logical schema to match physical schema

crates/deltalake-core/src/kernel/arrow/mod.rs, crates/deltalake-core/src/protocol/checkpoints.rs
When building the arrow schema for delta checkpoints, List, Map, and Binary max/min stats are not collected. If you have a Struct column with only a List Map, or Binary field, then the arrow schema gets an empty Struct. Parquet writer fails with this:
```
ParquetParseError { source: ArrowError("Parquet does not support writing empty structs") }
```
=> fix: prevent empty stats struct during parquet write

crates/core/src/writer/json.rs, crates/core/src/writer/mod.rs
Add case to error conversion implementation to preserve structured parsing error instead of converting to plain string.
- closes #2143
=> fix(#2143): keep specific error type when writing fails

Cargo.toml, crates/azure/src/config.rs, crates/azure/src/error.rs, crates/core/Cargo.toml, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/operations/delete.rs, crates/core/src/operations/merge/barrier.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/optimize.rs, crates/core/src/operations/transaction/state.rs, crates/core/src/operations/update.rs, crates/core/tests/integration_datafusion.rs, crates/gcp/src/error.rs, crates/sql/src/parser.rs
This PR upgrades `delta-rs` to using DataFusion 35.0, which was recently released. In order to do this, I had to fix a few breaking changes, and also upgrade Arrow to 50 and `sqlparser` to 0.41.
N/A
See here for the list of PRs which required code change:
- https://github.com/apache/arrow-datafusion/pull/8703
- https://github.com/apache/arrow-datafusion/blob/ec6abece2dcfa68007b87c69eefa6b0d7333f628/dev/changelog/35.0.0.md?plain=1#L227
=> chore: upgrade to DataFusion 35.0

crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/write.rs, crates/core/src/writer/test_utils.rs, docs/_build/links.yml, docs/index.md, docs/src/python/operations.py, docs/src/rust/operations.rs, docs/usage/writing/index.md, python/deltalake/writer.py, python/docs/source/index.rst, python/src/lib.rs, python/tests/test_writer.py
First/naive implementation of `replaceWhere` for `write`. Code compiles and there is a test to verify the outcome. I would appreciate any feedback on improving the structure/implementation. For example, I copied the part of code from `delete` operation because there is no way to call that code in `delete` directly from `write` - should I look into extracting that code from `delete` to somewhere central?
Seems to also works with partitions columns.
https://github.com/delta-io/delta-rs/issues/1957
Added a section in docs
=> feat: implementation for replaceWhere

crates/core/src/operations/merge/mod.rs
This fixes an observed bug where the partition generalization was failing. A minimal repro was:
```python
from deltalake import DeltaTable, write_deltalake
import pyarrow as pa
import pandas as pd
data = pd.DataFrame.from_dict(
{
"a": [],
"b": [],
"c": [],
}
)
schema = pa.schema(
[
("a", pa.string()),
("b", pa.int32()),
("c", pa.int32()),
]
)
table = pa.Table.from_pandas(data, schema=schema)
write_deltalake(
"test",
table,
mode="overwrite",
partition_by="a"
)
new_data = pd.DataFrame.from_dict(
{
"a": ["a", "a", "a"],
"b": [None, 2, 4],
"c": [5, 6, 7],
}
)
new_table = pa.Table.from_pandas(new_data, schema)
dt = DeltaTable("test")
dt.merge(
source=new_table,
predicate="s.b IS NULL",
source_alias="s",
target_alias="t",
).when_matched_update_all().when_not_matched_insert_all().execute()
``` …
=> fix: made generalize_filter less permissive, also added more cases

crates/core/Cargo.toml, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/operations/optimize.rs, crates/core/src/operations/writer.rs, crates/core/src/writer/json.rs, crates/core/src/writer/record_batch.rs, crates/core/src/writer/stats.rs
When switching to using `BTreeMap` for representing partition values, I introduced a bug, thinking `BTreeMap` would preserve insertion order. While it is ordered, it is ordered based on keys.
This PR moves to using `IndexMap`, which actually preserves insertion order.
=> fix: replace BTreeMap with IndexMap to preserve insertion order

crates/core/src/protocol/checkpoints.rs, crates/core/src/protocol/parquet_read/mod.rs
From the protocol, createdTime is of type Option[Long] and:
The time when this metadata action is created, in milliseconds since the Unix epoch
Not required, but this only shows up when checkpoints are created and then read back into on the table load
=> fix: allow checkpoints to contain metadata actions without a createdTime value

crates/core/src/operations/write.rs, crates/core/src/operations/writer.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/writer/json.rs, crates/core/src/writer/mod.rs, crates/core/src/writer/record_batch.rs
This commit introduces the `WriteMode` enum and the ability to specify writes which should enable [schema
evolution](https://delta.io/blog/2023-02-08-delta-lake-schema-evolution/).
The result of this is a new `metaData` action added to the transaction log with the write which reflects the updated schema
There are some caveats however such as all writes must include non-nullable columns.
Fixes #1386
Sponsored-by: Raft, LLC.
=> feat: introduce schema evolution on RecordBatchWriter

python/src/lib.rs
Some println's got slipped through recent refactors
=> fix: rm println in python lib

python/deltalake/writer.py, python/tests/test_writer.py
For some odd reason the pyarrow parquet writer will leave empty row groups in the parquet file when it hits the max_row limit that's passed. While grabbing the stats we were checking if all row_groups were having stats added to them but these empty row groups had no stats so it causes the whole file add action to get no stats recorded.
We now skip empty row groups while gathering the stats to prevent this.
In v0.15.2 we now also evaluate files with no stats mentioned as null @roeap @rtyler  not sure if this is entirely correct as well
- closes https://github.com/delta-io/delta-rs/issues/2169
=> fix(python): skip empty row groups during stats gathering

python/deltalake/writer.py
Add comment to explain why assert has failed for partition_by columns and show state
closes #2177
=> feat: add comment to explain why assert has failed and show state

crates/core/src/table/builder.rs
The `DeltaTableBuilder` class has a method `from_uri` that panics when receiving an invalid uri, and it has the method `from_valid_uri` that returns a result. Unfortunately, the method can also panic. I removed the panic.
=> fix: removed panic in  method

crates/core/src/kernel/arrow/mod.rs
This changes the field names inside map types to be `key` and `value` instead of `keys` and `values`. This matches the parquet spec for encoding map columns: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps 
I found this while trying to load a checkpoint from a table where it was failing with spurious errors. Pyarrow is tolerant of this to a degree but other readers like parquet4s (used in e.g delta standalone) took issue with it.
=> fix: correct map field names

crates/core/src/operations/optimize.rs, crates/core/src/schema/partitions.rs, crates/core/tests/command_optimize.rs
Implement string representation for PartitionFilter and add it to optimize command commit info for a TODO.
Following json representations of CommitInfo from delta scala project were found:
```
"operationParameters":{"predicate":"[\"(id#480 < 50)\"]"}
"operationParameters":{"predicate":"[\"(col1#1939 = 2)\"]"}
"operationParameters":{"predicate":"[\"`col2` LIKE 'data-2-%'\"]"}
"operationParameters":{"predicate":"[\"(id#378L < 2)\"]"}
"operationParameters":{
"predicate":"[\"(spark_catalog.delta.`/table-uuid`.id IN (0, 180, 308, 225, 756, 1007, 1503))\"]"
}
```
So I think representing predicate as a list of filters in string representation would be logical, for example:
```
// single PartitionFilter
"operationParameters":{"predicate":"[\"date = '2022-05-22'\"]"}
// two filters …
```
=> feat: implement string representation for PartitionFilter

docs/delta-lake-best-practices.md, mkdocs.yml
Adds a docs page on the Delta Lake best practices.
This is a first pass and I think this should evolve over time.
This is some of the most important content for our users IMO.
=> docs: add delta lake best practices

crates/core/src/kernel/models/schema.rs, crates/core/src/operations/convert_to_delta.rs
Correct hashing of StructField and add tests.
- Current:  Two StructFields with the same name but different `data_type` or different `nullable` are considered to hash equivalently.
- To be: `name`, `data_type` and `nullability` should match for a field to be considered equivalent.
closes #2045
=> fix: add data_type and nullable to StructField hash (#2045)

crates/core/src/kernel/snapshot/log_segment.rs
=> fix: `is_commit_file` should only catch commit jsons

README.md
Rust `deltalake` version 0.17 no longer has `.get_files()`.
Newer pandas versions raise a ValueError when comparing dataframes using `==`.
While updating our code to 0.17, I noticed that `.get_files()` was no longer present on `DeltaTable`. The README here and on crates.io still refers to it.
=> docs: update README code samples for newer versions

python/deltalake/writer.py, python/tests/test_writer.py
Supersedes this PR: https://github.com/delta-io/delta-rs/pull/1854, @PierreDubrulle thanks for pointing it out
- closes https://github.com/delta-io/delta-rs/issues/1853
=> fix(python): sort before schema comparison

crates/aws/src/storage.rs
When merging supplied storage options with environment variables, we need to canonicalize the items in the storage options first. This is because for some keys there is multiple valid definitions (`AWS_ENDPOINT_URL`, `AWS_ENDPOINT`) and also casing (`AWS_ACCESS_KEY_ID`, `aws_access_key_id`). It seems like the 'more canonical' lowercase versions win, which can cause surprise if you have one set of access keys in your environment and one in your storage options. This is exacerbated as the `S3StorageOptions` construction also _sets_ envrionment variables, and it always does so into the canonical lowercase versions. I found this when opening two buckets with different credentials, and the credentials for the first were being used to open the second.
=> fix: canonicalize config keys

crates/core/src/operations/merge/mod.rs
`DataFrame::with_column` performs a linear operation in the number of columns to append on an existing column, checking that nothing collides. On top of this once the projection a normalization step (also linear in number of columns) is performed before returning the dataframe.
For a merge where we are performing a `when_matched_update_all` type operation on wide tables (100+ columns), this is in effect a `2*N^2` operation as we were adding the remapped case columns one at a time with `with_column` and then remapping it.
This PR uses `project` directly to construct the logical plan. We don't need any of the special checking for name clashes or windowing that `with_column` provides and we discard it immediately down to an unoptimized logical plan anyway, so this produces no change to …
=> perf: directly create projection instead of using DataFrame::with_column

.github/workflows/build.yml
These caches cause more problems than they're worth and cause runners to exhaust their disk space
=> chore: remove caches from github actions

CONTRIBUTING.md
**The current example rust tests do not work:**
```bash
$ cargo run --examples basic_operations
error: unexpected argument '--examples' found
tip: a similar argument exists: '--example'
Usage: cargo run --example [<NAME>] [args]...
For more information, try '--help'.
```
**This also does not work:**
```bash
$ cargo run --example basic_operations 
error: target `basic_operations` in package `deltalake` requires the features: `datafusion`
Consider enabling them by passing, e.g., `--features="datafusion"`
```
**This does work:**
```
$ cargo run --example basic_operations --features="datafusion"
Compiling deltalake-core v0.17.0 (/Users/gautham/src/delta-rs/crates/core)
...
...
```
Making a quick update to the docs so that the example works out of the box.
=> docs: fixing example in CONTRIBUTING.md

crates/core/src/operations/constraints.rs, crates/core/src/operations/drop_constraints.rs, crates/core/src/operations/mod.rs, crates/core/src/protocol/mod.rs, python/Cargo.toml, python/deltalake/_internal.pyi, python/deltalake/table.py, python/src/lib.rs, python/tests/test_alter.py
Adds `drop constraint` as an operation, and also exposed it to python under the alter namespace 😄 
- closes https://github.com/delta-io/delta-rs/issues/2070
=> feat(rust, python): add `drop constraint` operation

crates/core/src/operations/transaction/mod.rs, crates/core/src/storage/mod.rs, crates/core/src/storage/retry_ext.rs, crates/core/src/writer/json.rs, crates/core/src/writer/record_batch.rs
Read-only operations are retried by [`ObjectStore`] internally. However, PUT/DELETE operations
are not retried even thought they are technically idempotent. [`ObjectStore`] does not retry
those operations because having preconditions may produce different results for the same
request. PUT/DELETE operations without preconditions are idempotent and can be retried.
Unfortunately, [`ObjectStore`]'s retry mechanism only works on HTTP request level, thus there
is no way to distinguish whether a request has preconditions or not.
This PR provides additional methods for working with [`ObjectStore`] that automatically retry
unconditional operations when they fail, and use these methods in writer to retry on temporary
network errors.
- https://datatracker.ietf.org/doc/html/rfc7231#section-4.2.2
- …
=> fix(writer): retry storage.put on temporary network errors

docs/src/python/check_constraints.py, python/deltalake/table.py, python/deltalake/writer.py, python/docs/source/_ext/edit_on_github.py, python/pyproject.toml, python/tests/pyspark_integration/test_write_to_pyspark.py, python/tests/pyspark_integration/test_writer_readable.py
As requested by @ion-elgreco in #2229 , we should fix the formatter versions
=> fix: fix ruff and mypy version and do formatting

Cargo.toml
See https://github.com/delta-io/delta-rs/pull/2229#issuecomment-1978658659 
This fixes object_store to use 0.9.0 for now,
=> fix: object_store 0.9.0 since 0.9.1 causes CI failure

python/Cargo.toml
Bumping to 0.16 since we got timestampNtz and schema Evolution now.
=> chore: bump to 0.16

crates/core/src/table/config.rs
=> fix(rust): typo deletionvectors

crates/core/src/table/config.rs
Spark-scala uses the plural form to construct intervals, so "day**s**" instead of "day". To keep backwards compatibility, I kept the singular form as well.
- closes https://github.com/delta-io/delta-rs/issues/2180
- closes: https://github.com/delta-io/delta-rs/issues/2072
=> fix(rust): make interval parsing compatible with plural form

README.md
Cloudflare R2 doesn't require the use of an external lock when using conditional operation headers like so:
```rust
let s3 = AmazonS3Builder::from_env()
.with_url(url)
.with_region("auto")
.with_access_key_id(&config.s3_access_key_id)
.with_secret_access_key(&config.s3_secret_access_key)
.with_endpoint(&config.s3_endpoint)
// Allows using S3-API without an external locking provider since Cloudflare R2
// provides atomic Put and Copy.
.with_config(
AmazonS3ConfigKey::CopyIfNotExists,
"header: cf-copy-destination-if-none-match: *".to_string(),
)
.build()
```
- https://developers.cloudflare.com/r2/api/s3/extensions/#putobject-1
- https://github.com/apache/arrow-rs/blob/c6ba0f764a9142b74c9070db269de04d2701d112/object_store/src/aws/precondition.rs#L29-L42
=> docs: update comment about r2 requiring locks

crates/core/src/operations/delete.rs
Update timing fields using the suffix `_ms` to be in milliseconds.
Doing a quick grep through the repo I only found a few instances of this in the delete.rs file.
Closes #2256
=> fix(#2256): use consistent units of time

crates/aws/Cargo.toml, crates/aws/src/errors.rs, crates/aws/src/lib.rs, crates/aws/src/logstore.rs, crates/aws/src/native.rs, crates/aws/src/storage.rs, crates/aws/tests/integration_s3_dynamodb.rs
This PR removes rusoto from the AWS crate while adding a dependency to the Rust AWS SDK
#2210
=> chore!: replace rusoto with AWS SDK

python/src/lib.rs
Release GIL in deltalake.write_deltalake by wrapping it in py.allow_threads
- closes #2234
=> feat(python): release GIL in the write_deltalake function

python/deltalake/table.py, python/tests/conftest.py, python/tests/test_merge.py
- Always encapsulates column names in backticks to in the insert_all and update_all calls. 
- Added note that users need to add backticks for special column names
- Removed bigint cast, this was temporarily needed while we were still relying on a physical plan
- closes https://github.com/delta-io/delta-rs/issues/2230
- closes https://github.com/delta-io/delta-rs/issues/2167
=> fix(python): always encapsulate column names in backticks in _all functions

docs/integrations/delta-lake-polars.md
Correct the spelling of `without`.
N/A
N/A
=> docs: fix typo in delta-lake-polars.md

python/deltalake/writer.py, python/tests/test_writer.py
- Replaces assert and AssertionError with built-in exceptions
- Amended tests to reference new exception types
- Following conventions in file of using built-in exceptions rather than custom exceptions
Closes https://github.com/delta-io/delta-rs/issues/2242
=> fix: replace assert and AssertionError with appropriate exceptions

crates/core/src/operations/transaction/state.rs, python/tests/test_delete.py, python/tests/test_update.py, python/tests/test_writer.py
Such a small change, but fixes many issues where parquets were written with arrow where the source data was in large dtype  format.
By default the parquet::ParquetReader decodes the arrow metadata which in return may give you large dtypes. This would cause issues during DataFusion parquet scan with a filter since the filter wouldn't coerce to the large dtypes. Simply disabling the arrow metadata decoding gives us the parquet schema converted to an arrow schema without large types 👯‍♂️ 
- closes https://github.com/delta-io/delta-rs/issues/1470
=> fix(python, rust): prevent table scan returning large arrow dtypes

crates/deltalake/Cargo.toml, crates/deltalake/src/lib.rs, crates/mount/Cargo.toml, crates/mount/src/config.rs, crates/mount/src/error.rs, crates/mount/src/file.rs, crates/mount/src/lib.rs, crates/mount/tests/context.rs, crates/mount/tests/integration.rs, python/Cargo.toml, python/src/lib.rs, python/tests/test_writer.py
compatible to write to local file systems that do not support hard link.
When we write to the local file system, sometimes hard link is not supported, such as blobfuse, goofys, s3fs, so deal with it with compatibility.
It is important to note that:
There is another problem with blobfuse, that is, when it comes to rename, it will report errors. Because rename did not release the file handle before.
See here for details: https://github.com/delta-io/delta-rs/issues/1765
Arrow-rs is required to cooperate with the modification, for example: https://github.com/GlareDB/arrow-rs/pull/2/files
Because object_store has been upgraded to 0.8, there are a lot of breaking change, so I haven't changed this one for the time being. Will fix it after upgrading to 0.8 …
=> fix: compatible to write to local file systems that do not support hard link

crates/core/src/kernel/arrow/mod.rs, crates/core/src/protocol/checkpoints.rs, python/tests/test_checkpoint.py
The CheckPoint schema simply didn't contain the features as fields in the Protocol struct, and we weren't propagating them as well within the checkpoint function.
- closes https://github.com/delta-io/delta-rs/issues/2288
=> fix(rust): features not maintained in protocol after checkpoint

crates/core/src/table/mod.rs
Typo in the Rust docs for `get_files_count`
=> docs: fix typo

crates/core/src/operations/merge/mod.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/protocol/mod.rs, crates/core/tests/command_merge.rs
This merge request will change the commitInfo.operationParameters.predicate of the merge operation. This is required to allow conflict checking on concurrent commits. Before, the predicate was just the simple merge predicate like `source.eventId = target.eventId`, but the conflict checker doesn't know these aliases and doesn't have access to the source df. 
So I now use the early_filter, which is also used before to filter a subset of the target table. Basically, the early_filter only contains static filters and partition filters that are converted to fixed values based on the source data.  The early_filter can be None if no column/partition pre-filtering is possible, or if the merge contains a not_match_source operation. (See the generalize_filter function in the file).
The commitInfo …
=> fix: merge predicate for concurrent writes

docs/src/rust/operations.rs
Fix for Rust example in ['Overwriting part of the table data using a predicate' part of the delta-rs webpage](https://delta-io.github.io/delta-rs/usage/writing/#overwriting-part-of-the-table-data-using-a-predicate)
The current example uses a keyword, `import` that does not exist in Rust. It also doesn't wrap the `Schema` in an `Arc`.
=> docs: make replaceWhere example compile

crates/core/src/operations/transaction/conflict_checker.rs
Not sure when this regressed but the lack of datafusion broke the core build
```
error[E0432]: unresolved import `crate::delta_datafusion`
--> crates/core/src/operations/transaction/conflict_checker.rs:5:12
|
5 | use crate::delta_datafusion::DataFusionMixins;
|            ^^^^^^^^^^^^^^^^ could not find `delta_datafusion` in the crate root
error[E0700]: hidden type for `impl Iterator<Item = actions::Add>` captures lifetime that does not appear in bounds
--> crates/core/src/operations/transaction/conflict_checker.rs:196:9
|
109 | impl<'a> TransactionInfo<'a> {
|      -- hidden type `impl Iterator<Item = actions::Add> + 'a` captures the lifetime `'a` as defined here
...
195 |     pub fn read_files(&self) -> Result<impl Iterator<Item = Add>, CommitConflictError> {
| …
```
=> fix: clean up some non-datafusion builds

crates/core/src/protocol/checkpoints.rs, python/Cargo.toml, python/tests/pyspark_integration/test_writer_readable.py, python/tests/test_checkpoint.py
Misread the protocol before but the columns readerFeatures or writerFeatures should be null and not empty list when you are below v3 or v7.
Also will immediately push a patch release since checkpoints with python v0.16.1 breaks reader compatibility with Spark
=> fix: checkpoint features format below v3,7

crates/core/src/kernel/arrow/mod.rs, crates/core/src/operations/cast.rs, crates/core/src/operations/write.rs, crates/core/src/writer/record_batch.rs, python/tests/test_writer.py
This fixes schema merge for large arrow types in combination with dictionary types. Basically we just allow merging any arrow data type that is the same delta type
Fixes #2298
=> fix: schema evolution not coercing with large arrow types

Cargo.toml, python/tests/test_fs.py
=> chore: object store 0.9.1

crates/core/src/operations/writer.rs, python/Cargo.toml
I ran this version in a pipeline at work and now it didn't give this anymore:
`OSError: Generic MicrosoftAzure error: Error after 0 retries in 30.000943594s, max_retries:10, retry_timeout:180s, source:error sending request for url (https://<redacted>.blob.core.windows.net/dev-preprocessed/<redacted>/product_line_code=<redacted>/event_year_month_clt=202209/part-00001-874ec394-72d0-44fb-8cbb-2b7b73b41ede-c000.snappy.parquet): operation timed out`
=> fix: try to fix timeouts

python/deltalake/table.py
Adds example from docs into docstring
=> docs: add example in to_pyarrow_dataset

crates/core/src/kernel/arrow/mod.rs, crates/core/src/kernel/expressions/scalars.rs, crates/core/src/kernel/models/schema.rs, python/deltalake/_internal.pyi, python/src/schema.rs, python/tests/test_schema.py, python/tests/test_writer.py
We weren't adhering to the protocol here, so we were permitting  larger than precision/scale 38 to end up in the metadata.
- fixes https://github.com/delta-io/delta-rs/issues/2331
=> fix(rust): adhere to protocol for Decimal

crates/core/src/operations/write.rs, python/tests/test_writer.py
The `can_cast_types` is a bit to flexible with decimals, since we define the decimal type in the table metadata. So if the source data contains a decimal that is larger than the decimal in the table metadata, we should throw an error. Before we would let our writer just write because `can_cast_types `does not check precision and scale for casting so Decimal(30.1) could  be  written after the table was  set to only  allow precision=1,  scale=1. 
After the write, the json parser would not be able to read the table anymore since it throws a decimal overflow, and rightfully so. This fix will prevent tables to get in these invalid states.
- fixes https://github.com/delta-io/delta-rs/issues/2275
=> fix(rust): raise schema mismatch when decimal is not subset

crates/benchmarks/src/bin/merge.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/merge/mod.rs
Delta scan will push filter to the parquet scan when possible. Added a new configuration for the special case where operations need to operate on an entire file  but still want to perform pruning.
- fixes #2362
=> fix: add config for parquet pushdown on delta scan

crates/core/src/protocol/checkpoints.rs
Noticed that we didn't set any compression, this should bring down the file size a bit for users that have large checkpoints
=> fix: add snappy compression on checkpoint files

Cargo.toml, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/expressions/scalars.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/kernel/snapshot/serde.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/storage/utils.rs, crates/core/src/writer/stats.rs, crates/core/tests/command_restore.rs
I was having some dependency conflicts with the `chrono = "=0.4.34` dependency. This bumps chrono to `>0.4.34`, so it should be a bit more relaxed when resolving dependencies.
=> chore: bump chrono

crates/core/src/operations/writer.rs
Reverts https://github.com/delta-io/delta-rs/pull/2318 by removing `flush` after writing each batch since it was causing smaller than expected row groups to be written during compaction.
- closes #2386
=> fix(rust): remove flush after writing every batch

docs/usage/writing/writing-to-s3-with-locking-provider.md
This documents the required AWS permissions on S3 and DynamoDB to interact with deltalakes.
- mentions #1091
=> docs: document required aws permissions

crates/aws/src/credentials.rs, crates/aws/src/lib.rs, crates/aws/src/storage.rs
Rusoto and the AWS SDK have different behavior when interacting with the ec2 metadata service. Despite the lower default timeout in the AWS SDK, it still takes longer to abandon the IMDS credential provider. This PR add a setting `AWS_EC2_METADATA_DISABLED` to disable the provider. It can be provided as an environment variable or isolated to the s3 storage settings. Additionally, I added `AWS_EC2_METADATA_TIMEOUT` to represent the timeout for the imds credential provider in milliseconds with a default value of 100.
This does not completely eliminate the regression, but it provides opt-in/opt-out options to mitigate the issues in exceptional cases.
- closes #2377 
[Rust SDK Environment Variables](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/environment-variables.html)
=> feat: added configuration variables to handle EC2 metadata service

README.md, docs/integrations/delta-lake-daft.md, mkdocs.yml
This adds an integration page for using Delta Lake with Daft.
=> docs: add Daft integration

crates/core/src/delta_datafusion/expr.rs, crates/core/src/protocol/checkpoints.rs, python/tests/test_checkpoint.py
Our timestamp deserialization format didn't include the %6f to decode this value: 1970-01-01 00:00:00.123456. Additionally during timestampNtz I didn't add deserialization of that primitive type :) 
- fixes https://github.com/delta-io/delta-rs/issues/2380
- fixes https://github.com/delta-io/delta-rs/issues/2381
=> fix(rust): timestamp deserialization format, missing type

crates/core/src/kernel/arrow/json.rs, crates/core/src/kernel/snapshot/replay.rs
- `stats_parsed` is a StructArray instead of StringArray
-  Parse `Add` action's `stats` to `stats_parsed` would panic due to the use of `slice.array_data()`.
closes #2312 
https://docs.rs/arrow/51.0.0/arrow/array/struct.GenericByteArray.html#method.value_data
=> fix(rust): stats_parsed has different number of records with stats

crates/core/src/delta_datafusion/mod.rs
This implements repartitioned from the ExecutionPlan trait of DeltaScan. Currently, Delta tables without partitions are read with all its files in a single file group of the underlying `ParquetExec`. This seems to mean that Delta tables without partitions are read without concurrency. With repartitioned we can repartition the DeltaScan to get concurrency when reading.
=> feat: implement repartitioned for DeltaScan

python/deltalake/table.py
Upon attempting to retrieve the version with a datetime object, the `load_as_version` method throws a `ValueError: Failed to parse datetime string: premature end of input`.
Datetime objects without a specified timezone will be treated as UTC datetimes.
=> fix(python): load_as_version with datetime object with no timezone specified

crates/core/src/operations/create.rs, python/tests/test_create.py
The overwrite mode never added the remove actions, which causes your table to get in an invalid state.
=> fix(python,rust): missing remove actions during `create_or_replace`

crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/merge/mod.rs, python/tests/test_merge.py
@Blajda I don't think `from_qualified_name_ignore_case` was needed here since the delta_fields don't have relation information, they are just the column names. 
`from_qualified_name_ignore_case` will try to parse `__delta_rs_c_y--1` and results into  `__delta_rs_c_y`, while `from_name `just keeps the column name as-is, which is preferred. 
- closes https://github.com/delta-io/delta-rs/issues/2438
=> fix(python, rust): use from_name during column projection creation

python/Cargo.toml, python/deltalake/_internal.pyi, python/deltalake/writer.py, python/src/lib.rs
Instead of reusing the table state, it was being instantiated every time you call write with the rust engine.
- https://github.com/delta-io/delta-rs/discussions/2448
=> fix(python): reuse table state in write engine

crates/core/src/operations/constraints.rs, crates/core/src/operations/delete.rs, crates/core/src/operations/drop_constraints.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write.rs, crates/core/tests/command_merge.rs
We advance the state in the post commit now, so it's done in a single location as per suggestion from @Blajda here: https://github.com/delta-io/delta-rs/pull/2391#issuecomment-2041500757
This PR also supersedes this one: https://github.com/delta-io/delta-rs/pull/2280
- fixes #2279
- fixes #2262
=> feat(rust): advance state in post commit

crates/core/src/operations/transaction/mod.rs, crates/deltalake/Cargo.toml, crates/gcp/Cargo.toml, crates/gcp/src/lib.rs, crates/gcp/src/storage.rs
Fixes #2451 
This is probably not the best implementation but it at least let me test the outcome.
Here's my test script:
```python
import os
from uuid import uuid4
os.environ['RUST_LOG'] = 'INFO'
from time import time
from concurrent.futures import ProcessPoolExecutor
import polars as pl
from deltalake import DeltaTable, write_deltalake
def worker(uri: str, df: pl.DataFrame) -> None:
table = DeltaTable(uri, log_buffer_size=1024 * 1024)
table.update_incremental()
print('writing in a loop')
while True:
try:
start = time()
write_deltalake(table, df.to_arrow(), engine='rust', mode='append')
print('Time taken:', time() - start)
except Exception as e:
print('Python error:', e)
continue
if __name__ == '__main__':    
df = pl.DataFrame({
'a': [1, 2, 3],
'b': [4, 5, 6],
})
uri = …
```
=> fix(rust): handle 429 from GCS

crates/aws/Cargo.toml, crates/aws/src/errors.rs, crates/aws/src/lib.rs, crates/aws/src/logstore.rs, crates/aws/src/storage.rs, crates/aws/tests/integration_s3_dynamodb.rs, crates/core/src/logstore/default_logstore.rs, crates/core/src/logstore/mod.rs, crates/core/src/operations/restore.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/storage/retry_ext.rs
This PR ensures when using `S3DynamoDBLogStore`, temp commit files are only deleted when the DynamoDB log entry is deleted.
Add `abort_commit_entry(version, tmp_commit)` to `LogStore`
- By default, this just deletes the `tmp_commit` file
- For `S3DynamoDBLogStore`, it first deletes the DynamoDB entry. Then, it only deletes `tmp_commit` if the entry is deleted successfully
This fixes a rare bug when using DynamoDB as the locking provider. Consider the following events:
1. `S3DynamoDbLogStore.write_commit_entry` succeeds at creating a DynamoDB entry, but fails during `repair_entry`
2. The error handling deletes the `tmp_commit` file
3. The next time `repair_entry` is called on this entry, it will lead to `ObjectStoreError::NotFound` since the temp commit file was deleted
4. We infer the …
=> fix(rust): implement abort commit for S3DynamoDBLogStore

python/deltalake/table.py, python/tests/test_writer.py
Otherwise there is no way to union this with another dataset.
=> feat(python): add  parameter to DeltaTable.to_pyarrow_dataset()

crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/replay.rs, python/tests/test_writer.py
In some edge cases where we schema evolve, it would parse the stats with the old schema result in these kind of errors:
`Exception: Json error: whilst decoding field 'minValues': whilst decoding field 'foo': failed to parse 1000000000000 as Int8`
```python
import polars as pl
from deltalake import write_deltalake
pl.DataFrame({
"foo": [1]
}, schema={"foo": pl.Int8}).write_delta("TEST_TABLE_BUG")
write_deltalake("TEST_TABLE_BUG", data = pl.DataFrame({
"foo": [1000000000000]
}, schema={"foo": pl.Int64}).to_arrow(), mode='overwrite', overwrite_schema=True,engine='rust')
```
Instead of taking the old schema, I added an optional schema to be passed in the logMapper
=> fix(python, rust): use new schema for stats parsing instead of old

crates/mount/src/file.rs
In the case of /tmp existing on tmpfs with musl, the prior version of this would fail with a cross-device link error before bubbling up a not found error
=> fix: check to see if the file exists before attempting to rename

crates/core/src/writer/record_batch.rs
…partition columns
This causes attempts to write to a partitioned table with MergeSchema to fail, as it's not supported by the code.
I took a look at trying to make it work, but there isn't a quick fix. This is because we need a merged schema definition _before_ we start trying to partition by the partition columns, otherwise the newly added columns get dropped. The schema reported for matching in `self.arrow_schema_ref` also needs to contain the partition columns, and ordering matters in comparing schemas so we need to know the right place to insert them. I think for situtations where `flush()` has already been called, we also need a function to return a `Option<MetaData>` action to be applied to manual commits. Finally, re-using a writer in the presence of schema evolution is dangerous, …
=> fix: return unsupported error for merging schemas in the presence of partition columns

python/Cargo.toml, python/deltalake/_internal.pyi, python/deltalake/fs.py, python/deltalake/table.py, python/deltalake/writer.py, python/src/filesystem.rs, python/tests/test_fs.py
Reuse the state so we save time instead of reconstructing and verifying the state.
=> fix(python): reuse state in `to_pyarrow_dataset`

crates/aws/src/storage.rs
The object store changes the keys used for creating the s3 options, while the log store does not. The difference between the two, and their usage together was causing some weird fallback behavior in the AWS SDK that invoked the IMDS service despite explicitly disabling it in multiple places. This fix handles the potentially different casing along with passing the options unmolested. It should stop any future, unwanted, IMDS behavior
- closes #2460
=> fix(rust, python): fixed differences in storage options between log and object stores

crates/core/src/operations/convert_to_delta.rs, crates/core/src/operations/mod.rs, crates/core/src/operations/transaction/conflict_checker.rs, crates/core/src/operations/transaction/protocol.rs, crates/core/src/operations/write.rs, crates/core/src/writer/record_batch.rs, crates/core/src/writer/stats.rs, python/src/lib.rs
The recent convert_to_delta changes imported a symbol from a module that is only compiled in with the datafusion feature, oops!
=> chore: tidying up builds without datafusion feature and clippy

crates/core/src/kernel/models/schema.rs
`field_with_name` on schema type does not handle nested field names. This comes up when setting the data skipping stats column property. For example when I set this value to `parent.child`, the stats handling code in table load/scan throws an error that it cannot find a field named `parent.child`.
Area where we would see the error: https://github.com/delta-io/delta-rs/blob/fae1406e91c7ac5188b64827eba11dbbb2acce59/crates/core/src/kernel/snapshot/mod.rs#L296
=> fix: enable field_with_name to support nested fields with '.' delimiter

python/src/lib.rs
=> fix(python): release GIL on most operations

Cargo.toml
Our min required rust version does not match the features we are using. Specifically, we are using `impl Trait` as a return type in a trait, which is only available since [`1.75`](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html).
https://github.com/delta-io/delta-rs/blob/8eb2b8b611ce4f8cdfd24d3ae5ff52332628188f/crates/core/src/delta_datafusion/mod.rs#L238-L241
This was raised in a discussion #2514.
=> fix: msrv in workspace

crates/core/src/operations/writer.rs
I would like to use PartitionWriter within my own crate. Would you mind making this public so I don't have to vendor it and all of the associated code?
=> feat(rust): make PartitionWriter public

docs/integrations/delta-lake-daft.md
This PR improves the Daft integration docs to better highlight key Delta features.
=> docs: improve daft integration docs

docs/usage/installation.md
This PR updates the conda install .yml file to pull deltalake from conda-forge instead of pip. Mixing pip and conda is not recommended when it can be avoided.
=> docs: pull delta from conda not pip

crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/visitors.rs, crates/core/src/operations/cast.rs, crates/core/src/operations/optimize.rs, crates/core/src/operations/transaction/application.rs, crates/core/src/operations/writer.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/table/state_arrow.rs, crates/core/src/writer/json.rs, crates/core/src/writer/record_batch.rs, crates/core/tests/command_merge.rs, crates/core/tests/integration_datafusion.rs
This PR fixes many clippy warnings in the Rust code.
=> fix: clippy warnings

crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/catalog-glue/Cargo.toml, crates/core/Cargo.toml, crates/deltalake/Cargo.toml, crates/gcp/Cargo.toml, crates/mount/Cargo.toml, crates/test/Cargo.toml, python/Cargo.toml, python/deltalake/writer.py
Uses of mode='append' and overwrite_schema=True lead to inconsistent behavior between Rust and PyArrow engines for write_deltalake. In the PyArrow case the parameter is quietly omitted so users may experience unexpected behavior since schemas will not actually be overridden.
Users of this parameter set most likely want schema_mode='merge' which would allow for schema evolution on appends to a Delta Table
Fixes #2553
=> fix: remove deprecated overwrite_schema configuration which has incorrect behavior

crates/deltalake/Cargo.toml, crates/deltalake/examples/basic_operations.rs, crates/deltalake/examples/load_table.rs, crates/deltalake/examples/read_delta_table.rs, crates/deltalake/examples/recordbatch-writer.rs
The data types and delta table paths in the examples were no longer correct.
There is no "arrow" feature anymore.
- closes #2552.
=> fix: update deltalake crate examples for crate layout and TimestampNtz

crates/core/src/operations/create.rs, python/deltalake/_internal.pyi, python/deltalake/table.py, python/src/lib.rs
This PR adds a `raise_if_key_not_exists` flag to the `CreateBuilder` which we propagate (currently always `true`), such that users can choose not to fail if the configuration contains a key that is not a valid DeltaConfigKey. Also expose this in the Python binding.
Closes #2564.
@ion-elgreco
=> fix: add raise_if_key_not_exists to CreateBuilder

docs/usage/deleting-rows-from-delta-lake-table.md
This PR adds more general context about using `dt.delete()` and a link to the API docs
=> docs: dt.delete add context + api docs link

crates/core/src/operations/create.rs, python/src/lib.rs
I forgot to change the name of the builder method!
Follow up from #2565.
=> fix: consistently use raise_if_key_not_exists in CreateBuilder

crates/core/src/operations/cast.rs
The current implementation of cast only works for structs nested in structs.  This PR adds supports for structs contained in other types (lists and maps).  This PR also prevents cast from adding nullable column if the field is not nullable, instead it will throw an error.
Note: This is only a partial solution which would let you merge schema with nested missing columns, it does not allow delta-rs to read the merged schema (though Spark can).  To read the merged schema will require another change where delta-rs defines its own datafusion parquet schemaAdapter.
=> fix: cast support fields nested in lists and maps

python/deltalake/table.py
This [documentation](https://delta-io.github.io/delta-rs/api/delta_table/#deltalake.DeltaTable.schema) describes the usage of `files_by_partition` but that API doesn't seem to be surfaced from the underlying rust implementation
=> chore: expose `files_by_partition` to public api

.github/workflows/build.yml, .github/workflows/python_release.yml
Seems like many folks use Mac : ), so I hope this fixes the issue as the only info I could find was that compiling it on different OS could result in this
Related issue https://github.com/delta-io/delta-rs/issues/2577
=> chore: bump macOS runners, maybe resolve import error

python/.gitignore, python/Cargo.toml, python/src/filesystem.rs, python/src/lib.rs, python/src/schema.rs
This migrates the Python package to use the new pyo3 bounds-based API, which allows more control over memory management on the library side and theoretical performance improvements (I benchmarked, and didn't notice anything substantial). The old API will be removed in 0.22.
=> chore: migrate to pyo3 Bounds API

python/pyproject.toml, python/tests/conftest.py, python/tests/test_fs.py
Reintroduce integration tests using Azurite and SAS tokens.
These tests were skipped believing that the mistake was due to the upgrade of version in `object-store>=0.9.1". Actually, what `object-store` started doing from that version on, is really using the SAS token for the first time. For more details, see:
- https://github.com/apache/arrow-rs/issues/5475#issuecomment-2084748858
I changed the command to create the SAS token using the `azure-storage-blob` library (adding it to the dev deps), rather than the azure CLI, and removed the pytest markers to skip the tests.
@ion-elgreco pinging you as promised, sorry if this took more time than expected!
=> test: reintroduce azurite SAS integration tests

python/deltalake/table.py, python/stubs/pyarrow/parquet.pyi, python/tests/test_table_read.py
Allow `pyarrow.dataset.Expression` in `filters` kwarg of `deltalake.DeltaTable.to_pyarrow_table` and `deltalake.DeltaTable.to_pandas` methods, and remove code dupllication in favor of the pyarrow implementation.
- closes #2597
=> feat(#2597): allow pyarrow.dataset.Expression in filters kwarg

python/src/filesystem.rs, python/src/schema.rs, python/src/utils.rs, python/tests/test_fs.py
Object stores expected fixed lengths for all multipart upload parts right up until the last part. The original logic just flushed when it exceeded the threshold. Now, it flushes when the threshold is met exclusively with the same fixed buffer, unless we're completing the transaction, in which case the last piece is allowed to be smaller.
Bumps the constant to reflect that the minimum expected size by most object stores is 5MiB. Also adds a UserWarning if a constant is specified to be less. 
Also releases the GIL in more places by moving the flushing logic to a free function. 
Closes #2605 
See: [MultipartUpload](https://docs.rs/object_store/latest/object_store/trait.MultipartUpload.html) docs
=> fix(python): constrain multipart upload size to fixed length

crates/core/Cargo.toml, crates/core/src/delta_datafusion/mod.rs, crates/deltalake/Cargo.toml
=> chore: implement regression test for push down panic

crates/core/src/operations/write.rs, python/tests/test_writer.py
fixed merge schema not working when overwrite is called 
closes #2567
=> fix(rust, python): fix merge schema with overwrite

python/deltalake/writer.py, python/tests/test_writer.py
added large_dtype to  schema convert
closes  #2374
=> fix(python): fixed large_dtype to schema convert

crates/core/src/kernel/arrow/mod.rs, python/tests/test_checkpoint.py
avoid adding maxvalue and minvalue when there is no value in max_min_vec 
closes #2622
=> fix(rust, python): fix writing empty structs when creating checkpoint

.github/workflows/build.yml
These actions are dramatically slowing doiwn the PR feedback loop since runners are not being placed by GitHub it seems
=> chore: remove macos builders from pull request flow

crates/core/src/delta_datafusion/mod.rs
The DeltaScanBuilder used by DeltaTable's TableProvider impl does not specify DeltaScanConfig. The builder uses Default for DeltaScanConfig and thus enable_parquet_pushdown is disabled.
This change makes it so DeltaScanConfig is an Option on the scan builder. If unset during build a default value will be created using the DeltaScanConfigBuilder rather than DeltaScanConfig::Default. The former has enable_parquet_pushdown defaulted to true. I considered changing the latter but it is used in a couple other places where I was not sure of the impact.
This is a rebase and closes the outstanding :boom: pull request from @alexwilcoxson-rel 
closes #2618
=> fix: enable parquet pushdown for DeltaScan via TableProvider impl for DeltaTable  (rebase)

.github/workflows/build.yml
=> chore: missed one macos runner reference in actions

python/deltalake/table.py, python/tests/test_merge.py
```
E       _internal.DeltaError: Generic DeltaTable error: type_coercion
E       caused by
E       Error during planning: Failed to coerce then ([Struct([Field { name: "city", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "state", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "street", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), Struct([Field { name: "city", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "state", data_type: LargeUtf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "street", data_type: LargeUtf8, nullable: true, dict_id: …
```
=> chore: add a reproduction case for merge failures with struct<string>

crates/core/src/kernel/snapshot/log_segment.rs
=> feat(rust): fix size_in_bytes in last_checkpoint_ to i64

crates/core/src/delta_datafusion/mod.rs
We need stable order between logical and physical schemas, but the order of  partitioning columns is not always the same in the json schema and the array. This is visible only when you have more than one partitioning column.
This can surface in different ways:
- select a partitioning column and get the values from the other
- filter by a  partitioning column and get the wrong results (#2494)
- closes #2494
=> fix(rust): inconsistent order of partitioning columns (#2494)

python/Makefile, python/pyproject.toml, python/tests/test_file_system_handler.py
This PR bumps `ruff` to the [latest version](https://github.com/astral-sh/ruff/releases). After the update, running `make format` returns:
```
--- Rust format ---
--- Python format ---
cargo fmt
ruff check . --fix
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'isort' -> 'lint.isort'
tests/test_file_system_handler.py:37:12: E721 Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
|
35 |     arrow_info = arrow_fs.get_file_info(file_path)
36 | 
37 |     assert type(info) == type(arrow_info)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ E721
38 |     assert info.path == arrow_info.path
39 …
```
=> chore: bump ruff to 0.5.2

crates/core/src/kernel/arrow/mod.rs, python/tests/test_checkpoint.py
when creating min , max  schema make sure the nullable is true 
closes #2675
=> fix(rust,python): checkpoint with column nullable false

python/deltalake/writer.py
Adds support for the [Arrow PyCapsule interface](https://arrow.apache.org/docs/format/CDataInterface/PyCapsuleInterface.html). 
Since pyarrow is already a required dependency, this takes the minimal route of converting pycapsule interface objects into pyarrow objects. This requires pyarrow 15 or higher for the stream conversion (https://github.com/apache/arrow/issues/39217).
This doesn't modify the existing hard-coded support for pyarrow and pandas
- closes https://github.com/delta-io/delta-rs/issues/2376
=> feat(python): handle PyCapsule interface objects in write_deltalake

python/deltalake/table.py, python/deltalake/writer.py, python/pyproject.toml, python/tests/pyspark_integration/test_write_to_pyspark.py
This PR proposes to enable the [`RUF`](https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf) ruleset.
```
ruff check .
```
returned:
```
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'isort' -> 'lint.isort'
deltalake/table.py:52:26: RUF100 [*] Unused `noqa` directive (unused: `F811`)
deltalake/writer.py:63:26: RUF100 [*] Unused `noqa` directive (unused: `F811`)
tests/pyspark_integration/test_write_to_pyspark.py:109:37: RUF010 [*] Use explicit conversion flag
Found 3 errors.
[*] 3 fixable with the `--fix` option.
```
So these were simply fixed with `ruff check . --fix`. …
=> chore: enable `RUF` ruleset for `ruff`

.github/workflows/python_build.yml, python/pyproject.toml
Currently, `ruff` and `mypy` have their latest versions installed in the CI pipeline, while locally they are fixed to a specific version. This can cause issues, see https://github.com/delta-io/delta-rs/issues/2678.
This PR proposes to fix them to their specific version in the pipeline. The alternative I could think of was installing the virtual environment with `make develop`, but that takes between 4 and 5 minutes, which might be considered a bit too long to wait on linting results.
This PR will have conflicts with https://github.com/delta-io/delta-rs/pull/2674, so I'll need to rebase one of these PR's once the other is merged.
- closes [#106](https://github.com/delta-io/delta-rs/issues/2678)
=> chore: pin `ruff` and `mypy` versions in the `lint` stage in the CI pipeline

Cargo.toml
Bump delta kernel version, to support tables written with Uniform protocol enabled
closes #2578
=> fix: update delta kernel version

.github/actions/setup-env/action.yml, .github/workflows/docs.yml, .github/workflows/python_build.yml, .gitignore
The CI/CD pipeline currently contains some duplication; This PR proposes to simplify that a bit by creating a reusable action to set up Python and Rust.
=> chore: create separate action to setup python and rust in the cicd pipeline

python/Makefile, python/pyproject.toml
This PR proposes to add a `make test-cov` command to the `Makefile` to make it easier for contributors to check test coverage.
Output currently looks as follows:
```
[...]
tests/test_writerproperties.py::test_write_with_writerproperties PASSED    
---------- coverage: platform darwin, python 3.11.2-final-0 ----------
Name                        Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------
deltalake/__init__.py          11      0      0      0   100%
deltalake/_util.py             16      1     12      1    93%
deltalake/data_catalog.py       6      0      0      0   100%
deltalake/exceptions.py         5      0      0      0   100%
deltalake/fs.py                44     11      2      0    76%
deltalake/schema.py            60      0 …
```
=> chore: add test coverage command to `Makefile`

.gitignore, CONTRIBUTING.md
- Some small formatting changes in `CONTRIBUTING.md`
- add the line `python -m venv .venv` to make it easier to follow along. (e.g. I by default ran `python -m venv venv`, but `venv` is not in `.gitignore`)
- add `venv` to root `.gitignore`
=> chore: improve contributing.md

crates/core/src/delta_datafusion/find_files/mod.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/delta_datafusion/schema_adapter.rs, crates/core/src/operations/constraints.rs, crates/core/src/operations/delete.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write.rs, crates/core/tests/integration_datafusion.rs
By casting the read record batch to the delta schema datafusion can read tables where the underlying parquet files can be cast to the desired schema. Fixes:
- Errors querying data where some of the parquet files may not have columns that were added later because of schema migration.  This includes nested columns for structs that are in Maps, Lists, or children of other structs
- maps and lists written with different different element names
- timestamps of different units.
- Any other cast supported by arrow-cast.
This can be done now since data-fusion exposes a SchemaAdapter which can be overwritten.
We should note that this makes all times being read by delta-rs as having microsecond precision to match the Delta protocol.
- This makes solving #2478 and #2341 just a matter of adding code …
=> feat(rust,python): cast each parquet file to delta schema

python/deltalake/schema.py, python/tests/test_writer.py
part of #2686  fix writing empty arrow dataset with pyarrow engine 
part of #2686
=> fix(python): empty dataset fix for "pyarrow" engine

python/deltalake/_internal.pyi, python/deltalake/writer.py
The codebase contains the following code twice:
```
if sys.version_info >= (3, 8):
from typing import Literal
else:
from typing_extensions import Literal
```
I believe this can be removed, since [pyproject.toml](https://github.com/delta-io/delta-rs/blob/f432c4f8337c2b0d47958645684e5df336c61522/python/pyproject.toml#L10) specifies that the minimum Python version for the project is 3.8:
```toml
requires-python = ">=3.8"
```
=> chore: remove stale code for conditional import of `Literal`

.github/workflows/docs.yml, .github/workflows/python_build.yml, docs/Makefile, python/pyproject.toml
There are a few mentions of `black` in the project, but they seem inconsistent;
- In `.github/workflows/docs.yml`, we use black to validate the formatting of Python code in the docs. However, there is no set-up or instructions to format code locally. Of course this is not a big issue; fixing the formatting is trivial when this gives an error by installing `black`.
```yaml
- uses: psf/black@stable
with:
src: docs/src/python
``` 
- In `.github/workflows/python_build.yml` `black` seems to be installed but unused.
- There is some configuration for `black` in `python/pyproject.toml`, even though the formatter for the project is `ruff`.
This PR aims to solve these inconsistencies:
- Remove the references to `black` listed above.
- Use `ruff` as a formatter for the `docs` to be consistent with …
=> chore: remove references to black from the project

crates/core/src/kernel/models/actions.rs
Add support for reading `userMetadata` from `CommitInfo`. This field is set by Spark when certain writer or session options are set (please see https://docs.databricks.com/en/delta/custom-metadata.html or https://github.com/delta-io/delta/blob/573a57f62918d0cb8937ca8c9b4047f8d696cc9c/spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala#L80-L84).
=> feat: support userMetadata in CommitInfo

python/deltalake/writer.py
Te body of the `write_deltalake` function is quite long, and thus a bit difficult to read and understand. This PR proposes to reduce the complexity of the `write_deltalake` function a little bit, by extracting some logic to a separate function, and moving some function definitions to outside of the body.
I guess this is a bit opinionated, so if you think this does not add value, feel free to close the PR.
=> chore: refactor `write_deltalake` in `writer.py`

Cargo.toml, crates/core/Cargo.toml, crates/core/src/kernel/scalars.rs
First parse in path and then encode, otherwise Path::from does double encoding if you do it reversed.
- closes https://github.com/delta-io/delta-rs/issues/2634
=> fix(python, rust): use url encoder when encoding partition values

crates/core/src/operations/transaction/mod.rs, python/deltalake/__init__.py, python/deltalake/_internal.pyi, python/deltalake/table.py, python/deltalake/writer.py, python/src/lib.rs, python/tests/test_checkpoint.py
This adds the cleanup expired logs post-commit hook. Tables by default have `delta.enableExpiredLogCleanup = true`, and` delta.logRetentionDuration = interval 30 days`. So moving forward those logs will be automatically cleaned up.
If users set `delta.enableExpiredLogCleanup = false` during table creation, the log clean up will never be executed in the post-commit. When cleanup_expired_logs in the post-commit hook properties is passed, then that take precedence over the table config. 
Additionally to most operations you can now pass in Python the PostCommitHookProperties to control the post commit hook, only really needed for advanced use cases, where you want to disable creating checkpoints across the board or override the log clean up.
@Blajda this is a follow up PR of the hooks, will …
=> feat(python, rust): cleanup expired logs post-commit hook

crates/core/src/kernel/snapshot/log_segment.rs
This change applies projection pushdown when reading the checkpoint parquet file. Typically only a portion of the schema is read. Adds + Txns, Removes, or Metadata+Protocol.
Note: I also attempted to apply a RowFilter. This works but provided no additional gain, and in the event every column was projected it slowed things down.
The results show that the old code is the same roughly as the new code when projecting every column. However when projecting just M+P actions there is a about a 2.75x improvement.
I have less data on this but the full EagerSnapshot on my 1,000,000 action table went from ~600-700ms to ~150ms.
=> perf: apply projection when reading checkpoint parquet

crates/core/src/operations/delete.rs, crates/core/src/operations/write.rs, python/tests/test_cdf.py
Adds CDC write support for the Delete operation. Tests added in python and rust :)
- closes https://github.com/delta-io/delta-rs/issues/2579
- related https://github.com/delta-io/delta-rs/issues/2720
=> feat(python, rust): cdc write-support for `delete` operation

crates/core/src/operations/load_cdf.rs
The arrow schema method wraps partition values, but these then incorrectly get read as Categorical/Dictionary values. Using the input schema fixes this.
=> fix(python, rust): use input schema to get correct schema in cdf reads

crates/core/src/operations/merge/mod.rs, crates/core/tests/command_merge.rs
This pr improves the merging performance by adding min/max filters to the early filter.
The number of files scanned from the target file table is reduced by using the table statistics. 
I have extended the early filter for this purpose. This filter is responsible for pre-filtering the target table. 
Previously, the early filter only consisted of partition columns by filtering for all unique values from the source. Now the non-partition columns are also used by aggregating the min/max values from the source and adding a between expression to the early filter. 
It is also automatically part of the conflict detection based on the predicate.
I added a property `extended_early_filter` to make this advanced filtering optional. I don't know if this is important, and maybe we can replace the bool …
=> feat: improve merge performance by using predicate non-partition columns min/max for prefiltering

crates/core/src/kernel/arrow/mod.rs
Change root field name for map to key_value
https://github.com/delta-io/delta-rs/pull/2182
https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps
=> fix: change arrow map root name to follow with parquet root name

crates/core/src/kernel/models/actions.rs, crates/core/src/operations/add_column.rs, crates/core/src/operations/create.rs, crates/core/src/operations/mod.rs, crates/core/src/operations/set_tbl_properties.rs, crates/core/src/operations/transaction/protocol.rs, crates/core/src/operations/write.rs, crates/core/src/protocol/mod.rs, python/deltalake/_internal.pyi, python/deltalake/table.py, python/src/lib.rs, python/src/schema.rs, python/tests/test_alter.py
The schema evolution code is quite well abstracted from the writer, so it seemed straight forward to expose this through an `add column` api. This would make it easier for users to add new columns or fields in structs.
At some point we can add type widening to the schema evolution as a separate path, which also than could be used to create an `alter column` operation.
=> feat(python, rust): `add column` operation

crates/core/src/delta_datafusion/mod.rs, crates/core/src/delta_datafusion/schema_adapter.rs
When pushdown_filters on DataFusion SessionConfig is enabled for Parquet, map_partial_batch on the schema adapter is called with a batch that is evaluating the RowFilter created by pushdown_filters. The batch only contains the column(s) in the predicate for the RowFilter. If table_schema contains not null column then the cast will fail.
Example error:
```
thread 'delta_datafusion::tests::delta_scan_supports_pushdown' panicked at crates/core/src/delta_datafusion/mod.rs:2284:41:
called `Result::unwrap()` on an `Err` value: ArrowError(ExternalError(External(SchemaError("Could not find column col_2"))), None)
```
This change only uses from table_schema the columns that exist in the batch.
See https://docs.rs/datafusion/latest/datafusion/datasource/schema_adapter/trait.SchemaMapper.html#tymetho …
=> fix: schema adapter doesn't map partial batches correctly

crates/core/src/delta_datafusion/mod.rs, crates/core/src/delta_datafusion/physical.rs, crates/core/src/delta_datafusion/planner.rs, crates/core/src/operations/delete.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/write.rs
Changes delete to use logical plans from the get-go. I had to introduce `with_files` on `DeltaTableProvider` in case you want to constraint the scope of files to be read.
Additionally abstracts a DeltaPlanner struct, which was left as TODO, I used this to create a delete MetricObservation node
This one needs to be merged first: https://github.com/delta-io/delta-rs/pull/2722
=> feat: use logical plan in delete, delta planner refactoring

Cargo.toml, crates/core/src/kernel/arrow/mod.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/table/config.rs, crates/core/src/table/state_arrow.rs
Updates delta_kernel to 0.3.0, which includes a fix for Map internal field names among other things: https://github.com/delta-incubator/delta-kernel-rs/blob/v0.3.0/CHANGELOG.md#v030-2024-08-07
=> chore: update delta_kernel to 0.3.0

docs/usage/loading-table.md
Vacuuming tables section has moved.
Offending page: https://delta-io.github.io/delta-rs/usage/loading-table/#time-travel
Target page: https://delta-io.github.io/delta-rs/usage/managing-tables/#vacuuming-tables
=> docs: fix broken link in docs

.github/workflows/python_build.yml, crates/core/src/delta_datafusion/find_files/mod.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/add_column.rs, crates/core/src/operations/cast/merge_schema.rs, crates/core/src/operations/cast/mod.rs, crates/core/src/operations/cdc.rs, crates/core/src/operations/delete.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write.rs, crates/core/src/writer/record_batch.rs, python/Cargo.toml, python/deltalake/schema.py, python/deltalake/table.py, python/deltalake/writer.py, python/pyproject.toml, python/stubs/pyarrow/__init__.pyi, python/tests/pyspark_integration/test_write_to_pyspark.py, python/tests/test_schema.py, python/tests/test_table_read.py, python/tests/test_writer.py
Allows large/view types to be passed through during write, and prevents unnecessary potentially costly casting that could fail.
In Pyarrow engine only normal/large modes can be used, in Rust engine we always passthrough since we allow passthrough throughout the codebase now, this notion can be removed once pyarrow engine is fully deprecated.
Can be merged after: https://github.com/delta-io/delta-rs/pull/2727
- closes https://github.com/delta-io/delta-rs/issues/2319
- related https://github.com/delta-io/delta-rs/issues/2613, can only be closed when this is released: https://github.com/apache/arrow-rs/pull/6171
=> feat(python, rust): arrow large/view types passthrough, rust default engine

crates/core/src/delta_datafusion/cdf/mod.rs, crates/core/src/delta_datafusion/cdf/scan_utils.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/operations/write.rs, python/src/lib.rs, python/tests/test_cdf.py
Improved logic
- If it's partition scan, we don't write CDC actions and data. CDF reader will use remove actions in this case now to know what's deleted or not
- When the predicate doesn't hit a partition, we also write CDC data for the inserts
- closes https://github.com/delta-io/delta-rs/issues/2750
=> fix(python, rust): cdc in writer not creating inserts

crates/core/src/delta_datafusion/cdf/scan_utils.rs, crates/core/src/operations/load_cdf.rs, python/tests/test_cdf.py
Fields were being flatten which caused to create unnecessary null arrays.
=> fix(python, rust): don't flatten fields during cdf read

crates/core/src/kernel/snapshot/parse.rs
We can stop a bit earlier when all values in the array are null by just grabbing the null count from nullbuffer.
=> perf: early stop if all values in arr are null

python/src/utils.rs, python/tests/test_table_read.py
The tokio runtime does not support forked processes, so fail fast if we detect this scenario
- Avoids difficult to debug deadlocks
- Using the deltalake python bindings with `multiprocessing` can easily run into this problem because the default `multiprocessing` start method is `fork` on linux systems
- closes #2744
=> feat: fail fast on forked process

crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/catalog-glue/Cargo.toml, crates/core/Cargo.toml, crates/deltalake/Cargo.toml, crates/gcp/Cargo.toml, crates/hdfs/Cargo.toml, crates/mount/Cargo.toml, crates/test/Cargo.toml, dev/publish.sh
To the best of my knowledge and testing ( :laughing: ) the version ranges on subcrates should be fine since we did not incorporate any major API changes since the 0.18.x line.
This also includes a little script to help me release these things in the right order :tada:
=> chore: prepare the next notable release of 0.19.0

crates/core/Cargo.toml, crates/core/src/kernel/snapshot/mod.rs
Added column parsing to include nested columns and `` enclosing to adopt 0.18.x
#2572  
https://github.com/delta-io/delta/blob/4b102d34a2ce881b2a851b4c6cfbf2ab3ab5534f/spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala#L549-L561
_extract_enclosed_string_ - is a utility function to remove enclosing characters from a string.
_get_stats_field_ - is a function to retrieve a field from a schema, handling nested field names and removing enclosing backticks.
=> fix: column parsing to include nested columns and enclosing char

Cargo.toml, crates/core/src/kernel/mod.rs, crates/core/src/kernel/models/fields.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/parse.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/operations/transaction/conflict_checker.rs, crates/core/src/operations/transaction/state.rs, crates/core/src/protocol/mod.rs, crates/core/src/test_utils/factories/actions.rs, crates/core/src/test_utils/factories/data.rs
This PR adresses some inefficiencies when creating stats for file pruning using the `PruningPredicate`. Rather then generating stats from file actions which we generate ad-hoc from teh underlying arrow data, we now read the stats directly from the raw file data - i.e. avoiding expensive roundtrips through file actions.
To make this work, we needed to include parsing partition values (adding the `partitionValues_parsed` field to action data) during log replay. As a follow-up we should make more use of the parsed partiton values #2771
=> feat: more economic data skipping with datafusion

python/deltalake/table.py, python/src/lib.rs, python/tests/test_writerproperties.py
added set_statistics_truncate_length in python WriterProperties
closes #2630
=> feat(python, rust): added statistics_truncate_length in WriterProperties

crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/filesystem_check.rs, crates/core/src/operations/transaction/state.rs, crates/core/src/protocol/checkpoints.rs, crates/core/tests/command_restore.rs, python/src/lib.rs
The `file_actions` method on our various state representations is quite inefficient, since it does some often unnecessary work converting out internal arrow state to the `Add` action representation. This PR removes some of the easy to remove call sites and does some drive by cleanup on the way.
All this is in preparation for some bigger work refactoring our checkpoint writing and generally fully embracing the arrow state.
=> chore: remove some `file_actions` call sites

python/deltalake/__init__.py, python/deltalake/_internal.pyi, python/deltalake/table.py, python/deltalake/writer.py, python/src/lib.rs, python/tests/test_writerproperties.py
addded ColumnProperties & BloomFilterProperties in WriterProperties
closes   #2785
=> feat(python, rust): add ColumnProperties And rework in python WriterProperties

crates/core/src/table/builder.rs
This trims trailing slash if present in a storage option's value
if it's key ends with `_URL` (e.g. `HOST_URL`) or if the value
itself seems to be a url (i.e. starts with `http://` or `https://`).
This also adds supporting test for this fix.
- closes https://github.com/delta-io/delta-rs/issues/2656
N/A
=> fix: trim trailing slash in url storage options (#2656)

crates/aws/src/storage.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/lib.rs, crates/core/src/logstore/mod.rs, crates/core/src/operations/convert_to_delta.rs, crates/core/src/operations/writer.rs, crates/core/src/storage/mod.rs, crates/core/src/table/builder.rs, crates/core/src/table/mod.rs, crates/core/tests/integration_datafusion.rs, python/Cargo.toml, python/src/lib.rs
A configured Tokio handle can be passed into the TableBuilder nested in the RuntTime enum, conveniently added a default which simply creates a new runtime and uses that handle.
- https://github.com/delta-io/delta-rs/issues/2595, https://github.com/delta-io/delta-rs/issues/2592
=> feat: configurable IO runtime

python/deltalake/table.py
This functionality was removed a while ago since it wasn't working, we only didn't remove the python code yet. For now we can raise notImplemented and enable it again at a later stage
=> chore(python): raise not implemented in from_data_catalog

crates/core/Cargo.toml
`cargo build` just in core was broken previously. When building at the root of the project this did not fail because some combination of feature flags for tokio were being used during that `cargo` run
=> fix: enable feature flags to which deltalake-core build tokio with enable_io

docs/api/delta_writer.md, docs/usage/writing/index.md
Added Docs for BloomFilterProperties, ColumnProperties, WriterProperties
=> docs: added WriterProperties documentation

python/tests/test_benchmark.py
Benchmark was still using the old optimize syntax which got removed a couple commits ago :)
=> test(python): fix optimize call in benchmark

python/deltalake/table.py
The docstring wasn't rendering properly, see https://delta-io.github.io/delta-rs/api/delta_table/delta_table_alterer/#deltalake.table.TableAlterer.set_table_properties, so I _think_ I fixed the syntax (I haven't tested it locally, does the CI build the docs?) and I also added an example (mostly taken from another docstring + https://github.com/delta-io/delta-rs/blob/fcd62ab10be9545eab296f03ae0e4324fc4be6cb/python/tests/test_alter.py#L184-L189)
=> docs: fix docstring of set_table_properties

crates/aws/src/storage.rs
If we don't explicitly set a token provider with our region provider, then the SDK loader takes the default region provider chain which then starts pinging the ec2 metadata address, and emits unnecessary warnings.
- closes https://github.com/delta-io/delta-rs/issues/2819
=> fix(rust): set token provider explicitly

crates/core/src/protocol/mod.rs
Make statistics available on `Add`s loaded via `DeltaTableState::get_file_actions`, by making `Add::get_json_stats`.
Closes #2821
=> feat: make `Add::get_json_stats` public

python/deltalake/_internal.pyi, python/deltalake/table.py, python/src/lib.rs, python/src/merge.rs
This was one of my first contributions, so clearly there was some room for improvements ^^
Now DeltaTable.merge returns a PyMergeBuilder. On this builder we keep building the when statements, then RawDeltaTable.execute consumes the PyMergeBuilder
=> refactor(python): add pymergebuilder

crates/core/src/operations/optimize.rs, python/deltalake/table.py
`max_spill_size` had misleading documentation that seemed to indicate the limit on disk.
However, the value was a limit on memory to avoid out-of-memory and to spill to disk on such case.
This issue was raised in https://github.com/delta-io/delta-rs/issues/2205
- closes #2205
=> docs: fix documentation about max_spill_size

python/deltalake/_internal.pyi, python/deltalake/table.py, python/deltalake/writer.py, python/src/lib.rs, python/src/merge.rs
Make better use of Pyo3 api :)
This one https://github.com/delta-io/delta-rs/pull/2823 should be merged first
=> refactor(python): post_commit_hook_properties derive

python/deltalake/table.py, python/tests/test_table_read.py
This adds a public method `partitions()` to the `DeltaTable` class to get properly formatted partitions (list of dicts) for the table. Also provides an option to return partitions as a list of tuples, and proxies the partition filters to rust `get_active_partitions()`.
This also adds supporting tests for this feature.
- closes #2671
Documentation included in method's docstring.
=> feat: public method to get partitions for DeltaTable (#2671)

crates/core/src/operations/merge/barrier.rs, crates/core/src/operations/merge/filter.rs, crates/core/src/operations/merge/mod.rs, python/tests/test_merge.py
is_in filters can be used now to do partition pruning, I also moved all the filter logic into it's own module.
- closes https://github.com/delta-io/delta-rs/issues/2802
- closes https://github.com/delta-io/delta-rs/issues/2726
=> fix(python, rust): allow `in` pushdowns in early_filter

.github/workflows/build.yml
This is shamelessly borrowed from our code in the kernel repo
=> chore: enable codecov reporting

crates/core/src/operations/write.rs
The PR contains the following:
* Defines a WriteMetrics struct
* Writes metrics to app_metadata under key "operationMetrics"
* Adds assertions to unit tests that get the latest commit info and check that metrics have been written
* Updates a few test assertions that changed because the commit info has more metadata.
closes #1992
=> feat(rust): add operationMetrics to WRITE

.github/workflows/build.yml, Cargo.toml
=> chore: pin the Rust baseline version to 1.80

python/Cargo.toml
This is the patch that was used to resolve the release errors of python-v0.19.2 for the Linux manywheels
Upstream reference openssl/openssl#25367
Fixes #2848
=> fix: pin the build-dependencies for Python to a slightly older vendored openssl

crates/core/src/writer/stats.rs, python/tests/test_writer.py
We parse the indents and then join them again with "." since the parquet SchemaDescriptor is using full paths.
- closes https://github.com/delta-io/delta-rs/issues/2849
=> fix: escaped columns in dataskippingstatscolumns

crates/mount/src/file.rs
Put opts were getting passed create always, but in mount storage we have to use overwrite mode always.
- closes https://github.com/delta-io/delta-rs/issues/2860
=> fix: set put mode to overwrite in mount backend

crates/core/src/operations/write.rs, python/tests/test_writer.py
fixed scan schema for predicate write
- closes #2867
=> fix(rust): scan schema fix for predicate

.github/dependabot.yml
The major update-type still means we're getting pinged with some frequency
=> chore: attempt to ignore all dependabot checks for arrow and datafusion

Cargo.toml, crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/catalog-glue/Cargo.toml, crates/gcp/Cargo.toml, crates/hdfs/Cargo.toml, crates/mount/Cargo.toml
had to do a little surgery to get the release out :face_with_head_bandage: , these are the changes
=> fix: pin broken dependencies and changes in 0.19.1

crates/core/src/operations/transaction/mod.rs, python/deltalake/__init__.py, python/deltalake/_internal.pyi, python/deltalake/table.py, python/deltalake/writer.py, python/src/lib.rs, python/src/merge.rs, python/tests/test_alter.py, python/tests/test_delete.py, python/tests/test_merge.py, python/tests/test_optimize.py, python/tests/test_repair.py, python/tests/test_restore.py, python/tests/test_update.py, python/tests/test_vacuum.py
Adds a `with_max_retries` in `CommitProperties`. Allow for clients to control the maximum number of times a commit will be retried before failing.
=> chore: set max_retries in CommitProperties

python/deltalake/table.py
https://github.com/delta-io/delta-rs/issues/2851
@ericvandever, this doesn't fix the coercion but allows you to still use large_dtypes=False to downcast so that you can still run most of your queries
=> fix: re-enable optional old casting behavior in merge

crates/core/src/storage/mod.rs
Disabled the ability to enable_io on non-unix systems
=> fix: conditionally disable enable_io non-unix based systems

docs/integrations/delta-lake-dagster.md
Correct the keyword on `Using Delta Lake and Dagster with Polars` section
=> docs: fix typo in delta-lake-dagster

python/deltalake/schema.py, python/stubs/pyarrow/__init__.pyi, python/tests/test_schema.py
The current code lacks support for pyarrow's [`ExtensionType`](https://arrow.apache.org/docs/python/generated/pyarrow.ExtensionType.html) when writing to Delta Lake, which is used by many libraries in the pyarrow ecosystem. This PR aims to improve the Delta Lake Python bindings to enhance support for these third-party ecosystems.
For example, the following code tests that data can be correctly written after adding this PR per https://github.com/Eventual-Inc/Daft/pull/2827#issuecomment-2346463669:
```py
import daft
df_dogs = daft.from_pydict(
{
"urls": [
"https://live.staticflickr.com/65535/53671838774_03ba68d203_o.jpg",
"https://live.staticflickr.com/65535/53671700073_2c9441422e_o.jpg", …
```
=> feat: add support for `pyarrow.ExtensionType`

crates/core/src/table/mod.rs
While storing `_last_checkpoint` delta-rs does not convert json keys to camel case, but protocol mentions they should be in camelCase, fix exactly that :)
Fixes https://github.com/delta-incubator/delta-kernel-rs/issues/326
Issue description is nicely documented :)
Tested with local crate copy and created a table
=> fix: convert last checkpoint json keys to camelCase

crates/aws/tests/integration_s3_dynamodb.rs, crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/logstore/mod.rs, crates/core/src/operations/create.rs, crates/core/src/storage/mod.rs, python/Cargo.toml
If a process fails before the initial commit is able it's possible for _commit(.*).tmp to be placed inside _delta_log/ and then a subsequent attempt to the create the delta table will fail because the log store believes it has been created but no initial transaction exists.
Sponsored-by: Scribd Inc.
=> fix: ensure log store correctly identifies existing delta tables

docs/usage/managing-tables.md
Currently the docs section [usage/Managing a table](https://delta-io.github.io/delta-rs/usage/managing-tables/) states that
> Optimizing tables is not currently supported.
This PR adds a short explanation of optimize and links to the more detailed examples of the usage/Optimize sections.
Closes #2891
https://delta-io.github.io/delta-rs/usage/managing-tables/
=> docs: updating usage/managing-tables on optimizing tables

crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/optimize.rs, python/tests/test_optimize.py
The real fix should be likely done in Datafusion, allowing [ListingTableUrl] to be directly created rather than needing to parse the &str passed  through
Fixes #2834
=> fix: double-encode paths during zorder optimize when they contain special characters

crates/core/src/operations/transaction/mod.rs
TransactionError::CommitConflict exposes private CommitConflictError. 
Cleaner access to Commit Conflict, allowing handling it in match for metrics/logging/error handling.
=> refactor: exposing CommitConflictError enum

docs/integrations/object-storage/s3-like.md
Fixes a few typos in cloudflare/minio docs page, adds working docker example and notes on special storage_option flags for http vs https.
- closes #2894
Updated docs to use `"aws_conditional_put":"etag"` due to the issue identified below.
=> docs: updating docs for MinIO and Docker, with working conditional put support

crates/core/src/operations/merge/mod.rs, python/Cargo.toml, python/tests/test_merge.py
DataFusion doesn't have unionByName or a relaxed concat, so the before and after schema needs to be in the same order. The before though was getting expressions in different order. So just doing a simple select_columns afterwards to take the after schema order (which has the write projection order)
- closes https://github.com/delta-io/delta-rs/issues/2908
- closes https://github.com/delta-io/delta-rs/issues/2832
=> fix: cdc merge union schema order

crates/azure/Cargo.toml, crates/azure/tests/integration.rs, crates/core/src/data_catalog/storage/mod.rs, crates/core/src/storage/mod.rs, crates/core/tests/fs_common/mod.rs
The `ListingTableProvider` used to gather `delta tables` from an `object_store` did not pass the `storage_options` (connection details) to the `object_store` library. Therefore, it was not possible to establish a connection. This PR fixes that specific issue
None
None
=> fix: `ListingSchemaProvider` not forwarding custom `storage_options`

crates/aws/Cargo.toml, crates/aws/src/credentials.rs
This change addresses some of the problems tacked onto #2893 but does not address the concern with ECS specifically. It does however improve the handling of `storage_options` since the improved credential provider code was introduced
=> fix: properly handle the different flavors of storage options keys

python/tests/test_writer.py
These tests help demonstrate schema evolution behavior when passing timestamps with and without timezones into write_deltalake() which can be confusing sine the `timestampNtz` case causes a necessary but aggressive minWriterVersion upgrade
=> chore: introduce some more writer tests to demonstrate schema promotion

python/src/utils.rs
Loading in delta tables from multiple threads is causing panics. Reproducible example:
```python
from multiprocessing.pool import ThreadPool
from deltalake import DeltaTable
def make_dt(x):
return DeltaTable('/path/to/some/local/table')
pool = ThreadPool(processes=16)
list(pool.map(make_dt, range(16)))
```
causes
```
pyo3_runtime.PanicException: Failed to record PID for tokio runtime.: 71866
```
This race condition is caused by multiple threads trying to acquire and set the `PID`. Multiple threads could succeed at the `PID.get()` call at time before any threads set the `PID`, but only one thread can successfully call `PID.set`, causing the remaining threads to panic.
This fixes by using `get_or_init` for setting `PID`, and only panics if the returned `runtime_pid` is different from the …
=> fix: panics when creating delta tables in threads

docs/how-delta-lake-works/architecture-of-delta-table.md
Fix typos and errors in the code of the "architecture" documentation
=> docs: minor fixes to the architecture documentation

crates/core/src/operations/cast/mod.rs, python/tests/test_writer.py
Adds information on the field, to-type and from-type when casting fails.
We could consider using our own error type for the casting errors to allow unrolling errors to get the full path to a field. Currently we only give the last part of the path.
When looking at `cast_field` I noticed that we might be missing a match on `(DataType::List(_), DataType::LargeList(_))`. Casting List to LargeList can currently cause some tricky behaviour. I had a record batch with a List type, and tried reading it with a LargeList schema. For some choices of schemas it failed with an error message, for other schemas is did not fail, but read the columns in the wrong order.
=> fix: improve errors on field cast failures

crates/core/src/protocol/checkpoints.rs
Both commits describe the specific fixes, but basically our checkpoint code was collecting too much into memory when it could iterate! :roller_coaster: 
With a test table:
Before
`Maximum resident set size (kbytes): 19964728`
After
`Maximum resident set size (kbytes): 4017132`
Sponsored-by: [Scribd Inc](https://tech.scribd.com)
=> fix: dramatically reduce checkpoint memory consumption

.github/workflows/dco.yml
=> chore: enable a dummy DCO app to unblock the merge queue

crates/core/src/protocol/checkpoints.rs
For checkpoint buffers that cannot fit into the batch size the checkpoint will be written with an insufficient number of bytes.
Unfortunately our tests didn't catch this and it only manifested on tables with very large transaction logs
=> fix: ensure the checkpoint decoder is regularly flushed

crates/core/src/operations/optimize.rs
Ooops this fell through
Fixes #2962
=> chore: be less verbose about zorder

crates/core/src/operations/writer.rs
In an edge case of having a delta writer with _many_ partitions, the close operation can be quite slow as it closes the inner partition writers serially. This change makes the close concurrent.
n/a
n/a
=> perf: close partition writers concurrently

crates/core/src/protocol/checkpoints.rs
This change pushes more serialized json actions into the decoder before flushing. For a log with 10s of thousands of actions, the current implementation took ~18 seconds, this change dropped it to 3.
n/a
https://docs.rs/arrow-json/53.2.0/arrow_json/reader/struct.Decoder.html#method.decode
=> perf: batch json decode checkpoint actions when writing to parquet

Cargo.toml
Closes #2382 as this includes https://github.com/apache/arrow-rs/pull/5830
Nothing to add here.
=> fix: update object_store to 0.10.2

crates/core/src/writer/json.rs, crates/core/src/writer/mod.rs
This is a fix aimed to enable jsonwriter to checkpoint in accordance with delta.checkpointInterval.  It changes the default commitbuilder to set a post_commit_hook so that checkpointing will be done by default. Potentially we could also expose CommitProperties as an argument to flush_and_commit, but that would require a change to the function signature and would be a breaking change.
- closes #2992
=> fix: jsonwriter should checkpoint by default

crates/core/src/logstore/mod.rs
In `logstore.is_delta_table_location()`, if a checkpoint file is the earliest/first file in a table's transaction log, the table should be positively identified as a delta table. (Currently, it only recognizes delta tables for which a commit json is the first file in the transaction log)
- Closes #3004
=> fix: correctly recognize existing delta tables using the transaction log

crates/aws/src/constants.rs, crates/aws/src/storage.rs
Suppressed the deprecation warnings coming in the "Spot-check..." step of [this build](https://github.com/delta-io/delta-rs/actions/runs/11834814138/job/32981029044?pr=2994).
closes #2995
=> fix: fixed the deprecation warnings in spot check step of the build

docs/usage/loading-table.md
Added the `storage_options` parameter to the `is_deltatable()` method in Usage's "Verify Table Existence" section.
closes #3002
=> docs: fix the verify table existence example in usage docs

crates/core/src/writer/stats.rs
Try to detect the situation where floating point conversion rounds the integer value beyond the valid Decimal(scale, precision) range, and rollback to next smaller value towards 0.0.
Closes #2974 
None
=> fix: decimal stat rounding overflow

crates/aws/LICENSE.txt, crates/azure/LICENSE.txt, crates/catalog-glue/LICENSE.txt, crates/core/LICENSE.txt, crates/deltalake/LICENSE.txt, crates/gcp/LICENSE.txt, crates/hdfs/LICENSE.txt, crates/mount/LICENSE.txt, crates/sql/LICENSE.txt
Hi, thanks for this project! This symlinks the license file so it's included in published crates.
None
N/A
=> chore: include license files in published crates

docs/index.md
The PR sets a proposed change to the text on the first page of the docs. When I arrived on these pages as a new user I found the current text did not answer the basic questions I had about the library. I've proposed a new text, though I'm happy to take on feedback. 
Note: there is some overlap with the ideas on the "Why use delta lake" page. In essence I'm proposing having a quick summary of those concepts and a quickstart guide on the first page as I feel that for potential new users who have no familiarity with delta spark the current front page goes into more technical detail on that relationship than necessary.  
I'd like to do a follow-on where the Why use delta lake page. I'm also wondering whether quickstart should be on a separate page in this section to make it easy to find.
- …
=> docs: explain the value of deltalake on first page of docs

crates/core/src/delta_datafusion/expr.rs, python/tests/test_merge.py
In the expr to str conversation was an issue for dates.
Before this expr `lit(ScalarValue::Date32(Some(18262)))` was converted to `_date = 2020-01-01`. If you want to parse this string again as an expr it will result into `...BinaryExpr(**BinaryExpr { left: BinaryExpr(BinaryExpr { left: Literal(Int64(2020)), op: Minus, right: Literal(Int64(1)) })...` which is not correct.
Now `lit(ScalarValue::Date32(Some(18262)))` will be converted to `_date = '2020-01-01'::date`, which will be parsed a as date again. 
- closes #2980
- closes https://github.com/delta-io/delta-rs/issues/2462
=> fix: expression with dates to string conversation

crates/aws/src/credentials.rs, crates/core/src/delta_datafusion/expr.rs, crates/core/src/writer/stats.rs, crates/test/src/datafusion.rs, python/src/features.rs, python/src/filesystem.rs, python/src/lib.rs
I fixed some warnings, only one allow this time because it made sense to keep the invoke.
=> chore: fixed a bunch of warnings and deprecations

crates/core/src/kernel/snapshot/log_data.rs
This pr is to get correct `num_rows` statistics for optimizing `select count(*) from xxx` case.
=> fix: num rows statistics

crates/core/src/table/config.rs, crates/core/src/writer/json.rs, crates/core/src/writer/record_batch.rs, crates/core/src/writer/stats.rs, crates/core/src/writer/test_utils.rs
This is an update to JsonWriter and RecordBatchWriter to allow them to write commit log stats information in accordance with delta.dataSkippingNumIndexedCols and
delta.dataSkippingStatsColumns if present on the table.  If these fields are unset, then the default behavior of collecting stats for the first 32 columns is preserved
- closes [#2982](https://github.com/delta-io/delta-rs/issues/2982)
Tested by running all unit tests with `cargo test` as well as followed the instructions in CONTRIBUTING.md
=> fix: jsonwriter and recordbatchwriter to respect stats skipping

crates/core/src/operations/write.rs
This change also refactors the check_preconditions function itself to be a bit less redundant and even includes some unit tests! Holy smokes!
I'm going to stand up a few pull requests as I work through this refactor incrementally
Related to work on #2968
=> chore: refactor some of the writebuilder preconditions into the appropriate function

python/src/lib.rs
Ending_timestamp was passed to starting_timestamp instead of ending_timestamp
cc@hntd187 
- closes https://github.com/delta-io/delta-rs/issues/3023
=> fix(python): pass ending_timestamp correctly

Cargo.toml, crates/core/Cargo.toml, crates/core/src/kernel/models/fields.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/protocol/checkpoints.rs, crates/deltalake/Cargo.toml, python/Cargo.toml, python/tests/test_checkpoint.py
This  workaround fixes #3030 but I'm not quite happy about how. I believe there is likely an upstream issue in arrow that I have not been able to reproduce where the nullable struct (deletionVector) which has non-nullable members (e.g. storageType) that are being read as empty strings rather than `null`.
This issue started to appear with the v0.22 release which included an upgrade to datafusion 43 and arrow 53. I believe the latter is causing the issue here since it affects non-datafusion code paths.
This workaround at least allows us to move forward and release a v0.22.1 while continuing to hunt down the issue.
=> fix: workaround for Add actions being read slightly differently out of parquet files

crates/core/src/delta_datafusion/mod.rs, python/tests/test_merge.py
Adds a check for top level column nullability whether the arrays in recordbatch contain nulls when they shouldn't.
- closes https://github.com/delta-io/delta-rs/issues/2991
This is probably required in nested fields as well, so something for a follow-up
=> fix: check top level nullability during write

Cargo.toml, crates/core/Cargo.toml, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/kernel/snapshot/parse.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/protocol/checkpoints.rs, crates/deltalake/Cargo.toml, python/Cargo.toml, python/tests/test_checkpoint.py
=> fix: attempt to workaround problems reading actions as empty rather than null

crates/core/src/operations/merge/mod.rs, python/tests/test_merge.py
=> fix: add explicit type casts while merge

Cargo.toml, crates/aws/src/lib.rs, crates/core/src/delta_datafusion/expr.rs, crates/core/src/kernel/models/actions.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/operations/optimize.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/operations/transaction/state.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/protocol/mod.rs, crates/core/src/schema/partitions.rs, crates/core/src/table/config.rs, crates/core/src/table/state_arrow.rs, crates/core/src/test_utils/factories/actions.rs, crates/core/src/writer/json.rs, crates/core/src/writer/record_batch.rs, crates/core/src/writer/stats.rs, python/src/lib.rs
bumps delta-kernel to `0.5.0`. This is a duplicate of #3036. @ion-elgreco, you choose if you want to merge this or finish yours. Just opened it since @rtyler mentioned some DF issues.
I think there may be one or two additional clippy fixes in the PR, but easy to add them later.
=> chore: bump delta-kernel to 0.5.0

.github/actions/setup-env/action.yml, .github/workflows/python_benchmark.yml, .github/workflows/python_build.yml, python/.gitignore, python/CONTRIBUTING.md, python/Makefile, python/README.md, python/pyproject.toml, python/uv.lock
Add [`uv`](https://docs.astral.sh/uv/) for python dependency management and building tool.
- partially closes #2949
=> chore: use uv

crates/core/src/operations/transaction/mod.rs, crates/core/src/protocol/checkpoints.rs, python/tests/test_checkpoint.py
- If explicitly creating checkpoint, we raise
- If checkpoint creation called in post_commit_hook, we warn
- closes https://github.com/delta-io/delta-rs/issues/3049
=> fix: raise during checkpoint creating with without_files

.github/workflows/build.yml, .github/workflows/codecov.yml, Cargo.toml, crates/aws/Cargo.toml, crates/azure/Cargo.toml, crates/catalog-glue/Cargo.toml, crates/catalog-unity/Cargo.toml, crates/core/Cargo.toml, crates/deltalake/Cargo.toml, crates/gcp/Cargo.toml, crates/hdfs/Cargo.toml, crates/mount/Cargo.toml, crates/test/Cargo.toml, python/Cargo.toml
a number of our transitive dependencies have forced the upgrade in patch versions of the Minimum Supported Rust Version (MSRV) and broke builds from crates.io and `main` on Rust 1.80. :unamused:
This change upgrades us to 1.81 but bumps to 0.23 in the process.
=> chore: create a new minor version with the MSRV upgrade

crates/mount/src/file.rs
Remove a println that looks to be unnecessary.
Closes #3070
=> fix: remove println from regular_rename func

Cargo.toml, crates/core/Cargo.toml, crates/sql/src/parser.rs
This PR is designed to help test DataFusion 44 with delta-rs *before* we release DataFusion
- It targets https://github.com/delta-io/delta-rs/pull/3073 from @rtyler 
It temporarily pins DataFusion to the latest version on main so we can test / verify the tests run
- https://github.com/delta-io/delta-rs/pull/3073
- https://github.com/apache/datafusion/issues/13834
=> chore: pin to pre-release DataFusion to test upgrade to 44

crates/aws/src/storage.rs
Fixes the is_aws check by using the correct aws_endpoint key. It's always the `aws_endpoint` lowercase after going through `with_env_s3`
=> fix: use correct aws_endpoint key

crates/catalog-unity/src/error.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/optimize.rs, crates/sql/src/parser.rs, crates/test/src/datafusion.rs
- targets https://github.com/delta-io/delta-rs/pull/3073 from @rtyler 
This PR makes some small changes to reduce the build warnings by using non deprecated APIs
=> chore: Reduce compiler warnings by updating to use non deprecated DataFusion APIs

crates/core/src/delta_datafusion/mod.rs
Adds test coverage for the regression fixed in 2272ff7051a013b0e0a3b45234e3b69168b1fe3b
=> fix: add test for Parquet column pruning in scans

CONTRIBUTING.md
uv is needed to use the make file for development, but uv is not installed in the venv and there is not a command to activate the venv. 
This PR adds the sh command to activate the venv and the command to install uv before executing the Makefile.
=> Add steps to install uv in venv

crates/core/src/lib.rs
Maybe we could run CI with
```
cargo clippy ... -- -D warnings
```
to catch this early?
=> fix: use of deprecated DeltaTable::peek_next_commit

Cargo.toml, README.md, crates/aws/src/lib.rs, crates/aws/src/storage.rs, python/pyproject.toml
- closes https://github.com/delta-io/delta-rs/issues/2843
=> refactor: make put-if-absent default for S3 stores

crates/core/src/delta_datafusion/expr.rs, python/tests/test_merge.py
- closes https://github.com/delta-io/delta-rs/issues/3033
=> fix: add decimal expr parsing

crates/core/src/kernel/scalars.rs, python/Cargo.toml
Fixes the polars test failures: https://github.com/pola-rs/polars/actions/runs/12580193685/job/35061681377#step:11:230
I'll do a bugfix release after merge
=> fix: scalar extraction view types

.github/workflows/python_build.yml, python/Makefile, python/pyproject.toml, python/tests/test_writer.py
=> fix: introduce a reproduction case for List casting with polars

python/deltalake/table.py, python/tests/test_merge.py
Adds optional argument `exclude` to MergeBuilder functions, so that it is simpler to update all columns except a select few.
- closes #2833
=> feat(python): add `except_cols` argument to `when_matched_update_all` and `when_not_matched_insert_all` for excluding specific columns

python/deltalake/query.py, python/tests/test_table_read.py
Adds user friendly methods, namely sql() and show() to the QueryBuilder
- closes #3076
=> feat(python): add sql() and show() convenience method to QueryBuilder

docs/src/rust/check_constraints.rs, docs/src/rust/read_cdf.rs, docs/usage/appending-overwriting-delta-lake-table.md, docs/usage/create-delta-lake-table.md, docs/usage/deleting-rows-from-delta-lake-table.md, docs/usage/examining-table.md, docs/usage/loading-table.md, docs/usage/managing-tables.md, docs/usage/merging-tables.md, docs/usage/optimize/delta-lake-z-order.md, docs/usage/optimize/small-file-compaction-with-optimize.md, docs/usage/querying-delta-tables.md, docs/usage/read-cdf.md
This PR is intended to add high-level (mainly usage) documentation of delta-rs using the Rust API.
closes #3088
Progress:
- - [x] Loading a table
- - [x] Verify table existence
- - [x] Time travel
- - [x] custom storage options
- - [ ] custom storage backends
=> docs: rust usage documentation

python/Cargo.toml, python/src/error.rs, python/src/filesystem.rs, python/src/lib.rs, python/src/query.rs, python/tests/test_threaded.py, python/tests/test_writer.py
This change introduces an internal Mutex inside of RawDeltaTable which allows the PyO3 bindings to share the Python object between threads at the Python layer.
PyO3 will raise a `RuntimeError: Already borrowed` for any function call which takes a mutable reference to `self`. Introducing the internal Mutex ensures that all function signatures can operate with just self-references safely.
The Rust-level Mutex is a simple passthrough for most operations which do not need to modify the underlying state. The critical sections which typically need to acquire and mutate with a lock are after I/O bound operations are completed as far as I can tell, so I don't anticipate deadlock or performance issues.
There is still some cleanup of errors that needs to happen to make the code here more ergonomic …
=> feat: allow multiple Python threads to work with a single DeltaTable instance

crates/aws/Cargo.toml, crates/aws/src/lib.rs, crates/aws/src/storage.rs, python/Cargo.toml
- Adds a trait to logstore and objectstore factory to parse options
- LogStoreFactory gets correct credentials as well now
- Reduces latency by only construction SDK config once for object store
- Fixes is_aws by also checking the env vars for locking provider and force_aws_credential_load, tested it and doesn't show aws sdk config logs anymore when you use endpoint url
cc @rtyler
=> fix: aws credential resolving, reduce api calls

crates/core/Cargo.toml, crates/deltalake/Cargo.toml
This change should be the final one in the 0.23.x release line since we're about to merge LakeFS support and go to 0.24
=> chore: raise patch versions for rust crate release

Cargo.toml, crates/core/Cargo.toml, crates/core/src/kernel/models/actions.rs, crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/kernel/snapshot/parse.rs, crates/core/src/operations/add_feature.rs, crates/core/src/operations/cdc.rs, crates/core/src/operations/constraints.rs, crates/core/src/operations/create.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/operations/transaction/protocol.rs, crates/core/src/operations/write.rs, crates/core/src/protocol/parquet_read/mod.rs, crates/core/src/test_utils/factories/actions.rs, crates/core/tests/read_delta_log_test.rs
Swapped out table features code from internal to delta-kernel-rs.
=> refactor: use kernel table features

crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/logstore/mod.rs
The current implementation of `is_delta_table_location` only check the first file in the `_delta_log` folder to check for the presence of a commit or checkpoint file. This creates issue when checking tables created using the Spark driver since `.crc` files are created and appear before commit files in the directory.
This MR modifies the behavior of `is_delta_table_location` so that files are checked in a loop. `.crc` files are ignored and the loop execution stops as soon as a commit, checkpoint or invalid file is found.
- closes #3115
=> fix: ignore crc files when checking if provided path correspond to a valid delta table

Cargo.toml, crates/aws/src/storage.rs, crates/azure/src/lib.rs, crates/core/Cargo.toml, crates/core/src/storage/mod.rs, crates/gcp/src/lib.rs, crates/lakefs/src/storage.rs, docs/integrations/object-storage/special_configuration.md, mkdocs.yml
- closes https://github.com/delta-io/delta-rs/issues/3128
=> feat: retryable config enablement through storage_options

crates/core/src/delta_datafusion/expr.rs, python/tests/test_merge.py
- closes https://github.com/pola-rs/polars/issues/20597
=> fix: fmt scalar view values

crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/error.rs, crates/core/src/kernel/models/actions.rs, crates/core/src/kernel/models/schema.rs, crates/core/src/operations/add_column.rs, crates/core/src/operations/add_feature.rs, crates/core/src/operations/cast/merge_schema.rs, crates/core/src/operations/cdc.rs, crates/core/src/operations/create.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/transaction/protocol.rs, crates/core/src/operations/write.rs, crates/core/src/table/mod.rs, python/tests/test_generated_columns.py
Adds generated columns.
- closes https://github.com/delta-io/delta-rs/issues/3116
=> feat: generated columns

docs/usage/writing/index.md
Hello, I noticed a small typo when reading the documentation (_properites_ rather than properties).
One thing I noticed when using this documentation though: I could not find anywhere documentation for the syntax of `predicate` for `replaceWhere`. It would be useful to add some words on it.
N/A
https://www.thefreedictionary.com/properties
(joking :laughing:)
=> feat(docs): minor documentation typo

python/deltalake/table.py, python/src/lib.rs, python/tests/test_writerproperties.py
- Add support for [`statistics_enabled`](https://arrow.apache.org/rust/parquet/file/properties/struct.ColumnProperties.html#structfield.statistics_enabled) in `ColumnProperties`.
- Remove deprecated and unused `max_statistics_size` from `ColumnProperties`.
- #2965
The only available way currently to avoid writing statistics to the transaction log for a column is via `max_statistics_size`. However, that has been [deprecated](https://arrow.apache.org/rust/parquet/file/properties/struct.ColumnProperties.html#structfield.max_statistics_size) in `arrow-rs`, furthermore it appears to be ignored: https://github.com/apache/arrow-rs/issues/2033. Being able to skip statistics is necessary for large data columns, as otherwise transaction log explodes after a few tens of thousands of transactions and …
=> feat(python, rust): add statistics_enabled to ColumnProperties

crates/core/src/operations/merge/mod.rs, crates/core/src/operations/merge/writer.rs, crates/core/src/operations/write.rs
During some exploration to make merge streamable, the complication is an ArrowArrayStreamReader can only be consumed once, so when we materialize (execute) a physical plan which has this LazyTableProvider twice, the second run will have no data.
This PR makes the MERGE+ MERGE_CDF plan a combined plan, and splits out the data during the write. A side benefit is that we now just have one function to do the writing and return all actions.
@JonasDev1 your work in MERGE to use min_max pruning from the source for the target scan also complicates things a bit since we consume the stream as a whole. We can solve this by caching the df beforehand, but then everything will stay in memory defeating the streamed execution. I'm curious if you have any idea's on how we could do this without full …
=> refactor: combine normal and cdf plan until write for merge

crates/core/src/operations/write.rs, crates/core/tests/integration_datafusion.rs, python/tests/test_writer.py
We were still using physical plans as starting point, we now only take in logical plans and pass them around. This solves also issues with physical type coercion, since logical type coercion is more flexible.
This is a breaking change though since folks who use .`with_execution_plan `now how to provide a logical plan instead of a physical plan. 
- close https://github.com/delta-io/delta-rs/issues/3139
=> refactor: logical plans in writer

crates/catalog-unity/src/credential.rs, crates/catalog-unity/src/lib.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/write.rs, crates/core/tests/integration_datafusion.rs
The current providers don't cover getting tokens directly from the workspace. This PR adds that functionality.
https://docs.databricks.com/en/dev-tools/auth/oauth-m2m.html
=> feat: added workspace oauth source for UC

crates/core/src/operations/mod.rs, crates/core/src/operations/update_field_metadata.rs, crates/core/src/protocol/mod.rs
Implements a new operation: `UpdateFieldMetadataBuilder` to `upsert` metadata on a field in a schema. The implementation checks for conflicts with protected metadata (e.g. from `column mappings`). 
**This only modifies metadata in a field. No schema evolution occurs**.
Stems from a conversation on Slack
No documentation.
=> feat: update metadata field builder

.github/workflows/dev_pr.yml
I _believe_ I can remove this in order to prevent the check from failing on merges. I'm not sure if this is required in order for the merge group to pass required checks though :thinking:
=> chore: prevent the pr actions from filing on merge_group

python/.cargo/config.toml, python/Cargo.toml, python/src/lib.rs
We actually didn't use any other allocator than the default one, this should reduce our memory usage in the python binding.
=> chore(python): use custom global alloc

Cargo.toml, crates/core/src/data_catalog/storage/mod.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/writer/json.rs, python/Cargo.toml, python/src/filesystem.rs, python/src/lib.rs
chore: upgrade to DataFusion 45.0.0
- related to https://github.com/apache/datafusion/issues/14008
=> chore: update to DataFusion 45.0.0 / arrow/parquet `54.0.0`

Cargo.toml, crates/lakefs/Cargo.toml, dev/publish.sh, python/Cargo.toml
This is still marked as draft for the time being because there is not a released version of delta-kernel-rs which has the `default-engine-rustls` flag _and_ a compatible set of arrow dependencies :see_no_evil: 
Fixes #2857
=> fix: removing openssl from the dependency tree

python/src/lib.rs, python/tests/test_stats.py
- fixes https://github.com/delta-io/delta-rs/issues/3173
- fixes https://github.com/delta-io/delta-rs/issues/3201
=> fix: only use stats for required cols

crates/core/src/protocol/mod.rs
This method is likely at least as useful as the existing public methods get_json_stats and get_stats_parsed (which should probably be non-public).
=> feat: make Add:get_stats public

crates/core/src/errors.rs, crates/core/src/logstore/mod.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/writer/record_batch.rs, crates/core/src/writer/test_utils.rs, crates/core/tests/command_restore.rs, crates/core/tests/integration_datafusion.rs, python/tests/test_cdf.py
The eq check was incorrect, should be only greater than.
Also found small bug in get_latest_version. It would return a version that might be invalid if the start version is not existent. Add a robustness check in there and one recursion loop, to start from -1. This will either result in the correct version or stay -1 an throw not a table location :)
- closes https://github.com/delta-io/delta-rs/issues/3165
=> fix: load cdf latest version

crates/core/src/protocol/checkpoints.rs, crates/core/src/table/config.rs, crates/core/tests/checkpoint_writer.rs
This PR adds a table configuration option to enable or disable run length encoding for checkpoint files. 
Note: I'm unsure if the table option is the right way to go - In the original issue it was propose to expose `writerProperties` on create_checkpoint, however, after evaluating this, I figured this has a few downsides:
- The automatic checkpointing wouldn't be aware of those custom `writerProperties`
- `writerProperties` would expose too much control, i.e. I don't really need that level of control over the checkpoint writing
- bindings would need to be updated (I'm using python and C# bindings, so that would add additional work)
Instead I went down the route of table properties, unsure however if the Delta Lake spec allows implementation specific table properties, or if these should be …
=> feat: configurable column encoding for parquet checkpoint files

crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/protocol/checkpoints.rs
`PostCommit` now contains the number of retries it took to do the commit and `FinalizeCommit` now contains number of retries, whether there was a checkpoint created and number of log files cleaned-up.
This can be useful for consumers to track if the retries are approaching the maximum retry count.  It also allows consumers to correlate commit times with the amount of work being done for that commit.
=> feat: return metrics about the commit

README.md, crates/core/src/kernel/arrow/mod.rs, crates/core/src/protocol/checkpoints.rs
@roeap according to the protocol we should only write struct stats when enabled. Currently we were ignoring this config and always writing struct stats. The table config is now adhered when either of two are disabled.
- closes https://github.com/delta-io/delta-rs/issues/3207
=> fix: adhere write stats configuration

crates/core/src/delta_datafusion/cdf/mod.rs, crates/core/src/delta_datafusion/cdf/scan.rs, crates/core/src/delta_datafusion/expr.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/delete.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write.rs, python/deltalake/_internal.pyi, python/deltalake/table.py, python/src/lib.rs, python/tests/test_cdf.py
Simplifies the reading of CDF. 
cc @hntd187 
- closes https://github.com/delta-io/delta-rs/issues/2825
=> feat: cdf tableprovider with predicate pushdown support

crates/core/src/operations/filesystem_check.rs, python/deltalake/table.py, python/tests/pyspark_integration/test_write_to_pyspark.py
This changes how the files_removed array is serialized, making it a stringified representation of the list of files. This is done to ensure compatibility with Spark.
To maintain the current behavior with the python bindings, the repair method wrapper in python will deserialize back to a list.
closes #3140
=> fix(rust, python): treat FSCK files_removed as strings

.github/workflows/python_benchmark.yml
We got hit by a brownout :D
<https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down>
=> chore: switch to cache@v4

crates/core/src/operations/transaction/mod.rs
Currently with multiple retries we would conflict check the same versions because our starting point (read_snapshot) is never updated after conflict resolution, this could be costly with many concurrent writers.
=> fix: update snapshot after conflict check

python/Cargo.toml
Let's also merge this: https://github.com/delta-io/delta-rs/pull/3178 before the 0.25 release :) @rtyler
=> chore: bump python 0.25

crates/core/src/lib.rs, python/src/lib.rs
We initialize the client version when we init the python module. Makes it easier to see which tables got written with which binding and the version :)
- closes https://github.com/delta-io/delta-rs/issues/2008
=> feat: set clientVersion for python binding

CONTRIBUTING.md, python/Makefile
I wanted to start developing delta-rs and found CONTRIBUTING.md confusing as it asks you to create a Python virtualenv that is never used. This updates the documentation to account for the switch to uv.
This was partly addressed previously in #3085.
=> docs: update CONTRIBUTING.md and Makefile to account for switch to uv

.github/scripts/retry_integration_test.sh, .github/workflows/python_build.yml, python/Cargo.toml
This PR enables the `azure` feature for UC crate to make sure the `deltalake_azure` registered handlers are called [here](https://github.com/delta-io/delta-rs/blob/main/crates/catalog-unity/src/models.rs#L426-L430). Without this feature being enabled, it throws a warning from [here](https://github.com/delta-io/delta-rs/blob/main/crates/catalog-unity/src/models.rs#L432-L436) resulting in a `MissingCredentials` error - "Failed to get a credential from UnityCatalog client configuration".
Update: Also enables `gcp` and `r2` for UC crate.
- closes #3236
N/A
=> fix: enable missing cloud features for uc crate

crates/core/src/operations/transaction/mod.rs, python/deltalake/_internal.pyi, python/deltalake/writer.py, python/src/lib.rs, python/tests/test_checkpoint.py, python/tests/test_threaded.py
As per @roeap  suggestion to simply reload the table state after cleaning up logs so that we get a proper snapshot.
Introduces a write function on the DeltaTable which allows us to update the state after writing, which we couldn't do properly before.
- closes https://github.com/delta-io/delta-rs/issues/3057
- closes https://github.com/delta-io/delta-rs/issues/3062
=> fix: refresh snapshot after vacuuming logs

crates/aws/src/credentials.rs, crates/core/src/kernel/models/fields.rs, crates/core/src/operations/filesystem_check.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/transaction/mod.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write/mod.rs, crates/lakefs/src/storage.rs
chore: fix compiler warnings
While working on https://github.com/delta-io/delta-rs/pull/3261 I found several items that generated warnings locally for me:
For example:
```shell
/Users/andrewlamb/.cargo/bin/cargo test --color=always --workspace --profile test --no-fail-fast --config env.RUSTC_BOOTSTRAP=\"1\" -- --format=json -Z unstable-options --show-output
Testing started at 2:41 PM ...
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/andrewlamb/Software/delta-rs/python/Cargo.toml
workspace: /Users/andrewlamb/Software/delta-rs/Cargo.toml
warning: unused import: `std::future::Future`
--> crates/core/src/operations/transaction/mod.rs:77:5
|
77 | use std::future::Future;
|     ^^^^^^^^^^^^^^^^^^^
|
= note: …
```
=> chore: fix some compiler warnings

crates/core/src/kernel/scalars.rs, crates/core/src/kernel/snapshot/log_data.rs, crates/core/src/operations/optimize.rs, python/tests/test_optimize.py
Our DeltaTableProvider is better to use than reading directly with ctx.read_parquet, since the DeltaTableProvider has a schemaAdapterFactory which maps each batch to the input_schema. This creates consistency while reading. A good side effect is we don't need to that path serialization fix anymore @rtyler 
- closes https://github.com/delta-io/delta-rs/issues/3185
=> fix: use tableprovider scan in z-order

crates/catalog-unity/src/datafusion.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/protocol/checkpoints.rs, crates/core/tests/integration_datafusion.rs, crates/gcp/tests/context.rs, python/src/lib.rs
Similarly to https://github.com/delta-io/delta-rs/pull/3262 I would like to use compiler warnings and clippy locally to find places that need to be changed after DataFusion upgrade. This means I would to have main have a clean clippy run
I just did what clippy told me to mostly
- Related to https://github.com/delta-io/delta-rs/pull/3261
- Related to https://github.com/apache/datafusion/issues/14123
=> chore: fix clippy warnings on main

.github/workflows/dev_pr.yml
Out commitlint check for PRs is currently overly agressive. Specifically it will complian, when the body of a PR is a bit more verbose. However we should not punish contributors who put in the time to elaborate on theor PRs by enforcing a line length on the PR body. I seems that other share this assessment, since it should already be configured in our commitlint config. So just seeing whats going wrong and trying to get the cli to pick up the config. Being deliberately chatty here to have a long PR body ...
=> fix: commitlint config

crates/core/src/operations/merge/filter.rs
**Note this PR should have no functional change**
This is part of the DataFusion upgrade in https://github.com/delta-io/delta-rs/pull/3262, which I am trying to split into multiple parts to reduce the size of the diff (so to make it easier to review and debug)
DataFusion 46.0.0 adds a new field, `Column::spans` which requires changing all locations that create `Column` either to have a `span` in it or to use the constructor. So let's change the code to use the constructor here
- Related to https://github.com/delta-io/delta-rs/pull/3261
- Related to https://github.com/apache/datafusion/issues/14123
=> chore: update tests to use `Column::new` and other expr_fn functions

.github/workflows/python_release.yml, python/Cargo.toml
This was a very pesky issue to figure out but finally nailed it down to being a manylinux glibc compatibility issue. Essentially with glibc 2.17 we were seeing ssl handshake failures which has some relation to the ring crate. Anyway, the fix is to release additional wheels for manylinux 2_28.
I also took the liberty in splitting up the manylinux job in to separate jobs.
- closes https://github.com/delta-io/delta-rs/issues/3241
- closes https://github.com/delta-io/delta-rs/issues/3243
- closes https://github.com/delta-io/delta-rs/issues/2192
- closes https://github.com/delta-io/delta-rs/issues/1978
- closes https://github.com/delta-io/delta-rs/issues/3193
=> fix: aarch64 ssl handshakes

Cargo.toml
The crate Chrono has been updated to 0.4.40. This has caused a breaking change in Arrow - as I understand it. This causes Arrow to fail when building due to disambigious syntax. Pinning Chrono to its `=0.4.39` release will fix the build issue until the next Arrow release in March. 
[Arrow Issue 7198](https://github.com/apache/arrow-rs/pull/7198#issuecomment-2685365216)
[Chrono Discussion of the breaking change](https://github.com/chronotope/chrono/pull/1666#discussion_r1971811769)
None
=> fix: chrono 0.4.40 causes disambiguation syntax when building arrow deps

crates/core/src/kernel/models/actions.rs, crates/core/src/operations/write/mod.rs, python/tests/pyspark_integration/test_write_to_pyspark.py, python/tests/pyspark_integration/utils.py, python/tests/test_writer.py
When a schema evolution write occurs, if a metadata ID from the table state exists, use that in the new metadata transaction entry. 
This PR has a unit test and a new integration test that runs a Pyspark stream between evolution runs. I confirmed that the integration test failed with the error I've seen in production when I removed the new logic, and passes with the new logic.
closes #3274
=> fix(rust): on write, have a schema evolution maintain metadata table id

crates/hdfs/Cargo.toml
I noticed the `home` dependency was pinned on some old version while working on https://github.com/delta-io/delta-rs/pull/3261 and when I went to update it turns out it wasn't even  used 🤔
=> chore: remove unused dev dependency on `home`

crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/mod.rs, crates/core/src/kernel/models/schema.rs, crates/core/src/operations/constraints.rs, crates/core/src/table/config.rs, crates/core/src/table/mod.rs
When retrieving constraints from the table config, the name is set to an asterisk (*). The name is needed if you want to e.g. drop the constraint again. I have modified the code to use the found keys excluding `delta.constraints.`.
**Before:**
```
"name": "*",
"expr": "double LIKE 'DO%' AND double LIKE '%IT%'"
```
**After:**
```
"name": "my_new_constraint_name",
"expr": "double LIKE 'DO%' AND double LIKE '%IT%'"
```
Going through the code, I discovered the reason behind using the asterisk. It was for the `delta_datafusion::enforce_checks` function to format its `SQL`-query with `SELECT * ...` in a constraint check. To ensure the `enforce_checks` function still works, I have expanded the `DeltaCheck` trait to include `as_any()` to allow type checking in `enforce_checks` to condition how …
=> refactor: replaced asterisk with constraint name in get_constraints

crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/merge/mod.rs, python/tests/test_merge.py
During merge we should simplify the expression before creating the commit predicate. Additionally, inside the DeltaScan we also need to simplify the expression to improve the pruning.
- related https://github.com/delta-io/delta-rs/issues/3278
This doesn't fully fix it but discussing the issue here: https://github.com/apache/datafusion/issues/14944
=> refactor: simplify expressions

crates/core/src/operations/mod.rs, crates/core/src/operations/optimize.rs
These have been broken in main for a little while after the refactor that @ion-elgreco performed to make the Datafusion-path of optimize simpler.
I think this module being split between the not(datafusion) and datafusion features has led to a maintenance burden we can no longer maintain. Should this code come back, I would welcome it in a _separate_ module that is more easily tested and validated separately from the datafusion-based optimized.
=> feat: remove optimize operations when building without Apache Datafusion

python/Cargo.toml
this is what is percolating in a release right now
=> chore: bump python version for release

.cargo/config.toml
- closes https://github.com/delta-io/delta-rs/issues/3295
=> chore: use flags for apple arm64

python/deltalake/table.py, python/tests/test_writer.py
Currently, to_pandas() in delta-rs does not retain PyArrow decimal types. Instead, it converts all decimal columns into object dtype in pandas.
**1. Loss of Decimal Precision Metadata**
- A column stored as Decimal(18,0) in Delta Lake is converted to an object dtype in pandas.
- This conversion strips away the original precision (18,0), leading to issues when writing back.
**2. Schema Re-Inference in write_deltalake()**
- Since pandas lacks native decimal types, write_deltalake() re-infers the column schema based on the actual data instead of preserving the original Decimal(18,0).
- The schema is inferred as Decimal(11,0) if the longest number has 11 digits (e.g., `12345678901`).
**3. Decimal Overflow Errors on Write**
- But since the column is a Decimal datatype, it stores the same value …
=> fix(pandas): retain pyarrow decimal datatype in to_pandas() by adding types_mapper to prevent precision loss

crates/core/src/kernel/models/actions.rs
Alright, let's go to [Chotchkie's](https://officespace.fandom.com/wiki/Chotchkie%27s)
Fixes #3211
=> fix: serialize empty deletionVector in add actions as absent

.github/workflows/build.yml, .github/workflows/codecov.yml, Cargo.toml, crates/core/src/delta_datafusion/expr.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/operations/merge/barrier.rs, crates/core/src/operations/merge/mod.rs, crates/core/tests/integration_datafusion.rs, crates/sql/src/parser.rs, crates/sql/src/planner.rs, python/src/lib.rs
chore: upgrade to DataFusion 46.0.0
- related to https://github.com/apache/datafusion/issues/14123
=> chore: upgrade to DataFusion 46.0.0

crates/core/src/kernel/snapshot/mod.rs, crates/core/src/operations/write/mod.rs, crates/core/src/writer/stats.rs, python/tests/test_writer.py
Handle `BINARY` column appropriately when specified in `delta.dataSkippingStatsColumns` while writing to a delta table.
- closes https://github.com/delta-io/delta-rs/issues/2854
- related https://github.com/delta-io/delta-rs/issues/2373
- https://github.com/delta-io/delta-rs/pull/1766
- https://github.com/delta-io/delta-rs/pull/1498 (reverted in PR https://github.com/delta-io/delta-rs/pull/1544)
- 
N/A
=> fix: stats column binary_column has unsupported type binary

python/src/error.rs
Allows to see the full IO error message, will be displayed like this:
=> chore: improve io error msg

python/Cargo.toml, python/src/filesystem.rs
- closes https://github.com/delta-io/delta-rs/issues/3271
=> fix: block_in_place to allow nested tasks

docs/integrations/object-storage/adls.md
Add example to docs/integrations/object-storage/adls.md on how to authenticate using Azure CLI for Azure ADSL integration.
=> docs: add example how to authenticate using Azure CLI for Azure ADSL integration

crates/core/Cargo.toml, crates/core/src/operations/mod.rs, crates/core/src/operations/transaction/protocol.rs
@rtyler the cdf feature actually won't be used without datafusion, so just to simplify it we can gate it behind the datafusion feature
=> chore: remove cdf feature

crates/core/src/operations/restore.rs
This PR spins out of a thread in the Slack `delta-rs` channel.
I was testing out a table where the last two commits were: `ADD CONSTRAINT` and `DROP CONSTRAINT`. Using the `RestoreBuilder` , I attempted to restore the table back to the `ADD CONSTRAINT` to undo the `DROP CONSTRAINT`  metadata action. Nothing happened. Going through the code, I do see code "reversing" `ADD` vs. `REMOVE` actions but nothing for `METADATA`.
I would expect every actions from the restored table to the latest table to be "reversed". 
From a blog post on (Delta.io)[https://delta.io/blog/2022-10-03-rollback-delta-lake-restore/], they state: 
> ... this change does not erase version 2; instead, a metadata-only operation is performed in which the changes in version 2 are undone.
My proposal is to add a `METADATA` …
=> fix: added restored metadata as action to the next committed version

Cargo.toml, crates/core/src/delta_datafusion/expr.rs, crates/core/src/kernel/scalars.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/schema/partitions.rs, crates/hdfs/Cargo.toml, docs/integrations/delta-lake-daft.md, python/src/lib.rs
Updating delta_kernel to `0.10.0`. This included:
- unpinning `chrono` dependency
- upgrading `strum` from `0.26` to `0.27`
- updrading `hdfs-native-object-store` to `0.13`
- migrating to the new `Scalar::Decimal(decimal_data)` API (instead of the old `Scalar::Decimal(value, precision, scale)`)
(please let me know if I should file an issue!)
N/A
=> chore: update delta_kernel to 0.10.0

python/deltalake/table.py
Based on the behavior and the constant definitions in the codebase, that should be 100MB (or 104857600 bytes)
=> fix: the default target size should be 100MB

crates/core/Cargo.toml, crates/core/src/lib.rs, crates/core/src/logstore/config.rs, crates/core/src/logstore/factories.rs, crates/core/src/logstore/mod.rs, crates/deltalake/Cargo.toml, crates/deltalake/src/lib.rs
Make "cloud" feature of object_store be optional, if not required then parse_url_opts() doesn't need to take a "RetryConfig"
This removes a lot of dependencies for users who don't need "cloud": ["serde", "serde_json", "quick-xml", "hyper", "reqwest", "reqwest/stream", "chrono/serde", "base64", "rand", "ring", "http-body-util", "form_urlencoded", "serde_urlencoded"]
- closes #3397
=> refactor: make "cloud" feature in object_store optional

crates/core/src/operations/vacuum.rs, python/deltalake/_internal.pyi, python/deltalake/table.py, python/src/lib.rs
This allows an optional but not-on-by-default mode of removing untracked
files in the delta table directory. Delta/Spark supports a "lite" and
"full" mode for [vacuum]. This change is intentionally not making "full"
the default as it is for Delta/Spark since that may have unintended
consequences for our users who have become accustomed to "lite" being
the default.
Fixes #2349
Signed-off-by: R. Tyler Croy <rtyler@brokenco.de>
[vacuum]: https://docs.delta.io/latest/delta-utility.html#remove-files-no-longer-referenced-by-a-delta-table
=> feat: introduce VacuumMode::Full for cleaning up orphaned files

crates/core/src/delta_datafusion/mod.rs
When adding a constraint to a table, the expression is formatted as: `<FIELD> <CONDITION> <VALUE>`. If - god forbid - a space occurs in a field name, the condition will not evaluate due to the field name not being escaped. During the `enforce_check` we are unable to get the field name, and to avoid breaking backward, I am suggesting adding some logic to add backticks to conditions.
1. Get the table schema
2. Loop through schema and check if field exists
3. If field exists, escape with backticks
I am not fan of this solution myself, but I do not have a better solution at the moment.
=> fix: if field contains space in constraint expression, checks will fail

crates/catalog-unity/Cargo.toml, crates/catalog-unity/src/lib.rs
I was trying to build the `deltalake-catalog-unity` crate without the `datafusion` feature. Here is the command I used:
```bash
cargo build -p deltalake-catalog-unity --no-default-features --features "aws"
```
I encountered the following error.
```text
error[E0432]: unresolved import `datafusion_common`
--> crates/catalog-unity/src/lib.rs:10:5
|
10 | use datafusion_common::DataFusionError;
|     ^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `datafusion_common`
|
= help: if you wanted to use a crate named `datafusion_common`, use `cargo add datafusion_common` to add it to your `Cargo.toml`
For more information about this error, try `rustc --explain E0432`.
error: could not compile `deltalake-catalog-unity` (lib) due to 1 previous error
```
This PR fixes the build error.
N/A …
=> fix: build Unity Catalog crate without DataFusion

crates/core/src/operations/update.rs
- closes https://github.com/delta-io/delta-rs/issues/3414
=> fix: drop column update

Cargo.toml, crates/core/Cargo.toml
Bump foyer to v0.17.2 to prevent from wrong disk cache returned entry on key hash collision.
https://github.com/foyer-rs/foyer/pull/1004
=> chore(deps): bump foyer to v0.17.2 to prevent from wrong result

crates/lakefs/src/client.rs, crates/lakefs/src/execute.rs, crates/lakefs/src/logstore.rs, python/tests/test_lakefs.py
If a branch does not have any file changes, we no longer merge the branch to avoid empty commits.
- closes #3190 
N/A
=> feat: during LakeFS file operations, skip merge when 0 changes

crates/core/src/operations/merge/mod.rs, crates/core/src/operations/write/generated_columns.rs, crates/core/src/operations/write/mod.rs
Add a validation check that only runs if generated columns feature is enabled in the tablefeatures or writer version 5 is enabled
- closes #3180
=> feat: added a check for gc code to run

crates/catalog-unity/Cargo.toml, crates/core/Cargo.toml, crates/deltalake/Cargo.toml, crates/lakefs/Cargo.toml
only the crates which had changes since 0.26.1
=> chore: bump crate versions which are due for release

crates/aws/src/storage.rs, crates/aws/tests/integration_s3_dynamodb.rs, crates/azure/src/lib.rs, crates/catalog-unity/src/lib.rs, crates/core/src/logstore/config.rs, crates/core/src/logstore/factories.rs, crates/core/src/logstore/mod.rs, crates/core/src/logstore/storage/runtime.rs, crates/core/src/operations/convert_to_delta.rs, crates/core/src/table/builder.rs, crates/core/src/table/mod.rs, crates/gcp/src/lib.rs, crates/hdfs/src/lib.rs, crates/lakefs/src/execute.rs, crates/lakefs/src/logstore.rs, crates/lakefs/src/storage.rs, crates/mount/src/lib.rs
Using the superior spawn request connector over the deltaIOStoragebackend: https://github.com/apache/arrow-rs-object-store/pull/332/files#diff-3afe0961b5df6dc75c903371865daa9b80c8da3912c9b96df5b51613a5695335
Had to slightly refactor logstore_with and logstore_for to pass the StorageConfig around, which now can hold on the IORuntime directly, so that the `lakefs` integration and others can rebuild a new store with the same io_runtime
- closes https://github.com/delta-io/delta-rs/issues/3427
=> feat: spawn io with spawn service

crates/core/Cargo.toml, crates/core/src/kernel/models/actions.rs
Removes unsused code to read deletion vectors. THis functionality is implemented in delta-kernel and does not need to be replicated here.
=> chore: remove unused code and deps

crates/aws/src/lib.rs, crates/azure/src/lib.rs, crates/catalog-unity/src/lib.rs, crates/core/src/logstore/factories.rs, crates/core/src/logstore/mod.rs, crates/gcp/src/lib.rs, crates/hdfs/src/lib.rs, crates/lakefs/src/lib.rs, crates/mount/src/lib.rs
In preparation for adopting engine we rename same paramerters on the factory methods to be more specific. I.e. we distinguish in docs and names if one can expect an objectst store with a prefix applied, or one pointing at the storeage root.
=> refactor: more specific factory parameter names

crates/aws/src/lib.rs, crates/aws/src/logstore/default_logstore.rs, crates/aws/src/logstore/dynamodb_logstore.rs, crates/aws/tests/integration_s3_dynamodb.rs, crates/azure/src/lib.rs, crates/catalog-unity/src/lib.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/transaction/mod.rs, crates/core/src/logstore/default_logstore.rs, crates/core/src/logstore/factories.rs, crates/core/src/logstore/mod.rs, crates/core/src/operations/create.rs, crates/core/src/table/builder.rs, crates/core/src/table/mod.rs, crates/core/tests/integration_datafusion.rs, crates/gcp/src/lib.rs, crates/hdfs/src/lib.rs, crates/lakefs/src/execute.rs, crates/lakefs/src/lib.rs, crates/lakefs/src/logstore.rs, crates/mount/src/lib.rs
One last pre-factor before starting to use kernel on more actively in our codebase. In this PR we expose an `Engine` on `LogStore` as well as introduce a distinction between `prefixed_store` and `root_store` exposed on log store. This structure is far from ideal, but allowsd us to begin migration. As we progress there, we should see many opportunities to simplify the API surface again.
@ion-elgreco - there was a little bit more handlin needed on the lake fs integration, but I "think" this should work for now.
=> feat: expose kernel Engine on LogStore

crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/kernel/transaction/mod.rs, crates/core/src/lib.rs, crates/core/src/logstore/mod.rs, crates/core/src/operations/vacuum.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/table/mod.rs, crates/core/src/table/state.rs, crates/core/tests/checkpoint_writer.rs, crates/core/tests/command_filesystem_check.rs, crates/core/tests/command_restore.rs, crates/core/tests/eager_snapshot.rs, crates/core/tests/integration.rs, crates/core/tests/integration_checkpoint.rs, crates/test/src/lib.rs, crates/test/src/read.rs, python/src/lib.rs
Moving to kernel also means a significant change in our path handling. THus far we rely on object store's `Path`, often relative to the delta table root. In parctical terms this right now also hinders us from processing tables where data files are in different locations. More importantly though, kernel handles all path references as fully qualified URLs. As a pre-factor to further kernel adoption, we change the APIs for the internal `Snapshots` and `LogSegement` to use `LogStore`. `LogStore` carries a reference to the full table location and exposes a prefixed (to table root) as well as a non-prefixed `ObjectStore` along with kernels `Engine`. Tjis will allow us to have chanegs in functionality much more isolated in future PRs.
This PR does not change an processing logic, and just defers …
=> refactor: use LogStore in Snapshot / LogSegment APIs

.github/workflows/build.yml, crates/core/Cargo.toml, crates/core/src/kernel/transaction/application.rs, crates/core/src/operations/create.rs, crates/core/src/operations/restore.rs, crates/core/src/protocol/checkpoints.rs
turns out our CI shouldn't have let some things through since it wasn't running a default build of tests too
=> chore: ensuring default builds work without datafusion

crates/azure/Cargo.toml, crates/core/Cargo.toml, crates/core/src/kernel/snapshot/log_segment.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/kernel/transaction/conflict_checker.rs, crates/core/src/kernel/transaction/protocol.rs, crates/core/src/kernel/transaction/state.rs, crates/core/src/logstore/config.rs, crates/core/src/logstore/mod.rs, crates/core/src/table/state.rs
Delta kernel handles all paths as fully qualified URLs. As another step towards adopting kernel, we move the internal log processing to handle full paths, rather than paths relative to the table root.
=> refactor: use full paths in log processing

crates/catalog-unity/src/client/retry.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/logstore/config.rs, crates/core/src/logstore/storage/mod.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/test_utils/mod.rs, crates/test/src/utils.rs
On a mission to improve test coverage before the 1.0 release. Starting with storage config and object store registry. Also moving fixtures around a bit preparing for more testing ...
also includes one `cargo clippy`.
=> test: improve storage config testing

crates/core/src/delta_datafusion/expr.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/constraints.rs, crates/core/src/operations/write/mod.rs, python/tests/test_constraint.py
This reverts https://github.com/delta-io/delta-rs/pull/3374
The main issue was in the Display for SqlFormat, so when you would add constraints in delta-rs with backticks or quotes for columns with whitespaces, it wouldn't properly persist when it hits the metadata. The default display for `Expr::col` is to use the flat name, but we should always use `quoted_flat_name`
=> fix: constraint parsing, roundtripping

python/Cargo.toml, python/src/merge.rs, python/tests/test_conversion.py
The pre-casted schema was set in the table provider, but should be post casting. Als updating py for quick python release.
- closes https://github.com/delta-io/delta-rs/issues/3507
=> fix: setting wrong schema in table provider for `merge`

crates/core/src/delta_datafusion/mod.rs, python/Cargo.toml, python/src/datafusion.rs, python/src/lib.rs, python/src/merge.rs, python/src/writer.rs
A small step in making our datafusion module a bit more parse-able. The `LazyTableProvider` is not used in the core crate, but only in the python crate, thus moving it over there.
=> refactor: move LazyTableProvider into python crate

crates/core/src/kernel/arrow/engine_ext.rs, crates/core/src/kernel/arrow/mod.rs, crates/core/src/kernel/snapshot/log_data.rs
Adding some extension traits, that make working with delta kernel abstractions a little less verbose. mainly exposing apis in therms of `RecordBatch`es rather than `EngineData`.
=> feat: add convenience extension for kernel engine types

Cargo.toml, crates/core/src/kernel/arrow/engine_ext.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/table/config.rs
To simplify our stats schema computation a bit, we leverage the `SchemaTransform` pattern from kernel. This also allows us to compute the schema from our internal representation of the table configuration or the configuration exposed on kernel snapshots.
This is a pre-factor to handle stats as structs in our checkpointing.
=> refactor: compute stats schema with kernel types

Cargo.toml, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/snapshot/replay.rs, crates/core/src/operations/cast/mod.rs, crates/core/src/table/state_arrow.rs
This is part of updating DataFusion:
- https://github.com/delta-io/delta-rs/pull/3520
Let's first upgrade the arrow and parquet libraries independently
Brings in the fix for
- https://github.com/apache/arrow-rs/pull/7539
=> chore: update arrow/parquet to 55.2.0

crates/core/src/logstore/mod.rs, crates/core/src/table/mod.rs, crates/core/tests/time_travel.rs
Version search does not work if there are temporary parquet checkpoint files in the `_delta_log` folder.
The 2nd commit fixes a regression introduced in a recent commit that uses the kernel to look for max_version, which fails if the version doesn't start at 0 (rarely the case on an older table).
=> fix: version binary search

Cargo.toml
With the latest arrow upgrade we can jump up a version now
=> chore: upgrade to delta_kernel 0.12.x

python/deltalake/table.py
The Python library already exposes `create_checkpoint()`, but users don't know that since it isn't documented. This ensures the method shows up in the API docs.
=> docs: ensure create_checkpoint() is visible in the Python API docs

crates/mount/src/lib.rs
Fix a typo that is failing on CI on my PR: https://github.com/delta-io/delta-rs/pull/3603
Here is an example failure
- https://github.com/delta-io/delta-rs/actions/runs/16379294197/job/46286870241?pr=3603
```
Warning: "moutn" should be "mount".
Warning: "moutn" should be "mount".
error: `moutn` should be `mount`
--> ./crates/mount/src/lib.rs:45:13
|
45 |         let moutn_config =
|             ^^^^^
|
error: `moutn` should be `mount`
--> ./crates/mount/src/lib.rs:49:13
|
49 |             moutn_config
|             ^^^^^
```
- https://github.com/delta-io/delta-rs/pull/3603
=> fix: fix typo to fix CI typo check

crates/azure/tests/context.rs, docker-compose.yml, python/tests/test_fs.py
The azure integration tests have been failing and the best I can tell is
that it happened around the upgrade to object_store 0.12.0? Perhaps?
It's a little confusing.
Either way I could not find documentation on what ebhaviors are
supported for different Azure URL schemes, but noticed that `az://` was
changed in object_store 0.12. It's not clear to me _how_ the changes in
object_store would affect behavior but based on the logs I have observed
it seems like something about the az:// handling was dropping the
container name in the URLs.
rust-v0.25.0 (object_store 0.11.x):
```
azurite-1     | 172.19.0.1 - - [22/Jul/2025:18:15:19 +0000] "GET /devstoreaccount1/test-delta-table-1753208110/simple/_delta_log/_last_checkpoint HTTP/1.1" 404 -
azurite-1     | 172.19.0.1 - - [22/Jul/2025:18:15:19 …
```
=> fix: switch the url schemes for Azure integration tests

crates/core/src/kernel/schema/partitions.rs
make match_partitions and new_metadata public.
We're writing Metadata "actions" and use match_partitions to do column mapping partition filtering (at least until delta-rs fully supports column mapping)
=> refactor: make match_partitions and new_metadata public

python/deltalake/writer/_utils.py, python/src/lib.rs, python/tests/test_threaded.py
FREEZE!
Looks like we were _really_ close to full multi-threaded support before,
and just needed to sprinkle a little macro magic on the pyclass
definition.
See [pyo3 docs](https://pyo3.rs/v0.23.0/class/thread-safety)
Fixes #3594
=> fix: allow writing to DeltaTable objects across Python threads

.github/workflows/build.yml, Cargo.toml, crates/core/src/delta_datafusion/mod.rs, crates/core/src/operations/merge/barrier.rs, python/src/writer.rs
Update to DataFusion 49.0.0
- Related to https://github.com/apache/datafusion/issues/16235
- See https://datafusion.apache.org/library-user-guide/upgrading.html#datafusion-49-0-0
=> chore: update to DataFusion `49.0.0`

.github/workflows/docs.yml
Signed-off-by: R. Tyler Croy <rtyler@brokenco.de>
=> fix: make the docs link checking more useful/less faily

python/Cargo.toml
This commit was released as python-v1.1.3
=> chore: bump version for release

python/deltalake/_internal.pyi, python/deltalake/table.py, python/src/lib.rs, python/tests/test_vacuum.py
Update the `delta_table.vacuum` command to add a `keep_versions` argument to specify versions to retain when performing a vacuum operation.
Closes https://github.com/delta-io/delta-rs/issues/3634
See the underlying Rust feature: https://github.com/delta-io/delta-rs/pull/3537
=> feat: add keep_versions parameter to vacuum command for python

.github/workflows/python_build.yml, python/Makefile, python/pyproject.toml, python/tests/test_table_read.py, python/tests/test_threaded.py
The additional benefit of running these tests in parallel is that more
racey/timing related test failures are cropping up for me.
=> chore: use pytest-xdist for speeding up python tests

crates/aws/tests/integration_read.rs, crates/core/src/logstore/mod.rs
Removes special casing for handling some AWS paths. The fix in the PR is trivial, since we just remove the special casing and do the test setup the same way we do for azure and gcp.
However I am more than sure that we did try this before to no avail. So why is it working now? My best guess is that the source was somewhere in the test setup when uploading the files to localstack, and has been removed when @rtyler recently updated the localstack version in our test setup.
In any case I am happy we got rid of it 😆.
=> fix: aws special paths encoding

.github/workflows/build.yml, .github/workflows/python_build.yml
As we want to work more with topic branches, extending the ci triggers to run more meaningful CI when targeting topic branches.
Limiting to branches `next`, `next/*`.
=> ci: run integration tests against next branches

Cargo.toml, crates/core/Cargo.toml, crates/core/src/kernel/scalars.rs, python/pyproject.toml, python/tests/test_partition_encoding_rfc3896.py
Before when I addressed partition encoding I was using the URL encoding, where I naively assumed this was URI encoding compatible, but protocol states to use RFC3896 with additional stricter rules. I have used the percent-encoding-rfc3896 crate for this which forks the percent-encoding crate but adds some extra things to make it it RFC3896 compatible.
The ASCII set contains all reserved characters that need to be encoded according to the protocol
- fixes: #3577
@kdn36
=> fix: use RFC3896 percent encoding with delta protocol correctness

python/deltalake/writer/_conversion.py, python/deltalake/writer/writer.py, python/tests/test_conversion.py
This PR fixes type inconsistencies in Pandas DataFrames by implementing automatic conversion of `object` dtype columns containing null values into their correct schema-defined types (when available).
Previously, `object` dtype columns with `null` values could remain untyped, leading to mismatches with schema-defined types and causing validation or serialization errors.
Now, these columns are automatically converted, ensuring consistency between DataFrame values and the schema while reducing type-related issues.
- closes #3691
=> fix(pandas): implement-automatic-conversion-for-pandas-null-types

python/deltalake/writer/_conversion.py
Small Python formatting issue fixed in conversion file.
=> fix(format): fix formatting in Python for conversion file

.github/actions/setup-env/action.yml, .github/workflows/build.yml, .github/workflows/python_build.yml, .github/workflows/python_release.yml, .github/workflows/rust_release.yml
Integrate `rust-cache` to persist Rust build artifacts and dependencies across CI runs, removing the need for repeated downloads and recompilations of unchanged dependencies.
- https://github.com/Swatinem/rust-cache
=> chore(ci): cache rust dependencies in the CI

crates/core/src/operations/merge/mod.rs, crates/core/src/operations/write/mod.rs
`write_deltalake` with `mode="overwrite"` and `schema_mode=None` was overwriting the nullability constraints of various columns in the schema, instead of accepting the existing schema fully (or failing on drift, if there was actually schema drift besides column constraints).
Upon reflection of the `merge` operation, it turned out that worked as intended, but this PR still introduces a test to ensure the schema behavior is consistent between the two.
Closes #3744
N/A
=> fix: `write_deltalake` with `mode="overwrite"` mode and `schema_mode=None` does not overwrite schema metadata

.github/workflows/build.yml, Cargo.toml, crates/core/src/delta_datafusion/expr.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/kernel/scalars.rs, crates/core/src/operations/optimize.rs, python/Cargo.toml, python/src/datafusion.rs, python/src/writer.rs
- https://github.com/apache/datafusion/issues/16799
As part of preparing for the DataFusion 50 release I am making a PR to upgrade delta.rs
=> feat: update to DataFusion 50, pyo3 24, pyo3-arrow 0.11

crates/catalog-unity/src/lib.rs
Add `StorageConfig` when building `UnityCatalog` to allow catalog credentials.
- closes #3757
=> feat(unity-catalog): support credentials via storage options

.github/workflows/build.yml
Committed a fix upstream
[here](https://github.com/bnjbvr/cargo-machete/pull/199)
=> chore: pin cargo-machete action to the sha right before a regression

python/deltalake/table.py, python/tests/test_table_read.py
Currently, delta-rs does not have an option to get the number of rows for a specific table.
I want to get the number of rows from the delta log without reading the whole table to the RAM of my application.
The idea is to handle a row counter and iterate over the log in order to get the number.
[- closes #3731](https://github.com/delta-io/delta-rs/issues/3731)
=> feat: get the delta table row count based on the table history

python/tests/test_table_read.py
The check that caught this wasn't apparently "required" when I had refactored our repo rules a month or so ago.
I had also made this change locally, there might even be video evidence of it :smile: but I must not have correctly pushed it
=> fix: somehow the right test value didn't make it into the pr

crates/core/src/operations/optimize.rs
This allows passing a `SessionState` into an `OptimizeBuilder`, mirroring the other operation APIs. Very useful if running concurrent delta table operations in a kubernetes pod, as you can limit Datafusion to use a certain amount of ram between all shared contexts to prevent OOMs
Closes #3797, effectively reverts/supersedes #3751
=> feat: allow passing a `SessionState` into a `OptimizeBuilder`

crates/core/src/table/mod.rs
When creating a DeltaTable with new_from_state we should persist the `load_config` from the state also on the DeltaTable Struct, in reality this has no true effect because we **never** hit a code path of using the config from DeltaTable after we have `Some(DeltaTableState)` since we only look at the LoadConfig within the snapshot. The config on the DeltaTable struct is only used when creating the snapshot and then it's passed through it. After we have a snapshot, the config is only used from within there.
But this is more correct so lets prevent footguns in the future if we do for some reason look at the DeltaTable struct for the config.
@corwinjoy
=> fix: maintaining load config from state

.github/actions/setup-env/action.yml, .github/workflows/build.yml, .github/workflows/dev_pr.yml, .github/workflows/docs.yml, .github/workflows/integration.yml, .github/workflows/python_benchmark.yml, .github/workflows/python_build.yml, .github/workflows/python_release.yml, .github/workflows/rust_release.yml, .github/workflows/typos.yml
This is another attempt at making our CI a bit more pleasant to work with. The basic idea is - more smaller jobs as well as avoiding some redundant work.
we moved integration tests into their own job and streamlined the build job.
- `build/check`: fmt, clippy (with --test), docs, on linux only
- `build/build`: previous buid and check commands but without `--test`, all os
- `build/test`: unit tests on all os
In integration we now run a job for every crate that has integration tests. azure, aws, gcp, hdfs, lakefs
=> ci: split out integration tests

crates/core/src/operations/mod.rs, crates/core/src/operations/vacuum.rs, crates/core/src/table/state.rs, python/src/lib.rs
The vacuum operations was the last one still using `DeltaTableState`. Now that we have updated tombstone access, we can also migrate this one to use `EagerSnapshot`.
=> refactor: use EagerSnapshot in vacuum operation

crates/core/src/delta_datafusion/cdf/scan.rs, crates/core/src/delta_datafusion/expr.rs, crates/core/src/delta_datafusion/mod.rs, crates/core/src/delta_datafusion/table_provider.rs, crates/core/src/kernel/snapshot/iterators/scan_row.rs, crates/core/src/kernel/snapshot/mod.rs, crates/core/src/kernel/snapshot/serde.rs, crates/core/src/kernel/transaction/conflict_checker.rs, crates/core/src/operations/add_column.rs, crates/core/src/operations/create.rs, crates/core/src/operations/delete.rs, crates/core/src/operations/load.rs, crates/core/src/operations/load_cdf.rs, crates/core/src/operations/merge/mod.rs, crates/core/src/operations/optimize.rs, crates/core/src/operations/update.rs, crates/core/src/operations/write/execution.rs, crates/core/src/operations/write/mod.rs, crates/core/src/protocol/checkpoints.rs, crates/core/src/table/mod.rs, crates/core/src/table/state.rs, crates/core/src/writer/json.rs, python/src/lib.rs, python/src/query.rs, python/src/schema.rs
In many places we require the arrow schema of a snapshot. As such we replicate converting schemas in many places. In this PR we track a reference to an arrow schema on our innermost snapshot and start using it in some places.
We also now expose the kernel schema as an arc to better alogn with how delta kernel and datafusion expose schemas.
part-of: #3733
=> feat: expose arrow schema on snapshots
