- Cargo.lock
- python/Cargo.toml
- python/src/lib.rs
- ruby/Cargo.toml
- ruby/lib/deltalake.rb
- ruby/src/lib.rs
- rust/Cargo.toml
- rust/src/main.rs
- rust/tests/dataframe_test.rs
- rust/tests/datafusion_test.rs
- rust/tests/read_delta-0-2-0_test.rs
- rust/tests/read_simple_table_test.rs
This way all the native bindings are published as `deltalake` packages and
everything is consistently `deltalake`
> Rename APIs in the rust crate to `deltalake` for good symmetry

- Cargo.lock
- rust/Cargo.toml
- rust/src/delta.rs
Using parquet = "2" resulted in two versions of arrow being compiled; this thins out the dependency tree a bit.
> Update parquet dependency to match arrow/datafusion

- Cargo.lock
- TODO
- python/Cargo.toml
- python/src/lib.rs
- ruby/Cargo.toml
- ruby/src/lib.rs
- rust/Cargo.toml
- rust/src/bin/delta-inspect.rs
- rust/src/delta.rs
- rust/src/storage/azure.rs
- rust/src/storage/file.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3.rs
- rust/tests/azure_test.rs
- rust/tests/datafusion_test.rs
- rust/tests/read_delta-0-2-0_test.rs
- rust/tests/read_simple_table_test.rs
This PR makes the `StorageBackend` trait methods async (using `async_trait`), and changes the implementations for file/Azure/S3 to be async. The `list_obj` methods now returns a `Stream<Item = Result<ObjectMeta, StorageError>>` instead of an iterator.
This change ends up propagating all the way back to the main entrypoints, since those functions do quite a lot of IO to get data from the storage backend. Not 100% how that could affect the Python APIs yet - perhaps I should look into it before this is merged - but I thought it could be worth pushing this up as-is.
I don't have any way of testing this against S3 directly unfortunately; it would be good to get tests for a large number of objects to test the continuation token code.
> Asyncify APIs

- .github/workflows/python_release.yml
10.15 an 11.0 targets the same platform macosx_10_7, so we only need to
run release with 10.15.
> avoid duplicate mac os pypi release

- rust/src/storage/s3.rs
Addresses #42
Using Region::default() instead of a specific hard coded region.
This will allow the user to set the region using one of AWS' config files **HOWEVER** the region (as far as I understand) is irrelevant when working with s3:// URI's and buckets in general because their names are globally unique.
> use default region for S3StorageBackend (#42)

- .github/workflows/python_release.yml
upstream release have caught up on my patches, this should speed up release pipeline
> release python binding with maturin 0.9.0 release

- rust/tests/s3_test.rs
I have synced the golden data set from the connectors.git repository to the
Azure and S3 storage containers we're using for our integration tests:
Synced at 4fd7f370b53b99b5aa91b384d1dcf13a123d37ea
cd connectors/golden-tables/src/test/resources/golden
rclone sync . deltars:deltars/golden
rclone sync .  deltars-azure:golden
This of course relies on a local rclone configuration on my machine with write
access :smile_cat:
I trust that @houqp and @nevi-me can do more interesting tests with this data
Fixes #55
> Add a simple integration test which relies on the golden data set in S3

- rust/src/delta.rs
Refactoring of trailing slash in `table_path`
> Refactoring - trailing slash in table_path

- rust/src/delta.rs
Missing refactoring for `get_files_path` method @houqp
> Refactoring get_file_paths with storage_backend

- rust/Cargo.toml
- rust/tests/s3_test.rs
As described in https://github.com/delta-io/delta-rs/issues/82, it looks like the shared rusoto hyper client singleton is breaking our tests. Ultimately, the shared hyper client used by rusoto _may_ cause many other problems for delta-rs use cases, but this PR is intended to just fix CI for now.
Solution implemented is to use [serial_test](https://github.com/palfrey/serial_test) to serialize s3_test functions only without requiring the entire delta-rs suite to be ran serially.
Tested many times locally and all outputs look as below (pass, pass, pass):
```
cargo test --test s3_test                                                                                                                           christianw at C02Y104ZJGH8 (--)(issue-82/s3_test_workaround)
Finished test [unoptimized + …
```
> [ISSUE-82] Add serial to handle concurrent s3 test execution

- python/deltalake/schema.py
- python/tests/test_schema.py
- python/tests/test_table_read.py
- rust/tests/delta_arrow_test.rs
- The method `type_for_alias()` of pyarrow is not available for the decimal type, I changed the conversion by creating the decimal128 type directly
- Add test on the decimal conversion for arrow schema
> Fix the decimal type in Python schema.

- python/Cargo.toml
cut a new release to include the new schema method.
> bump python binding version for 0.3.0 release

- rust/src/storage/mod.rs
- rust/tests/s3_test.rs
Fixes #103.
In upstream issue users report that GET does not return `GetObjectError::NoSuchKey`, however that wan't the case for me when I tested it. It makes sense this to be reproducible only for HEAD calls, since rusoto has shared parsers for both which parses response body, however there's none for HEAD. Hence, response code is used to determine Not Found response
> Add proper StorageError::NotFound error handling for s3 HEAD request

- rust/src/storage/mod.rs
- rust/src/storage/s3.rs
Blocked by #104
Adds simple (non-atomic) _put object if not exists_ (similar to file backend) implementation for S3
> Implement put_obj for S3 backend

- python/src/lib.rs
- rust/src/delta.rs
- rust/src/delta_arrow.rs
- rust/src/delta_datafusion.rs
- rust/tests/delta_arrow_test.rs
- rust/tests/write_exploration.rs
Refactoring of ArrowSchema, using `TryForm` trait and raise an `ArrowError` when there is an error in the conversion of the Schema.
Related to the issue: #93
> Refactoring of ArrowSchema conversion

- .github/workflows/pull_request_template.md
It could be interesting to have a PR template in the repository when people are creating a PR.
The template may contain description, issue-related, documentation, or conventions...
WDYT @houqp @rtyler?
> Add a PR template into the repository

- python/deltalake/schema.py
- python/deltalake/table.py
- python/tests/test_schema.py
- This PR keeps the `json_schema` returned by Rust in the `Schema` Python binding object
- It provides the functionality to create a StructType PySpark structure using JSON format without having the `pyspark[sql] `dependency in delta-rs
https://spark.apache.org/docs/3.0.1/api/python/pyspark.sql.html#pyspark.sql.types.StructType.fromJson
> Add json_schema field in Schema Python binding

- Cargo.lock
- python/Cargo.toml
- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_table_read.py
Add optional version argument to python binding init method. Also bump version to prep for release.
> python: support open table by version

- rust/README.md
Add crates.io and api doc link to rust workspace readme.
> add crates.io and api doc link to rust workspace readme

- python/deltalake/schema.py
- python/tests/test_schema.py
Fix the `json()` method in Python binding 
#121
> Fix json method in Python binding

- rust/src/delta.rs
This prevents duplicate loading of already loaded checkpoints, and
replaying json despite a newer checkpoint being available.
closes #123 
The behavior has been tested using the approach discussed in #123.
1. start: 5 commits `createCommits(5, "<some delta path>")`
```
reading delta table: "<some path>"
[apply_logs_after_current_version] applied 0
[apply_logs_after_current_version] applied 1
[apply_logs_after_current_version] applied 2
[apply_logs_after_current_version] applied 3
[apply_logs_after_current_version] applied 4
[apply_logs_after_current_version] end of log : 5, rollback
initial table loaded, version 4
waiting on keypress for update, current version 4
```
2. 4 more commits: no checkpoints yet
```
updating ...
[update] process started
[update] no previous checkpoint, trying …
```
> Fix update logic.

- rust/src/storage/s3.rs
The `S3Client` in Rusoto crate, for the S3 storage, should use the standard AWS Tool Chain using the `ChainProvider`. 
The `rusoto_core::ChainProvider` is a convenience for attempting to source access credentials using all the methods in the same order as AWS tools.
The provider has a default timeout of 30 seconds. We can reduce if we want:
```
let mut provider = ChainProvider::new();
// you can overwrite the default timeout like this:
provider.set_timeout(Duration::from_secs(60));
```
https://github.com/rusoto/rusoto/blob/master/AWS-CREDENTIALS.md
> Add ChainProvider for AWS S3Client

- Cargo.lock
- rust/Cargo.toml
- rust/src/storage/s3.rs
The standard `ChainProvider` used in `rusoto` does not support credentials from a web token file by default. This authentication method is only relevant in the context of the `S3StorageBackend` and when running the client libraries in pods on EKS (that themselves are attached to Service Accounts with relevant IAM roles). 
I've tested this change on an actual cluster and it works. 
* `WebIdentityProvider`: https://docs.rs/rusoto_sts/0.45.0/rusoto_sts/struct.WebIdentityProvider.html
> Support EKS(K8s) service account authentication for S3 backend

- rust/src/action.rs
This is a very small PR to add a `StreamingUpdate` enum variant to `DeltaOperation` so it may be passed by writers committing a `DeltaTransaction`.
This PR relates to, but does not actually implement any part of https://github.com/delta-io/delta-rs/issues/133. However, the `DeltaOperation` parameters are the most interesting part of `commitInfo`. The `StreamingUpdate` enum variant is needed so that github.com/delta-io/kafka-delta-ingest may pass this operation when committing delta transactions.
* Commit Provenance section in [protocol doc](https://github.com/delta-io/delta/blob/331c2af50dc3a2746f72f58cb896a5459caebff1/PROTOCOL.md#commit-provenance-information)
* Commit info and operation serialization in [reference implementation](https://github.com/delta-io/delta/blob/331c2af50dc3a2746f7 …
> Add StreamingUpdate operation enum variant.

- rust/src/delta_arrow.rs
This fixes an incorrect schema mapping for `timestamp` from delta to arrow
The protocol talks about timestamp being a microsecond precision value with no time zone. The Arrow `Time64` only stores the time portion of a timestamp, so the mapping was incorrect.
> Fix Delta <> Arrow schema timestamp

- .github/workflows/ruby_build.yml
- Cargo.lock
- ruby/Cargo.toml
- ruby/Gemfile
- ruby/Rakefile
- ruby/lib/deltalake.rb
- ruby/lib/deltalake/version.rb
- ruby/spec/deltalake_spec.rb
- ruby/src/lib.rs
Change Ruby bindings from the deprecated [helix](https://github.com/tildeio/helix) to [rutie](https://github.com/danielpclark/rutie).
- Resolves #20 
To build and test the bindings:
```
cd ruby
cargo build --release
rake spec
```
The only concern to make the test work and possibly deployment is the required `lib_path` option of `../../target/release` which is hardcoded. 
```ruby
module Deltalake 
Rutie.new(:deltalake_ruby, lib_path: '../../target/release').init 'Init_table', __dir__
end
```
> Migrate Ruby bindings from helix to rutie

- .github/workflows/build.yml
- Cargo.lock
- python/Cargo.toml
- rust/Cargo.toml
- rust/src/delta.rs
- rust/src/storage/file/mod.rs
- rust/src/storage/file/rename.rs
- rust/src/storage/mod.rs
Fix windows build, which was blocking us from releasing a windows
python client. Added mac and window build to the build matrix.
Also move rename temp file clean up logic into put_obj method in
preparation for moving the temp file creation logic into optimistic
delta commit loop. See https://github.com/delta-io/delta-rs/issues/135.
> fix windows build

- .github/workflows/python_build.yml
- Cargo.lock
- Cargo.toml
- glibc_version/Cargo.toml
- glibc_version/src/lib.rs
- rust/Cargo.toml
- rust/build.rs
- rust/src/storage/file/rename.rs
Avoid linking to renameat2 glibc symbol for old glibc versions. This should unblock python release. Delta write is not supported in python at the moment, so this should have no impact to python users.
Will add workarounds for old glibc and linux kernel in a separate follow up PR.
close #145 and #146.
> Fix python releases

- python/deltalake/schema.py
- python/tests/test_schema.py
In the python library, I noticed that the schemas of nested delta tables are not being built correctly by `Schema.from_json`.  For example this JSON Spark schema with an array field (which is in the test case I've added)
```json
{
"type": "struct",
"fields": [
{
"name": "x",
"type": {
"type": "array",
"elementType": "long",
"containsNull": true
},
"nullable": true,
"metadata": {}
}
]
}
```
is translated to this Schema
```python
Schema(Field("x", DataType({"type": "array", "elementType": "long", "containsNull": True}), True, {})
```
When I believe the correct result should be
```python
Schema(Field("x", ArrayType(DataType("long"), True), True, {}))
```
> Ensure that Schema.from_json builds all DataTypes correctly

- Cargo.lock
- rust/src/storage/file/rename.rs
Tries to use renameat2 exported from latest libc crate fixed in [rust-lang/libc#2116](https://github.com/rust-lang/libc/pull/2116/files) (as mentioned in [comment](https://github.com/delta-io/delta-rs/pull/140/files/98c1d9181249f83790719ad28ccb33ecbdb4cd74#r598330852)).
closes #143
> Use renameat2 symbol exported from official libc crate

- rust/src/storage/s3.rs
S3 compatible services like minio and localstack need to be accessed by setting a custom endpoint url. This PR adds support for setting the endpoint url through `AWS_ENDPOINT_URL` env var. The env var name is picked based on aws cli argument `--endpoint-url`.
- closes #163
> support custom endpoint url for S3 backend

- .github/workflows/build.yml
- .github/workflows/python_build.yml
- Cargo.lock
- Cargo.toml
- python/tests/test_table_read.py
- rust/build.rs
This should make non-integration test related CI failure easier to catch. Breaking up CI into finer grain parallel jobs should also speed up the pipeline.
> separate integration tests from the rest of CI pipeline

- .github/workflows/python_build.yml
- python/Cargo.toml
Add a coverage report for the CI on the test coverage 
```
---------- coverage: platform linux, python 3.6.12-final-0 -----------
Name                       Stmts   Miss  Cover
----------------------------------------------
tests/conftest.py              6      3    50%
tests/test_schema.py         109      0   100%
tests/test_table_read.py      71     23    68%
tests/test_version.py          4      0   100%
----------------------------------------------
> TOTAL                        190     26    86%
```
> Add pytest coverage plugin

- rust/src/storage/file/rename.rs
> Don't rely on env::tmp_dir() which may be on a different device for this test

- .github/workflows/python_build.yml
The upstream action is not well maintained and implemented, it's better/faster to just install black from pip manually.
> fix python binding black lint

- .github/workflows/build.yml
- Cargo.lock
- build/setup_localstack.sh
- docker-compose.yml
- rust/Cargo.toml
- rust/src/lib.rs
- rust/src/storage/s3/dynamodb.rs
- rust/src/storage/s3/dynamodb_lock.rs
- rust/src/storage/s3/mod.rs
- rust/tests/dynamodb_test.rs
This PR adds dynamo distributive lock ported from https://github.com/awslabs/amazon-dynamodb-lock-client
Note that not every feature is ported from java lock client to easy the integration. 
In addition, this port also introduces additional feature, it is the extending a timeout duration on each time exiting lock changes its rvn. Meaning that there's other clients trying to acquire a lock and they were more successful, so instead retuning  None (due to timeout as in original java version) this implementation extends the wait duration by adding another `lease_duration` to the try acquire loop.
> Add dynamodb lock implementation

- .github/workflows/python_build.yml
- python/.gitignore
- python/Cargo.toml
- python/README.md
- python/deltalake/schema.py
- python/deltalake/table.py
- python/docs/Makefile
- python/docs/make.bat
- python/docs/source/_ext/edit_on_github.py
- python/docs/source/_static/.gitignore
- python/docs/source/api_reference.rst
- python/docs/source/conf.py
- python/docs/source/index.rst
- python/docs/source/installation.rst
- python/docs/source/usage.rst
- rust/tests/s3_test.rs
The Sphinx documentation is applied to the docstrings used in the Python code.
The typing of Python is also used for detecting the types of parameters inside the functions.
- closes #154 
We could link Github with the Read the Docs page but I don't have the permissions 😃 
> Quickstart for GitHub-Hosted Projects
> By the end of this quickstart, you will have a new project automatically updated when you push to GitHub.
> 
> Create an account on Read the Docs. You will get an email verifying your email address which you should accept within 7 days.
> Log in and click on "Import a Project".
> Click "Connect to GitHub" in order to connect your account's repositories to GitHub.
> When prompted on GitHub, give access to your account.
> Click "Import a Repository" and select any desired …
> Add Sphinx documentation for the Python bindings

- .gitignore
- tlaplus/README.md
- tlaplus/dynamodblock.tla
- tlaplus/dynamodblock.toolbox/.project
- tlaplus/dynamodblock.toolbox/.settings/org.lamport.tla.toolbox.prefs
- tlaplus/dynamodblock.toolbox/dynamodblock___fast_dev.launch
- tlaplus/dynamodblock.toolbox/dynamodblock___full_tiimeless.launch
Spec is model checked without pause and crash.
Adding crash and pause to the modeling requires enabling timer in the
spec (i.e. setting TIME_TICK_UNIT > 0). This will fail the model check
because lock with expiration cannot gurantee correctness without use of
fenching token.
> tla+ spec for dynamodb lock

- rust/src/delta_arrow.rs
The default timestamp type for parquet files is INT96, which is with nanosecond precision
- https://github.com/delta-io/delta/issues/643
> Change the default timestamp to nanosecond precision for Delta <> Arrow schema

- python/deltalake/schema.py
- python/tests/test_schema.py
Add the missing `floatingpoint` pyarrow data type inside the Python bindings
- closes #192
> Add pyarrow floatingpoint in Python bindings

- python/deltalake/__init__.py
- python/deltalake/table.py
- python/docs/source/usage.rst
- python/src/lib.rs
- python/tests/test_table_read.py
Add the metadata in the Python bindings.
Metadata:
- id
- name
- description
- configuration
- partition_columns
- closes #190
> Add Metadata in Python bindings

- python/Cargo.toml
Bump Python bindings version to v0.4.6
> Bump Python bindings version to v0.4.6

- rust/src/delta.rs
This is a drive-by fix.
I encountered a bug when using the delta txn version from kafka-delta-ingest. The prior `process_action` implementation does not update the existing map entry for tx version when re-processing actions. This change resolves that.
> Update app tx version when processing action

- Cargo.lock
- build/setup_localstack.sh
- docker-compose.yml
- rust/src/delta.rs
- rust/src/storage/azure.rs
- rust/src/storage/file/mod.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
- rust/tests/simple_commit_test.rs
Before introducing S3 locking we need to match its behaviour with filesystem backend. 
Also, temporary files are now created before commit loop, to avoid unnecessary creation of tmp files at each try. 
I've also made simple_commit to be tested against s3 backend, so with these we have first s3 writer test
> Unify s3 and fs try_commit behavior

- Cargo.lock
- python/Cargo.toml
- rust/Cargo.toml
- rust/src/delta_datafusion.rs
- rust/tests/datafusion_test.rs
This updates the arrow deps to the latest commit (https://github.com/apache/arrow/commit/9c1e5bd19347635ea9f373bcf93f2cea0231d50a). 
There's the following changes:
* `TableProvider` signature in datafusion now takes a limit
* Parquet writer returns statistics (more relevant for kafka-delta-ingest)
No changes
> Update arrow deps

- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_table_read.py
- rust/src/delta.rs
- rust/tests/read_delta_test.rs
Add a Vacuum dry run command for listing files no longer referenced by a Delta table and are older than the retention threshold.
https://docs.delta.io/0.8.0/delta-utility.html#remove-files-no-longer-referenced-by-a-delta-table
> Add dry_run vacuum command

- python/Cargo.toml
- python/deltalake/schema.py
- python/deltalake/table.py
This allows the use of minio or localstack for the Python bindings
Reviewed live via Jitsi with @houqp
None filed yet
The use of `AWS_ENDPOINT_URL` is not [yet conventional](https://github.com/aws/aws-cli/issues/1270#issuecomment-301625262) by the `aws` CLI, but we're already relying on this in the Rust code specifically. :shrug:
> Accommodate AWS_ENDPOINT_URL in the python binding to allow alternatives to S3

- rust/tests/dynamodb_test.rs
- rust/tests/s3_common/mod.rs
- rust/tests/s3_test.rs
- rust/tests/simple_commit_test.rs
Fixes #176
For integration tests, cargo executes each test file within its own crate, so in order to declare common code which has to be used among different test one should create it under directory with mod.rs file. This will not be acknowledged as test file and hence could be reused in other tests.
More here https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests.
> Add common setup envs code for S3 tests

- python/Cargo.toml
The version of pyarrow must be >= 4 for the Python bindings
#218
> Bump the version of pyarrow needed for Python bindings

- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_table_read.py
- rust/src/delta.rs
- rust/tests/read_delta_test.rs
Add Vacuum on the Delta table
#97
> Add Vacuum command in DeltaTable

- rust/src/delta_arrow.rs
When converting delta array type to arrow list, the arrow list should have a name in its field.
Spark and Parquet use "element" as the field name, thus I have used that.
None
"element" comes from https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#nested-types
> add "element" as the arrow list field name

- python/deltalake/schema.py
- python/tests/test_schema.py
Add Date, StructArray and Map for Pyarrow types in Python schema
closes #217
> Add Date, StructArray and Map for Pyarrow types in Python schema bindings

- rust/src/storage/azure.rs
- rust/src/storage/file/mod.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
This makes `BackendStorage::list_objs` to be `Send + Sync` so that `BackendStorage` can play nice with other tokio streams.
Closes #230
None
> Make streams impl send

- rust/Cargo.toml
Fix the follow publish error:
```
error: api errors (status 200 OK): wildcard (`*`) dependency constraints are not allowed on crates.io. See https://doc.rust-lang.org/cargo/faq.html#can-libraries-use--as-a-version-for-their-dependencies for more information
```
> avoid wildcard dependency constraint to unblock crates.io release

- .github/workflows/ruby_build.yml
This should reduce ruby build time.
> avoid python build for ruby ci/cd pipeline

- rust/README.md
always point doc link to the latest version.
> update rust doc link in readme

- rust/src/delta.rs
- rust/tests/read_delta_test.rs
- rust/tests/read_simple_table_test.rs
Fairly straightforward implementation and integration test to allow Rust binding users to get fully-qualified file paths for the specified partitions.
Fixes #222
> Implement get_file_paths_by_partitions

- python/src/lib.rs
- ruby/src/lib.rs
- rust/Cargo.toml
- rust/src/action.rs
- rust/src/delta.rs
- rust/tests/azure_test.rs
- rust/tests/read_delta_test.rs
- rust/tests/read_simple_table_test.rs
- rust/tests/s3_test.rs
This change will refactors `DeltaTableState` to carry out the `Add` struct from the action module, this will allow the `DeltaTable` or `DeltaTableState` structs to expose stats more readily to their consumers.
Todo #45
> Exposing file stats

- rust/src/delta.rs
- rust/tests/simple_commit_test.rs
This PR adds a `commit_version` method to `DeltaTransaction` which takes a version parameter from the caller. 
Some clients (i.e. https://github.com/delta-io/kafka-delta-ingest) include `txn` actions when creating delta log entries that may require additional conflict resolution with external systems before incrementing the delta log version. The `commit_version` method propagates version conflict errors back to the caller immediately so they may apply conflict resolution steps before attempting another commit.
This PR is complete - but leaving it in a draft status per @rtyler's [notice](https://delta-users.slack.com/archives/C013LCAEB98/p1621350036003900) that we may preemptively avoid some conflicts by incorporating this into [his PR](https://github.com/delta-io/delta-rs/pull/248).
> Add commit_version method to DeltaTransaction

- Cargo.lock
- rust/.ignore
- rust/Cargo.toml
- rust/src/delta.rs
- rust/src/lib.rs
- rust/src/writer.rs
- rust/tests/concurrent_writes_test.rs
- rust/tests/simple_commit_test.rs
- rust/tests/write_exploration.rs
This pull request is a work in progress, pending more complete riffing on the [deltalake_ext.rs](https://github.com/delta-io/kafka-delta-ingest/blob/main/src/deltalake_ext.rs).
The objective here is that the primitive API will just handle writing some bytes to storage and the subsequent `add` transaction, whereas the high-level writer API will manage buffering of rows for a parquet file.
> Adding a primitive and high-level writer interface

- .github/workflows/rust_release.yml
Whenever a tag `rust-vx.y.z` (like `rust-v0.4.0`) is pushed, this workflow will publish via `cargo publish`.
GitHub Secrets configuration:
- `CARGO_REPOSITORY_TOKEN` - Token used in `cargo login`
**BLOCKER: Since `cargo publish` requires all dependencies to be published, this will fail until [azure-sdk-for-rust](https://github.com/Azure/azure-sdk-for-rust) is stable or released.**
Also, I noticed in the `rust-v3.0.0/rust/Cargo.lock` file that `azure_core` and `azure_storage` is commented so this seems acknowledged:
```toml
```
We could create another `Cargo.release.toml` to hide the `azure` dependencies for the meantime but seems unfulfilling.
- closes #238 
Links:
- https://doc.rust-lang.org/cargo/reference/publishing.html#github-permissions
- https://github.com/katyo/publish-crates
> Add initial Rust release CI 

- .github/workflows/python_release.yml
Grant commit access to `release-docs` job
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#modifying-the-permissions-for-the-github_token
https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-contents
> fix python doc release

- rust/Cargo.toml
renameat2 is only available starting in libc 0.2.90
> fix libc constraints to pull in renameat2 symbol

- .github/workflows/build.yml
- Cargo.lock
- python/Cargo.toml
- rust/Cargo.toml
- rust/README.md
This allows clients to use rustls or native-tls. In my case I need to use rustls
so that I can build Lambdas more easily
> Disable default features for rusoto

- rust/src/delta.rs
- rust/tests/read_error_test.rs
This commit updates NotATable to provide some more useful user-facing error
information.
* #267
> Add a simple error message for NotATable

- rust/src/delta.rs
The current parquet filename is appended with partition values, e.g. `part-0000-xxxx-c000.snappy.parquet/part1=value1/part2=value2`. Seems it doesn't follow existing conventions as `part1=value1/part2=value2/...` .
> Fix generated parquet filename

- rust/src/delta.rs
Newly added test `parquet_filename` failed on windows-2019 CI:
---- delta::tests::parquet_filename stdout ----
thread 'delta::tests::parquet_filename' panicked at 'assertion failed: parquet_filename.contains(\"col1=a/col2=b/part-00000-\")', rust\src\delta.rs:1610:9
This tries to fix it.
> Fix path check of parquet_filename

- python/deltalake/table.py
- python/tests/test_table_read.py
Many users that work in Python use pandas in their daily work. Adding a `.to_pandas` method makes it super easy for users to read in a Delta table into a pandas dataframe. 
-
- Added documentation to the `.to_pandas` method. Will update the docs if the proposed change looks fine.
> Added .to_pandas to deltalake python

- .github/workflows/build.yml
- docker-compose.yml
- rust/src/storage/s3/dynamodb_lock.rs
- rust/src/storage/s3/mod.rs
- rust/tests/dynamodb_lock_test.rs
This PR brings the support of non-expirable locks. Such behaviour might be desired by external systems which interact with concurrent writer, e.g. in order to pause them etc. However there's the risk of delta-rs writer might expire such lock. With these changes, when the active lock has lease_duration as None, then the lock client treats such lock as non expirable and will not expire it. 
I've also introduced an optional `do_not_timeout_on_non_expirable_locks` config with default to `true`. If `true` then the acquire lock function will not fail with timeout when its reached so (the timeout is config's `lease_duration` + `additional_time_to_wait_for_lock`)
> Make dynamodb lease_duration optional to support non-expirable locks

- rust/src/storage/s3/mod.rs
- rust/tests/repair_s3_rename_test.rs
Make `LockClient` optional in `S3StorageBackend::new_with(S3Client,Box<dyn LockClient>)`
None
> [feat] optional lock when creating custom S3 backend

- rust/src/delta.rs
- rust/tests/simple_commit_test.rs
This PR brings low-level transaction API into public. Once it's merged we'll end up with 3 ways of writing data into delta:
1. Low-level transaction API: The `prepare_commit` and `try_commit` function. First creates the temporary file and second is trying to rename it with given version. That's what is going to be used by kafka-delta-ingest. Users of this will have to handle the commit loop by themself
2. High-level transaction API: The `commit` function. It actually reuses the API above and provide it's own commit loop.
3. Wirter API in the `writer.rs`.
We had to get rid of `commit_version` as it's produced a unhandled temporary file in case of commit conflict. Moreover, since the user didn't have the control over the temp file, it's been created on each try. With new API, having the …
> Remove commit_version in favor of public prepare_commit/try_commit transaction API

- rust/src/delta.rs
- rust/src/delta_datafusion.rs
- rust/tests/data/delta-0.8.0/_delta_log/00000000000000000000.json
- rust/tests/data/delta-0.8.0/_delta_log/00000000000000000001.json
- rust/tests/read_delta_test.rs
This starts using the provided metadata in delta transactions for the table provider, instead of the rowgroup.
This can be much faster, especially for a large number of files.
This also adds some integration testing against a delta dataset.
This exposes the file statistics of the files in a table.
Closes #247
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file
> Expose delta statistics as utility function #306, start using statistics for Datafusion `TableProvider` 

- Cargo.lock
- rust/Cargo.toml
- rust/src/delta_datafusion.rs
- rust/tests/datafusion_test.rs
Adds implementation of `statistics` to table provider to return total number of rows.
This helps in applying cost-based optimization (join reordering), and optimization with a direct  `COUNT(*)`.
I also removed the unneeded crossbeam dependency.
> DataFusion: Expose, calculate number of records in TableProvider

- rust/src/delta.rs
The `get_latest_version` method looks incorrect to me, by comparing with the logic in other latest version related methods.
The correct logic looks like to be: 1. get last check point version from `get_last_checkpoint`. 2. try to load log with `version = version + 1` until failing to load one and the the latest version is `version = version - 1`.
> Fix incorrect latest version

- rust/src/delta.rs
Not sure that that fully "fixes" the #128, but that's still the improvement, especially for writes, as you don't load checkpoints on each write/retry.
Also note attention to the function rename `apply_logs_after_current_version` -> `apply_logs_from_current_version`. I found after misleading as it's first applies the current version and then increments. That was not acceptable for update_incremental function since the current version is already applied. Hence, without creating any new wheels I figured to reuse that function but then, within update_incremental, I'm incrementing the table version so the next one will be applied. There's the case when  there's no new version after current, but `apply_logs_from_current_version` already handles that by reverting the version to one back so we're …
> Introduce update_incremental

- rust/src/storage/file/mod.rs
This PR addresses a bug I discovered in the FileStorageBackend. The `put_obj` implementation was calling `File::write` which does not write the full byte buffer. Changed to call `write_all`.
N/A
* https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all
* https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write
> Update file storage backend to write _all_ bytes from the passed buffer.

- rust/src/delta.rs
- rust/src/delta_datafusion.rs
`get_actions` might give reader the wrong impression that it will return all action variants.
Follow up on https://github.com/delta-io/delta-rs/pull/321.
> rename get_actions to get_active_add_actions

- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
Thank you for all the awesome work on this crate!
This is a small fix for getting `WebIdentityProvider` credentials for the DynamoDb lock client via service account in k8s. Essentially just a copy of what was already being done for the S3 client, but I have folded the logic into a separate function for code reuse. I have successfully tested this in cluster as well.
Essentially #132 for DynamoDb
`WebIdentityProvider`: https://docs.rs/rusoto_sts/0.45.0/rusoto_sts/struct.WebIdentityProvider.html
> Use WebIdentityProvider for DynamoDb client in k8s

- .github/workflows/rust_release.yml
Pass crates.io token through `--token` argument.
> fix automated rust release CD job

- python/Cargo.toml
- python/README.md
* add pandas keyword to python package metadata
* add document url
closes https://github.com/delta-io/delta-rs/issues/282
> add pandas keyword to python package metadata

- rust/build.rs
Added a warning message to assist in debugging since atomic renames has only been implemented for glibc version >= 2.28
> added warning message if the detected glibc version is < 2.28

- rust/src/delta_datafusion.rs
- rust/tests/datafusion_test.rs
This is a follow up of #327 for the comment https://github.com/delta-io/delta-rs/pull/327#discussion_r672030078.
For the max/min column scalar values, we convert it to correct `ScarlarValue` based on arrow datatype.
> Convert scalar value to correct type based on arrow data type.

- rust/src/checkpoints.rs
- rust/src/storage/file/mod.rs
- rust/tests/checkpoint_writer_test.rs
Some of the code within `checkpoint_add_from_state` is not executed because of excessive check. This PR fixes it.
UPD. This is dependent on map support, so keeping this as DRAFT until the former is merged
> Fix consecutive checkpoints

- rust/src/action.rs
- rust/src/delta.rs
- rust/src/schema.rs
This is the current implementation for a low level create table api
- I think the new() method for DeltaTableMetaData needs to take in format (just defaulted to parquet to get things working)
- I think the create() method should return an updated version of the DeltaTable instead of nothing at the moment
> Low level create table

- .gitignore
- rust/src/delta.rs
Added the table level API to get the current_metadata table configuration
- closes #353
> pub DeltaTable method to retrieve table configurations

- rust/src/storage/file/mod.rs
- rust/src/storage/mod.rs
- rust/tests/checkpoint_writer_test.rs
Our file storage backend `put_obj` implementation is not correct because it could result in partial write being visible to readers.
This change fixes partial read for non-concurrent readers. To properly support concurrent readers, we need to write to a temp location first, then follow by an atomic rename. Filed https://github.com/delta-io/delta-rs/issues/361 as follow up.
> fix sleep workaround in checkpoint test

- rust/src/delta.rs
- rust/tests/read_error_test.rs
Fix an edge case in get_latest_version.
- closes #312
> Fix get_latest_version returning version < 0.

- rust/src/delta.rs
Currently the temp prepared commit file has ending `.json` which is the same as for the actual commits. This makes it impossible to add filters/listeners in S3. 
Adding the `.tmp` so it's `_commit_{uuid}.json.tmp` now
> Add '.tmp' suffix to temporary file of prepared commit

- python/deltalake/table.py
- rust/src/checkpoints.rs
- rust/src/delta_arrow.rs
support partition value string deserialization for float/double/date
related to https://github.com/delta-io/delta-rs/issues/357
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#partition-value-serialization
> support partition value string deserialization for float/double/date

- rust/src/storage/file/mod.rs
Use write and rename file to implement atomic put_obj in fs backend.
- closes #361 
- closes #368
> Implement atomic put_obj.

- rust/src/action.rs
Format.options is required field, see https://github.com/delta-io/delta/blob/eab445a15f478ed2454cf152edb795e9fece91f6/core/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala#L358-L360
> Make Format.options to be required field

- rust/src/storage/file/mod.rs
- rust/src/storage/file/rename.rs
A follow up of https://github.com/delta-io/delta-rs/pull/367. `put_obj` has to follow the semantic of replace existing which was violated with recent changes. There's atomic swap supported by additional flags of `rename2` but it only works if both files are present. As a workaround I'm adding a files_exists() call to determine which rename to call.
> Allow filesystem backend put_obj to overwrite existing

- Cargo.lock
- python/Cargo.toml
- rust/Cargo.toml
- rust/src/checkpoints.rs
- rust/src/delta_arrow.rs
- rust/src/writer.rs
- rust/tests/checkpoint_writer_test.rs
This PR fixes several blocking issues related to checkpoint data and schema correctness.
One especially important note is that I'm switching from nanoseconds to microseconds for the default arrow timestamp unit. Neither actually works well for read scenarios because the parquet timestamp could be one of various types (https://github.com/delta-io/delta/issues/643), but for writes, microseconds definitely looks like the best bet for broad support and good precision.
Note: I'm merging this to the writer-map-support branch rather than main because the required arrow and parquet crate refs aren't ref'ed by datafusion yet.
Additional note: this also picks up @mosyp's fix to the fs backend that was merged to main in https://github.com/delta-io/delta-rs/pull/376
> Fix checkpoint and timestamp bugs

- aws/delta-checkpoint/docker-compose.yml
- aws/delta-checkpoint/src/main.rs
- aws/delta-checkpoint/tests/lambda_checkpoint.rs
- build/setup_localstack.sh
- rust/src/checkpoints.rs
- rust/src/delta.rs
- rust/tests/checkpoint_writer_test.rs
When creating checkpoints from table uri there's been at least 2 instances of backend. Also when calling with table_state, once has to have a table instance to call it, so we'll get additional instances of tables and backends.
I've also removed checkpoint struct as usually they created just for one call and hence unneeded. 
Also fixed a PR builds due to localstack image version bump
> Reuse table/storage instances in checkpoints

- rust/src/storage/file/rename.rs
add a specific panic! message when libc::renameat2 returns the EINVAL flag and handle the error message it in the succesful atomic_rename / move A to C test
After cloning the repo on Windows with VSCode and building it on WSL2, the atomic_rename test failed with a generic "invalid argument" error message. Atomic rename is supported on WSL2, but not when you try to rename files on the Windows mounts. This change adds a error handle for this situation in the atomic_rename function, to make the error much more specific. 
None as far as I am aware, and I didn't open an issue for it myself. 
N/A
> additional error handling to atomic_rename

- rust/src/delta.rs
Adding commitInfo data for the create method for DeltaTable
closes #350
Looking for input on the field names for json provided by delta-rs
"delta-rs": version of delta-rs
"timestamp": unix time in milliseconds
> added initial commit info on create method for a DeltaTable

- rust/src/checkpoints.rs
- rust/tests/checkpoint_writer_test.rs
Fixes #385
And takes into account https://github.com/delta-io/delta-rs/issues/385#issuecomment-900032974 suggestion
> Remove version param from create_checkpoint_from_table

- python/Makefile
- python/README.md
This change was made to make it easier for new developers to quickly setup a dev environment for working on the python api portion of delta-rs
#404 
The command `make setup-dev` may not work if multiple versions of the whl file are created from `maturin build` in the `/target/wheels/` directory
> Update python readme

- rust/src/delta.rs
- rust/src/storage/azure.rs
- rust/src/storage/file/mod.rs
- rust/src/storage/file/rename.rs
- rust/src/storage/gcs/client.rs
- rust/src/storage/gcs/mod.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
- rust/tests/repair_s3_rename_test.rs
As a follow up of #367 , use syscall rename in `put_obj` to avoid race conditions.
- related to #361
> Use `tokio::fs::rename` in `put_obj`.

- rust/src/delta.rs
- rust/tests/read_delta_test.rs
Every time the `update` is called, the `Add` action from the latest checkpoints are being applied once more, leading into duplicates. 
As it turned out, it's a regression from https://github.com/delta-io/delta-rs/pull/124 changes.
First commit shows the repro steps, second revers mention changes and resolves the issue
> Fix duplicates on update call

- python/deltalake/table.py
- python/docs/source/conf.py
- python/stubs/pyarrow/fs.pyi
- python/tests/test_table_read.py
- Expose `filesystem` argument for reading DeltaTable with Pyarrow in the Python binding
#392
> Add filesystem argument for reading DeltaTable in Python binding

- rust/src/delta.rs
- rust/src/schema.rs
This change makes the table `Schema` type an alias to the `SchemaTypeStruct` thus ensuring that all tables are properly created with the correct schema type.
closes #409
The related issue #409 details this a bit more. But as required in other delta implementations -  spark -
the create table must use a struct type as the schema definition. 
https://jaceklaskowski.github.io/mastering-spark-sql-book/logical-operators/CreateTableStatement/?h=createtable
https://jaceklaskowski.github.io/mastering-spark-sql-book/types/StructType/
> Ensures that all table schemas are of StructType

- rust/src/storage/gcs/client.rs
- rust/src/storage/gcs/util.rs
After putting together some code to actually write into gcs, I had encountered a few issues.
- Content Length header must be included on POST requests, else a 411 status is returned
- ~The storage backend rename method was attempting to cleanup the src file, but it turns out this is unnecessary`~
EDIT: nope that delete in rename is needed
> Gcs writer bugs

- rust/src/lib.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/dynamodb_lock.rs
- rust/src/storage/s3/mod.rs
- rust/tests/dynamodb_lock_test.rs
- rust/tests/repair_s3_rename_test.rs
- rust/tests/s3_test.rs
Add S3StorageOptions to allow configuring S3 backend explicitly (rather than through env).
This enables different backend configuration for two different delta tables (which is a need in kafka-delta-ingest for dead lettering to delta). With this change, we can configure two different storage backends with different parameters (specifically DynamoDb lock name difference is needed for our use case) and use the `DeltaTable::new` factory (https://github.com/delta-io/delta-rs/blob/main/rust/src/delta.rs#L1038).
Does not reference an existing delta-rs issue, but required for dead lettering to delta in kafka-delta-ingest - https://github.com/delta-io/kafka-delta-ingest/pull/69
> Add S3StorageOptions to allow configuring S3 backend explicitly

- rust/src/checkpoints.rs
Let's keep it in debug level as other logs in delta-rs and let the caller to decide how to log it in info level
> Change checkpoint creation logs from info to debug

- python/LICENSE.txt
- python/pyproject.toml
- Add the `LICENSE.txt` file in the Python binding to include it inside the package when using `maturin`
- Refer the `LICENSE.txt` file in `pyproject.toml`
#421
> Add LICENSE file in the Python binding and refer it in the pyproject

- python/src/lib.rs
- rust/src/action.rs
- rust/src/delta.rs
- rust/tests/azure_test.rs
- rust/tests/read_delta_test.rs
- rust/tests/read_simple_table_test.rs
- rust/tests/s3_test.rs
- rust/tests/write_exploration.rs
Audit Action attributes using https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala file
closes #372
> Audit action field optionality

- python/deltalake/table.py
- python/src/lib.rs
- rust/Cargo.toml
- rust/src/checkpoints.rs
- rust/src/delta.rs
- rust/src/delta_config.rs
- rust/src/lib.rs
- rust/tests/azure_test.rs
- rust/tests/checkpoint_writer_test.rs
- rust/tests/data/checkpoints_rw/.gitignore
- rust/tests/fs_common/mod.rs
- rust/tests/read_delta_test.rs
- rust/tests/read_simple_table_test.rs
- rust/tests/s3_test.rs
There's a lot of delta configs which are ignored by delta-rs. This PR introduces the mechanism of working with these configs with the similar manner as in spark codebase https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala#L325.
When working with kafka-delta-ingest in production we noticed that removes logs are never cleared, however they are in spark writer, due to the config mention above. 
Note that the `vaccum` function has not been modified in this PR (however it has to use the retention interval value from the configs as default instead of const value). Because when comparing it with spark `vaccum`, we found that spark deletes **every** file which is in the table but not referenced in delta logs. 
Both delta logs entries and …
> Introduce DeltaConfig and tombstones retention policy

- Cargo.lock
- python/Cargo.toml
- rust/Cargo.toml
- rust/src/checkpoints.rs
- rust/src/delta_arrow.rs
support partition value string deserialization for timestamp/binary
- related to #357
> Support partition value string deserialization for timestamp/binary

- rust/src/schema.rs
This PR just makes a doc-comment out of a pre-existing comment, so that the list of valid primitive types at least appears in the documentation. Even better would be to have an enum, but that can happen in a further commit :)
> Document the valid primitive types

- rust/src/storage/s3/dynamodb_lock.rs
- rust/src/storage/s3/mod.rs
- rust/tests/dynamodb_lock_test.rs
If there's any outside of delta-rs writes to the table that are done with s3 backend and dynamodb lock, we want the mechanism to immediately stop delta-rs writes if required. 
The example could be the dropping of a table. For example you acquire a lock and then try drop (or drop/create etc., something that modifies the delta log completely) a table. The dangerous part here is that the concurrent delta workers will still perform the write whenever the lock is available, because we effectively lock the `rename` operation. 
To prevent that, this PR introduces a `is_non_acquirable` that will cause delta-rs writer to fail immediately (or to be precise return the specific error) when the remote lock has this field set. For this to work, the outside of delta-rs writer, which performs the …
> Add is_non_acquirable field to the dynamodb lock

- rust/src/delta.rs
- rust/tests/read_simple_table_test.rs
Right now, we use `Iterator::retain` to remove files from active file list when applying remove actions from the transaction log. This can be optimized by performing an early exit of the iteration when we reach the file that needs to be removed.
1. Find the position of the file.
2. Remove the file from the vector.
- closes #424
> Optimize remove action apply with early iteration exit #424

- rust/src/storage/s3/dynamodb_lock.rs
- rust/tests/dynamodb_lock_test.rs
- `release_lock` allowed non-owners to release a lock, added the owner check to prevent that
- introduced `delete_lock` for non-owners to delete a lock
The option to delete a lock for non owners is added to recover from `is_non_acquirable` locks in kafka-delta-ingest
> Add delete_lock and fix release_lock

- rust/src/delta.rs
Improve tombstone handling by only applying the remove actions as a
batch at the end of a load or incremental update operation.
For checkpoint loading, we entirely skip interpretation of the remove
actions because according to the delta spec, a remove must be in a later
revision than the associated add, so they wouldn't be both in the same
checkpoint.
The PR does not add any new tests, as we are only changing implementation details. I think the proper handling of tombstones is demonstrated by `read_simple_table()` as it makes sure that tombstones are applied properly when loading a table with remove operations.
> Batch-apply remove actions in tombstone handling

- .github/workflows/build.yml
Some of the s3 tests was missed out by CI. I figure it easier to run every test with s3 feature on, rather than selective, it's far more reliable (also as of now we have missed the whole file from ci )
> Run all tests under s3 feature flag

- Cargo.lock
- README.adoc
- python/Makefile
- python/README.md
- python/pyproject.toml
- Bump [maturin](https://github.com/PyO3/maturin/releases/tag/v0.11.4) version  to `0.11.4` to install extra with the develop command
- Add make develop command to launch maturin develop with the extras
- Add history command in the README.md
> Add maturin develop command with extras in Python binding

- .github/workflows/python_build.yml
- .github/workflows/python_release.yml
- Cargo.lock
- python/Cargo.toml
- python/pyproject.toml
- rust/Cargo.toml
- rust/src/bin/delta-inspect.rs
- Change Rust edition `2018` to `2021`
- Change maturin version `0.11.4` to `0.11.5`
> Change Rust edition from 2018 to 2021

- python/Cargo.toml
- python/deltalake/__init__.py
- python/deltalake/fs.py
- python/pyproject.toml
- python/src/lib.rs
- python/stubs/deltalake/deltalake.pyi
- python/tests/test_table_read.py
- Add PyDeltaTableError in Python binding
- Add markers for pytest
- Bump version to `0.5.4`
- close https://github.com/delta-io/delta-rs/issues/493
> Add DeltaTableError in Python binding

- Cargo.lock
- rust/Cargo.toml
- rust/src/delta_datafusion.rs
- rust/tests/datafusion_test.rs
Using released arrow/parquet crates. One step closer to the delta-rs release. 
Unfortunately datafusion has no release for 6.1 yet
> Bump arrow to 6.1.0

- rust/Cargo.toml
- rust/src/checkpoints.rs
- rust/src/delta_config.rs
- rust/src/storage/file/rename.rs
- rust/src/storage/mod.rs
- rust/src/table_state.rs
- rust/tests/checkpoint_writer_test.rs
This patch adds the config `logRetentionDuration` which controls how long delta table commit logs should be in retention. After creating a checkpoint, expired delta table commit logs will be deleted.
closes #437
> Clean up expired delta table commit logs after checkpoint

- rust/Cargo.toml
Makes it more flexible for downstream consumers. We can expect no breaking api changes in arrow within the same major version releases.
> pin arrow to major version

- rust/src/checkpoints.rs
- rust/src/delta_config.rs
- rust/src/storage/file/mod.rs
- rust/src/table_state.rs
- rust/tests/checkpoint_writer_test.rs
This is the follow up work of #484. This patch adds one bool config `enableExpiredLogCleanup` which is also documented in official delta lake implementation. The config controls whether to clean up expired checkpoints and logs.
> Add bool config enableExpiredLogCleanup

- rust/src/checkpoints.rs
- rust/tests/checkpoint_writer_test.rs
1)  fix cleanup_expired_logs which used `timestamp()` which are seconds but not millis
2) fix delete_expired_delta_log_in_checkpoint by adding missing check on version `2` and using `modified` on the actual file (which is used in comparison rather then log action json)
> Fix cleanup_expired_logs timestamp

- rust/src/action.rs
- rust/tests/fs_common/mod.rs
- rust/tests/read_delta_partitions_test.rs
If checkpoint contains the partition with null value, the `populate_hashmap_with_option_from_parquet_map` will fail to read it because it expects the value to be present, despite the map being `HashMap<String, Option<String>>`
> Fix nullable partition values

- rust/src/storage/s3/mod.rs
- rust/tests/repair_s3_rename_test.rs
We're getting 500 errors in kafka-delta-ingest on get requests (especially with several workers), which is expected and such requests have to be retried
```
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message>
```
We've already tested this in high load environments and this fix helped us avoid unnecessary restarts https://github.com/delta-io/delta-rs/tree/kdi-partition-values-quick-fix.
I've tried to find some universal approach to retry every s3 requests, but couldn't figure out one due to rusoto restrictions
> Retry S3 get request on 500 Internal Server Error

- rust/src/schema.rs
This PR adds support for creating Array and Map schema types.
- closes #513
> Add support for creating Array and Map schema types

- Cargo.lock
- aws/delta-checkpoint/src/main.rs
- rust/src/checkpoints.rs
- rust/src/delta_arrow.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
- rust/tests/checkpoint_writer_test.rs
- rust/tests/read_delta_partitions_test.rs
- rust/tests/read_delta_test.rs
The `list_objs` for s3 returned a list of `ObjectMeta` with a `path` as `key` instead of `s3_path`. E.g.
`ObjectMeta { path: 'table/_delta_log' }` instead of `ObjectMeta { path: 's3://bucket/table/_delta_log' }`. However, the `head_obj` for example returns expected s3 uri.
This was found when running `cleanup_metadata` on S3, since it uses `list_objs` to list objects. So primary testing are done within a scope of this feature. I've also replicated tests with fs to be consistent. Also note that there's no workaround to pauses as S3 doesnt allow you to change object modified metadata.
> Fix S3 list_objs and cleanup_metadata

- rust/src/lib.rs
> Add datafusion examples to docs

- rust/src/storage/gcs/client.rs
- rust/src/storage/gcs/error.rs
- rust/tests/gcs_test.rs
closes #530
When the gcs credentials cannot be found, the error looks confusing now:
```
thread 'gcs::test_gcs_simple' panicked at 'called `Result::unwrap()` on an `Err` value: StorageError { source: GCSError { source: IOError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } } }', rust/tests/gcs_test.rs:21:14
```
This makes it a specified credential error so users can easier know what's going wrong:
After:
```
thread 'gcs::test_gcs_simple' panicked at 'called `Result::unwrap()` on an `Err` value: StorageError { source: GCSError { source: CredentialsError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } } } }', rust/tests/gcs_test.rs:21:14
```
BTW, we don't have a gcs test …
> Add gcs test and improve credential error

- .gitignore
- python/.cargo/config
- python/deltalake/table.py
- python/src/lib.rs
- python/stubs/deltalake/deltalake.pyi
- python/stubs/pyarrow/dataset.pyi
- python/tests/test_table_read.py
- rust/src/action.rs
- rust/src/bin/delta-inspect.rs
- rust/src/delta.rs
- rust/src/delta_arrow.rs
- rust/src/storage/file/mod.rs
- rust/tests/read_delta_test.rs
- rust/tests/read_simple_table_test.rs
As currently written, `DeltaTable.to_pyarrow_dataset()` will start the dataset discovery process, requiring additional IO to discover partitions and read schemas. This PR changes the implementation to populate the dataset fragments based on the delta log, which will avoid some discovery IO and also allow the datasets API to benefit from the file statistics in the log.
In detail:
* Changed `get_file_uris()` and `get_stats()` public methods to return iterators instead of materialized vectors.
* Added new `get_partition_values()` method that returns iterator over the partition values of each file.
* Created new `dataset_partitions()` method in Rust `RawDeltaTable` impl, which returns the list of files and an associated partition expression (one that is guaranteed to be true for all rows in …
> [Python] Create PyArrow dataset fragments from delta log

- python/docs/source/usage.rst
I rewrote most of the Python usage documentation.
* Reflowed the usage documentation to start with loading, then look at log introspection, and finally querying tables. At the end I created a placeholder for writing, noting that it's not yet supported.
* Added info about supported backends and data catalogs.
* Added more examples and guidance on how to query Delta tables. Note: I'd like to include DataFusion here, but from what I've seen that's not yet possible, right?
By rewriting this I broke any links to sections *within* the page, but not to the page itself.
None
> Refresh Python usage documentation

- rust/.gitignore
- rust/src/storage/s3/mod.rs
As part of the refactoring done by https://github.com/delta-io/delta-rs/pull/508, the `LockClient` used by the S3 storage implementation got coupled to a specific implementation of the `LockClient`, i.e. `DynamoDbLockClient`.  That doesn't look to be necessary and this PR addresses that by removing that coupling and let the S3 storage support any `LockClient`. 
This is useful in cases where we may not be using S3 in AWS.  For example, one could be using MinIO, Hitachi HCP etc which implement the S3 protocol and can be used just like S3.  In these cases, a DynamoDb based lock is not required and some other implementation can be used.
> Remove coupling of DynamoDbLockClient from S3 storage

- python/deltalake/table.py
- python/docs/source/usage.rst
- python/pyproject.toml
- python/src/lib.rs
- python/tests/test_table_read.py
- rust/src/storage/s3/mod.rs
- Add `storage_options` parameters to the `DeltaTable` constructor to provide options for the backend storage in the Python binding
- Refactoring of the alternate constructors for the `DeltaTable`
- Bump version of `maturin` to `0.12.6`
- Add options in the S3 backend storage 
- closes #477 
- closes #278
> Add storage options for backends

- .github/workflows/python_release.yml
- Add the target in the Python release workflow of Github Action
More info: https://github.com/delta-io/delta-rs/runs/4925831645?check_suite_focus=true
> Fix the Python release Github action workflow for macos11

- rust/src/delta.rs
- rust/src/table_state.rs
- rust/tests/read_delta_test.rs
Implement various ways for clients to consume and update the Delta table's state. 
Clients have a choice of viewing actions related to a commit and then applying those actions to obtain the next version of the table. 
I used the general outline provided in #413 and I'm looking for feedback
Thanks
> Implement polling for table updates. (#413)

- Cargo.toml
- proofs/Cargo.toml
- proofs/README.md
- proofs/src/main.rs
- python/Makefile
Our TLA+ proof is already out of date, so I took a stab at using stateright to formally remodel our S3 atomic rename design.
I think the current proof already discovered a bug that could lead to duplicated commits in our implementation. Here is what it found:
- writer A acquires lock for version 0
- writer A paused
- writer B acquired expired lock
- writer B repairs writer A's rename, we now have version 0 saved in S3
- writer A resumes execution
- writer A sees version 0 already exists in S3
- writer A's rename call returned version already exists error, it increments the version count and tries the commit again.
You can replicate the trace by running the following command in the proofs folder:
```
cargo run --release explore --worker-count 3
```
> formally verify S3 atomic rename

- Cargo.lock
- aws/delta-checkpoint/src/main.rs
- rust/src/delta.rs
- The `obj.meta` is the absolute path of the object on AWS S3 so we could use directly the `table_uri` for comparing the listed files with the valid files of the DeltaTable.
- closes #549 
- AWS S3
- Local
> Fix VACUUM by using the URI of the DeltaTable when filtering the files to delete

- Cargo.toml
- delta-inspect/Cargo.lock
- delta-inspect/Cargo.toml
- delta-inspect/src/main.rs
- rust/Cargo.toml
- rust/src/delta.rs
- rust/tests/read_delta_test.rs
Remove CLI related deps from the rust core. Also change vacuum method to take a non-mut reference.
fix #402
> move delta-inspect to its own crate

- python/Cargo.toml
- Bump version of Python binding to 0.5.6
> Bump version of Python binding to 0.5.6

- .github/workflows/python_build.yml
- .github/workflows/python_release.yml
In #566 we ran into an issue where changes meant docs couldn't build with Python older than 3.8. We should simply build them in a newer version of Python.
In addition, we should be testing the Python package with both the minimal PyArrow version and the latest PyArrow version, since they are several major versions apart. (PyArrow right now just releases new major versions quarterly, so breaking API changes are common in experimental parts of the package.)
None
> [Python] Test in minimal and latest Python environments

- python/deltalake/writer.py
- python/src/lib.rs
- python/tests/test_writer.py
+ Add Name, Description, and Configuration arguments to write_new_datalake in python and python-rust bindings
+ Add round trip metadata writing test
+ Suppress write clippy "too many arguments" (Default max seems to be 7, function has 8). 
Should resolve #576
> Allow metadata for write_deltalake

- .github/workflows/lambda_checkpoint_build.yml
- rust/src/lib.rs
- rust/src/time_utils.rs
In its custom writer implementation, [kafka-delta-ingest](https://github.com/delta-io/kafka-delta-ingest) uses the `timestamp_to_delta_stats_string` function which was recently moved into its own private `time_utils` module. This PR makes `time_utils` public so we continue using the same code when upgrading to the newest version of `delta-rs`.
Drive by: Temporarily disable lambda checkpoint test until we get the checkpoint memory pressure figured out.
> Change private time_utils module to public.

- .github/workflows/python_build.yml
I noticed the CI job " Python Build (Python 3.7 PyArrow 4.0.0) " was taking a while, and it looks like it was building pandas from source. 
Before (16m45s): https://github.com/delta-io/delta-rs/runs/6282672393?check_suite_focus=true
After (8m57s): https://github.com/delta-io/delta-rs/runs/6283588059?check_suite_focus=true
Also added caching to the latest Python build, since it was easy. Can't add it to minimal due to issues with old glibc.
> Avoid building pandas and numpy from source

- rust/src/delta.rs
- rust/src/table_state.rs
- rust/src/writer/stats.rs
- rust/tests/read_delta_test.rs
Since #454 dev is stopped. We aim to gradually address that issue.
Firstly, this PR. The changes introduces  `require_files` which similar to `require_tombstones`, filters out any files if the flag is set to `false`. Hence the table state will end up with metadata only. This is a perfect behavior for append only apps (like kafka delta ingest for example). 
Secondly, the catch is the how to create a checkpoint, because we need both adds & removes for that. One possible approach is a create checkpoint in another process, which is applicable. However we can omit that and do in process if we apply the work from #454. E.g. by operating on arrow/record batch objects to reduce memory usage / decentralization just enough to read/create checkpoint.
Thirdly, if 2nd step is successful, we can …
> Introduce require_files for tracking the add files in table state

- .github/workflows/python_build.yml
- python/deltalake/writer.py
- python/pyproject.toml
- python/tests/test_fs.py
- python/tests/test_table_read.py
- python/tests/test_writer.py
Pandas is supposed to be an optional dependency. This PR adjust CI to enforce that, fixes the issues in the writer sub-module, and also make pandas optional for unit tests.
Thanks @fvaleye for reporting this issue!
- closes #596
> Make sure pandas is optional

- .github/workflows/build.yml
- rust/src/delta_datafusion.rs
- rust/src/operations/transaction.rs
- rust/src/operations/write.rs
This PR does a bit of housekeeping: 
- fixes an oversight in the latest Delta operations commit
- re-enables tests for datafusion which were deactivates back in the days of arrow 6 :)
- add some updates to the datafusion integration originally proposed in #344, which seems to have gone stale
P.S. Sorry for the sizeable update in the CI/CD files, my local prettier config is eager to adjust it to its liking. (only relevant change in L91)
> Re-enable datafusion tests and improve supported types.

- rust/src/storage/mod.rs
Defaults to a root path if there is no path segment in an azure storage path.
i..e this does work right now `adls2://account/container/`, while this does not work `adls2://devargusadlsv2/simple`. THis PR makes the second option also work.
closes #602
> default to root for empty path in azure store

- rust/Cargo.toml
- rust/src/storage/azure/mod.rs
- rust/src/storage/mod.rs
Allows a user to create a DeltaTable backed by ADLS storage by simply passing uri and a map of options.
This helps promote the usage of different storage backends by only having to change some configuration rather than explicitly creating a storage backend instance in the user's code. 
Related to #555 since it allows an alternative from using environment variables for creation.
> Configure Azure storage using a map (#555)

- Cargo.lock
- rust/src/storage/azure/mod.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
The PR improves flexibility and ease of use for creating `Adls2StorageBackaends`.
* Introduce `AzureStorageOptions` a typed struct to make azure config options explicit.
* Harmonizes option handling between S3 and Azure.
* explicitly support service principal authorization ontop of previously introduced TokenCredential
The azure backend tests were successfully executed locally.
closes #555
closes #527
closes #554 
#554 was actually done before, but should be closed anyhow
> Azure options

- Cargo.lock
- aws/delta-checkpoint/Cargo.toml
- dynamodb_lock/Cargo.toml
- rust/Cargo.toml
Update the `rusoto` dependencies to version `0.48`
> Update rusoto dependencies to 0.48

- python/pyproject.toml
There seems to be a bug in 5.0 when handling `Literal[]` type hints.
I've raised an issue upstream: https://github.com/sphinx-doc/sphinx/issues/10497
> fix: cap sphinx version to avoid bug in 5.0

- .github/workflows/python_release.yml
- Provide Python `aarch64` wheels for Linux by adding a new release Python step in the Github action with the `manylinux2014` Docker image
> Provide Python aarch64 wheels for Linux.

- python/deltalake/writer.py
- python/docs/source/usage.rst
- python/src/lib.rs
- python/tests/test_writer.py
Changes:
* Fixes `write_deltalake()` to enforce the existing schema of the table
* Makes most arguments of `write_deltalake()` keyword-only. This is nice because it means re-ordering them later will no longer be a breaking change.
* Added `overwrite_schema` argument, which allows providing a new schema when `mode="overwrite"`. This is meant to parallel the PySpark option `option(“overwriteSchema”, “true”)`.
* Fixes #623
> feat(python): validate schema in write_deltalake

- .github/workflows/build.yml
- Cargo.lock
- rust/Cargo.toml
- rust/src/storage/azure/mod.rs
- rust/src/storage/mod.rs
- rust/tests/adls_gen2_backend_test.rs
- rust/tests/adls_gen2_table_test.rs
- rust/tests/read_simple_table_test.rs
With the latest version of the azure SDKs some annoyances got fixed. specifically, list now returns something `Send`able, which allows us to significantly simplify the `list_objs` method. Secondly the errors are no longer a deeply nested nightmare 😆.
Also added a test for validating that service principal access works (#609) - currently i am guessing the issues encountered there are more related to #643
validate the SP access works for #609
> Refactor azure storage with crate updates

- rust/src/delta.rs
Defers the creation of the storage backend until `build` is called on the builder unless a backend is provided by the user.
An alternative approach to resolving this is to add a new method called `from_uri_with_map` which will use a map when creating a backend. If we want to use this approach I have no problem with changing the implementation.
- closes #638
> Defer creation of storage backend in DeltaTableBuilder

- .github/workflows/python_build.yml
- python/Makefile
- python/deltalake/fs.py
- python/deltalake/writer.py
- python/pyproject.toml
- python/src/lib.rs
- python/tests/conftest.py
- python/tests/pyspark_integration/test_writer_readable.py
- python/tests/test_writer.py
- rust/src/checkpoints.rs
- rust/src/storage/azure/mod.rs
- rust/src/storage/file/mod.rs
- rust/src/storage/gcs/mod.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
- rust/tests/adls_gen2_backend_test.rs
- rust/tests/s3_test.rs
Fixes two bugs:
1. The `size` field of add actions was always being set to zero. This PR corrrect that to always use the correct file size.
2. Null partition values were being recorded in add actions with the string `"__HIVE_DEFAULT_PARTITION__"`. They are now correctly recorded as JSON `null` values. 
Other changes in service of fixing those bugs:
1. Added pyspark integration tests that run in CI. This is what allowed me to catch the bugs. Right now it just tests that the output of our writer is readable in Spark. Our existing tests show that we can read their tables. We can't write to each others tables yet, because we don't support the same writer versions. (But maybe I should double check we are enforcing that 🤔 .)
2. Added `size` field to `ObjectMeta`, so we can use `head_object()` …
> fix: Add correct size and null paritition values to add actions

- rust/src/action.rs
https://github.com/delta-io/delta/commit/6f396301f74bea16ad27404a7c79e9aa698d6e2c added a new numRecords field on remove actions. To prevent a large spam of warnings when reading tables with this new field delta-rs needs to be updated to accept this field.
I've just gone for the simplest possible fix which is to just ignore `numRecords` when reading. I had a go at [making it read the field](https://github.com/delta-io/delta-rs/pull/650) but being a novice I didn't really know what the impact of those changes would be. 
- closes #614
> fix: Prevent warning spam when reading tables generated by delta 1.2.1

- python/src/lib.rs
- ruby/src/lib.rs
- rust/src/checkpoints.rs
- rust/src/delta.rs
- rust/src/operations/create.rs
- rust/src/operations/mod.rs
- rust/src/operations/write.rs
- rust/src/optimize.rs
- rust/src/table_state.rs
- rust/tests/adls_gen2_table_test.rs
- rust/tests/checkpoint_writer_test.rs
- rust/tests/concurrent_writes_test.rs
- rust/tests/gcs_test.rs
- rust/tests/optimize_test.rs
- rust/tests/read_delta_partitions_test.rs
- rust/tests/read_delta_test.rs
- rust/tests/read_simple_table_test.rs
- rust/tests/s3_test.rs
- rust/tests/simple_commit_test.rs
This PR moves the `version` field into `DeltaTableState`. The added consistency helps implementing #632 - split this in a separate PR to make review easier.
closes #390
> refactor: move version field to  `DeltaTableState`

- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_table_read.py
- rust/src/delta.rs
- rust/tests/read_delta_test.rs
This maps to the reference implementation's
spark.databricks.delta.retentionDurationCheck.enabled config.
> feat: add enforce_retention_duration param to vacuum method

- python/tests/test_table_read.py
- python/tests/test_vacuum.py
- rust/src/delta.rs
It seems that when we pass a relative path to `DeltaTable()`, vacuum doesn't actually delete files. I've added tests in Python which is more convenient now that we have a writer.
* Fixes #663
> bugfix: Make sure vacuum works on relative paths

- Cargo.lock
- rust/Cargo.toml
- rust/src/storage/azure/mod.rs
- rust/src/storage/file/mod.rs
- rust/src/storage/gcs/mod.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
So far we were not traversing into directories when listing objects with the local storage backend - this is required for the vacuum command to work properly (i.e discovering orphaned files not in the log).
I more or less ported the implementation from object_store_rs, as I believe the code over there is of very high quality.
As a "drive-by" I updated the return type definitions on all `list_objs` using the `BoxStream` shorthand.
@Blajda  - would the vacuum tests validate this fix?
towards #671
> fix: traverse directories in local `list_objs`

- rust/src/vacuum.rs
- rust/tests/common/adls.rs
- rust/tests/common/clock.rs
- rust/tests/common/mod.rs
- rust/tests/common/s3.rs
- rust/tests/common/schemas.rs
- rust/tests/vacuum_test.rs
Continuation of #669 but only contains the parts required to run the tests. My intent for this PR is to review the test utilities and vacuum test cases. It will not address the failing test cases for each backend. Once we have sign off on that part we can mark the failing tests as `ignore`
Currently this is the status for each vacuum tests against each backend
| Test Name                               | Local FS | S3 | ADLS|
|-----------------------------------------|-------------|-----|---------|
| test_non_partitioned_table      | :heavy_check_mark:  | :heavy_check_mark: | :x: | 
| test_partitioned_table              | :x: | :heavy_check_mark:  | :x: | 
| test_ignored_files                    | :heavy_check_mark:  | :heavy_check_mark: | :x: | 
| test_partitions_included          | :x: | …
> Implement vacuum tests and general test setup utils

- .github/dependabot.yml
- Setup dependabot for Rust by adding `dependabot.yml` file in the Github configuration
- Weekly frequency to have up-to-date Rust dependencies
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> Setup Github dependabot for Rust

- python/src/lib.rs
- rust/src/delta.rs
- rust/src/optimize.rs
- rust/src/storage/mod.rs
- rust/src/writer/json.rs
- rust/src/writer/record_batch.rs
- rust/src/writer/stats.rs
- rust/src/writer/test_utils.rs
- rust/tests/adls_gen2_backend_test.rs
- rust/tests/common/mod.rs
- rust/tests/optimize_test.rs
While working on #632 i saw that a shareable storage backend is also required for #690 - as such i decided to move this to a separate PR, to get things stared for #689.
> feat: sharable reference to storage backend

- python/deltalake/writer.py
Following up on #654, Get size from written_file if PyArrow >= 9.0.0
> Get file size from Pyarrow directly (>= 9.0.0)

- python/docs/source/usage.rst
- Fix usage section in the Python documentation: use `load_with_datetime()`
> Fix usage documentation in Python binding

- .github/workflows/python_build.yml
- Cargo.lock
- rust/Cargo.toml
- rust/src/checkpoints.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/mod.rs
- rust/src/schema.rs
- rust/tests/datafusion_test.rs
This PR deepens the integration with datafusion by leveraging the column statistics from the delta log to prune the files that need to be scanned when additional constraints are supplied. Luckily datafusion provides some excellent utilities to implement this. Specifically we implement `PruningStatistics` for `DeltaTable`,  use that with `PruningPredicate`, and the rest just kind of happens 😆. 
I still need to do cleanup and more testing as well as have a look how much effort and dependency growth it would be to adopt datafusion expressions for our partition / stats handling. However if there is feedback as to if this is the right way to go, I'd be happy to hear it.
_cc_ @houqp @wjones127 - maybe even @tustvold has some feedback? :) 
Especially the statistics recorded during scans should …
> Prune scanned files on column stats

- rust/src/action.rs
- rust/tests/read_delta_test.rs
When reading the struct column stats (as opposed to json column stats) the null counts where ignored for struct type columns. Completely ignoring is probably less bad than parsing them wrongly but if the user was filtering on a struct column this may have impacted performance. It was also spamming error logs:
```
[2022-07-26T19:33:52Z ERROR deltalake::action] Expect type of stats_parsed.nullRecords value to be struct, got: {integer: 0, null: 1, boolean: 0, double: 0, decimal: 0, string: 0, binary: 0, date: 0, timestamp: 0, struct: {struct_element: 0}, map: 0, array: 0, nested_struct: {struct_element: {nested_struct_element: 0}}, struct_of_array_of_map: {struct_element: 0}}
```
I probably should have done this as part of https://github.com/delta-io/delta-rs/pull/656. Sorry for introducing …
> Fix parsing null counts for struct type columns in the struct stats

- .github/workflows/python_build.yml
- python/pyproject.toml
- python/tests/test_writer.py
I thought we were testing with `pyarrow==4`, but turns out `maturin develop` silently upgrades all dependencies :facepalm:.
It seems that our actual minimum version is pyarrow 7.0.0 (released in February 2022), which was mostly pushed up by my work on the writer. This PR pushes up the minimum version. If that feels to aggressive, I could refactor so that only the writer module requires this more recent version.
> Python: fix: fix minimal test and bump minimum pyarrow version

- dynamodb_lock/src/lib.rs
- python/src/lib.rs
- rust/src/action.rs
- rust/src/delta.rs
- rust/src/delta_config.rs
- rust/src/storage/azure/mod.rs
- rust/src/storage/file/rename.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3/mod.rs
- rust/src/vacuum.rs
This addresses clippy lint warnings that appeared with the 1.63.0 release of rust. Most of the changes are reasonable and straight forward. I'm unsure about the best way to resolve python/src/lib.rs. I whitelisted the check, as py03 wants pymethods to have parameters with known sizes as compile time.
- closes #741 
https://rust-lang.github.io/rust-clippy/master/index.html#needless_return
https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
https://rust-lang.github.io/rust-clippy/master/index.html#borrow_deref_ref
> fix: Address clippy lint warnings.

- python/deltalake/fs.py
- python/deltalake/table.py
- python/src/lib.rs
- python/tests/pyspark_integration/test_writer_readable.py
- rust/src/builder.rs
After the migration to `object_store`, the pyarrow integration broke when using remote storages. The root cause is that paths are handled a bit differently by object_store, and these differences were not accounted for in all scenarios.
Specifically, when using the `DeltaStorageFsBackend`, we are passing in the full path including cloud prefixes - e.g. `s3://<bucket>/<path>`. Object store now expects paths relative the the object store root. For remote stores, the root is always the bucket level, for local it can be anywhere, but we make sure its always the file system root. (note the `DeltaObjectStore` wrapping the backend is always rooted in the table root).
Since recently we have a new struct `StorageUrl`, which encapsulates all the logic of url parsing specific to our object store. …
> hotfix: python object store paths

- .github/workflows/build.yml
- .github/workflows/python_release.yml
- Cargo.lock
- python/Cargo.toml
- python/Makefile
- python/docs/source/usage.rst
Prepare the release of python version `0.6.1`, to mitigate the regression regarding path handling.
I tested it against real azure, azurite and localstack. Prettier made this PR a bit less pretty, but the following a re the relevant changes.
- update python version 
- remove macos-10.15 from test matrix, add macos-11
- update python makefile, since somehow version parsing broke, which in turn broke the docs build.
- update docs relating to table uris.
closes #785 (i guess we'll see in ci :) ... but i could repro and fix it locally)
> prepare python release `0.6.1`

- Cargo.lock
- python/Cargo.toml
- python/deltalake/deltalake.pyi
- python/deltalake/fs.py
- python/deltalake/writer.py
- python/docs/source/usage.rst
- python/src/filesystem.rs
- python/src/lib.rs
- python/src/schema.rs
- python/src/utils.rs
- python/stubs/pyarrow/__init__.pyi
- python/tests/test_file_system_handler.py
- python/tests/test_fs.py
- python/tests/test_table_read.py
- rust/src/storage/mod.rs
This PR embraces the object store crate also on the python side and at least for the current test base supports reading and writing using the dataset and other pyarrow APIs. Thanks to @wjones127 's mutipart upload in object_store, implementing the write functionality was actually quite straigt forward. We now implement `ObjectInputFile` and `ObjectOutputStream`, which - if wrapped in `pyarrow.PythonFile` will work with the arrow ecosystem (so far ;))
There was on bigger and breaking deign decision, but I hope people agree :).
Essatially I just accepted, that working exclusively with the relative delta paths makes life much more convenient.. As such rather then adding and removing paths prefixes all the time, I thought it would be reasonable to as users to wrap their own filesystems in a …
> feat: integrate `object_store` for read/write with pyarrow

- rust/src/action/parquet2_read/mod.rs
- rust/src/builder.rs
- rust/src/checkpoints.rs
- rust/src/delta.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/mod.rs
- rust/src/optimize.rs
- rust/src/writer/json.rs
- rust/src/writer/mod.rs
- rust/src/writer/record_batch.rs
- rust/src/writer/utils.rs
- rust/tests/command_optimize.rs
I have been working again on the high level writer APIs. Specifically how we use data fusion and trying to move towards a structure that can more easily integrate with other query backends. These changes are fairly well contained in the `operations` module, But they do include the changes here. While mostly cosmetic so far, I was hoping to merge this PR as is, as to make review in the follow ups easier.. Right now the main focus is to end up somewhere we we can finally finish #632. 
<hr/>
This in preparation to make a pass through the `RecordBatchWriter` and some convenience around loading partitioned tables,
Publishing this already to get some feedback on the general error handling approach.  I took the same approach in the updated file and s3 object stores. Essentially the idea would be …
> cleanup errors and make `DeltaWriterError` internal

- .github/workflows/python_release.yml
- Split Windows and Mac Github Action runners when releasing a new version of the Python binding
- Provide `x86_64` and `aarch64` wheels for Mac
- related to #808
> Refactoring of the Github Action python release

- python/deltalake/writer.py
- python/tests/test_writer.py
We were always testing writing to directories that already existed, and the recent object store changes caused a regression that made it not support writing to local directories that don't already exist.
- closes #777
> Re-allow writing to non-existant local paths

- python/deltalake/writer.py
- python/tests/test_writer.py
We were finding the file-level min and max by taking the min and max values of the row-group level ones; but we were not accounting for all-null row groups, which will not have min/max stats.
- fixes #763
> [Python] Fix handling of null stats in write_deltalake

- Cargo.lock
- python/deltalake/_internal.pyi
- python/deltalake/writer.py
- rust/Cargo.toml
- rust/src/builder/azure.rs
- rust/src/builder/google.rs
- rust/src/builder/mod.rs
- rust/src/delta.rs
- rust/src/storage/mod.rs
- rust/src/test_utils.rs
- rust/src/writer/json.rs
- rust/src/writer/mod.rs
- rust/tests/common/adls.rs
- rust/tests/common/mod.rs
This PR mainly improves the handling of configuration - hopefully. In essence we get closed to the options usually used in fsspec or the azure sdk, while retaining the current key names and the option to configure via the environment.
Previously I also believe that in cases where an applicable environment variable was defined, it may have taken precedence over alternative configuration passed to the Delta table.
For testing purposed the in-memory store can now also be used as a backend to delta tables. (I am working on updating the operations, and bringing in changes piece-by-piece to keep PR size reasonable).
For now I left out migrating the S3 config, as it has a bit more logic in it. Also since the currently documented way is still supported, I have not yet updated the documentation. I …
> feat: improve storage configuration

- Cargo.lock
- rust/Cargo.toml
- rust/src/delta_datafusion.rs
- rust/src/operations/create.rs
- rust/src/operations/mod.rs
- rust/src/operations/transaction.rs
- rust/src/operations/write.rs
- rust/src/storage/mod.rs
- rust/src/storage/utils.rs
- rust/tests/command_optimize.rs
- rust/tests/datafusion_test.rs
- rust/tests/integration_datafusion.rs
- rust/tests/integration_object_store.rs
Going forward we may introduce a dependency on `datafusion_expr`, or other sub crates, to use for handling predicates etc. AFAIK, the datafusion crate is also going to deprecate re-exports of some of these sub-crates. To be prepared for this, we refactor the imports in `delta-rs` to import from the sub-crates.
As a drive-by I also consolidated some helper functions in `storage::utils`.
> Datafusion-imports

- .github/workflows/build.yml
- aws/delta-checkpoint/Cargo.toml
- rust/tests/integration_commit.rs
- rust/tests/integration_concurrent_writes.rs
- rust/tests/integration_object_store.rs
also test rustls feature in CI
> use rustls for delta checkpoint lambda

- Cargo.lock
- python/Cargo.toml
- python/deltalake/_internal.pyi
- python/deltalake/writer.py
- python/src/lib.rs
- python/src/schema.rs
- python/tests/pyspark_integration/test_write_to_pyspark.py
- python/tests/pyspark_integration/test_writer_readable.py
- python/tests/pyspark_integration/utils.py
- python/tests/test_writer.py
- rust/src/delta.rs
- rust/src/delta_datafusion.rs
- rust/src/schema.rs
Adds support to retrieve invariants from the Delta schema and also a struct `DeltaDataChecker` to use DataFusion to check them and report useful errors.
This also hooks it up to the Python bindings, allowing `write_deltalake()` to support Writer Protocol V2.
I looked briefly at the Rust writer, but then realized we don't want to introduce a dependency on DataFusion. We should discuss how we want to design that API. I suspect we'll turn DeltaDataChecker into a trait, so we can have a DataFusion one available but also allow other engines to implement it themselves if they don't wish to use DataFusion.
- closes #592
- closes #575
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#column-invariants
> Add invariant enforcement support

- Cargo.lock
- python/Cargo.toml
- Bump Python binding version to `0.6.2` for a new release
> Bump Python binding version to 0.6.2

- python/deltalake/table.py
- python/src/lib.rs
Added _without_files_ flag to DeltaTable constructor. If the flag is set it will be called method _without_files_ in the **DeltaTableBuilder**. And this allows users to control memory usage. Some append-only applications might have no need of tracking any files.
Indicates whether DeltaTable should not track files. This defaults to "false" (files are tracked). Some append-only applications might have no need of tracking any files. So, DeltaTable will be loaded with significant memory reduction.
> Added without_files flag to DeltaTable constructor

- .github/workflows/build.yml
- .github/workflows/python_build.yml
- docker-compose.yml
- python/deltalake/_internal.pyi
- python/deltalake/writer.py
- python/src/filesystem.rs
- python/src/lib.rs
- python/tests/conftest.py
- python/tests/pyspark_integration/test_write_to_pyspark.py
- python/tests/test_fs.py
- rust/src/builder/mod.rs
- rust/src/storage/s3.rs
- rust/src/test_utils.rs
- rust/tests/common/s3.rs
We forgot to pass down storage options, so storage options were being ignored if you were passing a URI and not a DeltaTable.
This also adds a new S3 option: `AWS_S3_ALLOW_UNSAFE_RENAME` which allows using the default S3 backend without support for concurrent writers. This is an opt-in option and there is a helpful error message to provide guidance to users.
To test, I implemented integration tests that run against localstack.
- might be a fix for #883
> fix: pass storage options down when getting delta table

- .github/workflows/build.yml
- Cargo.lock
- dynamodb_lock/src/lib.rs
- rust/src/checkpoints.rs
- rust/src/writer/stats.rs
- Fix the latest cargo clippy issues in Rust from the version `0.1.65`
> Fix cargo clippy issues 0.1.65 in Rust

- python/Cargo.toml
- Prepare the release of the Python version `0.6.3` binding
> Bump version of the Python binding to 0.6.3

- python/deltalake/table.py
- python/deltalake/writer.py
- python/tests/test_table_read.py
We weren't enforcing the reader protocol version, causing issues when trying to read tables with column mapping. 
- closes #929
> fix(python): enforce reader protocol version

- python/deltalake/table.py
- python/stubs/pyarrow/__init__.pyi
- python/tests/test_table_read.py
When passing `parquet_read_options` to `to_pyarrow_dataset` it is now possible to use `dictionary_columns` to control which columns should be dictionary encoded as they are read.
- closes #938
> Allow for reading columns as dictionaries using to_pyarrow_dataset

- Cargo.lock
- glibc_version/src/lib.rs
- rust/Cargo.toml
- rust/src/builder/mod.rs
- rust/src/delta.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/load.rs
- rust/src/storage/mod.rs
- rust/src/table_state.rs
- rust/tests/datafusion_test.rs
- rust/tests/integration_object_store.rs
Use (hopefully soon-to-be-merged) Datafusion functionality to allow dynamic (i.e. SQL-based) registration of deltalake tables at runtime.
- closes #891
- TBD
> Add TableProviderFactory and test for SQL to register tables dynamically at runtime

- python/src/filesystem.rs
- python/src/lib.rs
- python/src/utils.rs
This PR builds in top of the changes to handling the runtime in #933. In my local tests this fixed #915. Additionally, I added the runtime as a property on the fs handler to avoid re-creating it on every call. In some non-representative tests with a large number of very small partitions it cut the runtime in about half.
cc @wjones127
> feat: improve write perfromance of `DeltaFileSystemHandler`

- rust/Cargo.toml
- rust/examples/basic_operations.rs
- rust/src/operations/create.rs
- rust/src/operations/load.rs
- rust/src/operations/mod.rs
- rust/src/operations/writer.rs
- rust/src/table_properties.rs
Adding a simple example how to use operations APIs to create and work with delta tables and some minor documentation tweaks.
> docs: add simple operations example

- rust/Cargo.toml
It's been a long time since our last crates.io release!
Should make version pinning a little bit easier for https://github.com/pola-rs/polars/issues/2858
Closes https://github.com/delta-io/delta-rs/issues/480.
> bump rust core version to 0.5.0

- rust/Cargo.toml
all dependency versions need to be pinned in order to release to creates.io
> pin glic_version version in dep to unblock creates.io release

- rust/Cargo.toml
- rust/src/test_utils.rs
Wildcard version pin blocks crates.io publish
Also migrate to dotenvy because dotenv is not being maintained anymore.
> remove all wildcard version pin in Cargo.toml

- python/Cargo.toml
- python/pyproject.toml
- Prepare to release the version `0.6.4` of the Python binding
> Bump version of the Python binding to 0.6.4

- python/deltalake/schema.py
- python/deltalake/writer.py
- python/stubs/pyarrow/__init__.pyi
- python/tests/test_writer.py
As described in #686 some pandas datatypes are not converted to a format that is compatible with delta lake.  This handles the instance of timestamps, which are stored with `ns` resolution in Pandas.  Here, if is a schema is not provided, we specify converting the timestamps to `us` resolution.
We also update `python/tests/test_writer.py::test_write_pandas` to reflect this change.
#685
> Handle pandas timestamps

- Cargo.lock
- rust/src/delta_datafusion.rs
- rust/src/operations/write.rs
This PR integrates the `DeltaDataChecker` in the write path of the operations API. I was unsure whether to integrate this in the (experimental) writer in the operations module, but opted for keeping the writer itself focussed on the lower level write operations.
> feat: check invariants in write command

- rust/src/builder/azure.rs
When updating the parsing for azure configuration, the client secret got lost, This should fix that. 
closes #977
> fix: get azure client secret from config

- python/Makefile
- python/pyproject.toml
This loosen the version requirement for maturin when building the python package.
- closes #1004
Using an exact version can be excessively restrictive, for example preventing the use of the latest (but still compatible) version of maturin. Especially when packaging for rolling-releases distributions (like Archlinux), being able to build with the latest version would be beneficial.
> Loosen version requirement for maturin

- python/tests/test_fs.py
- rust/src/builder/azure.rs
This fixes the truncation of Azure SAS signatures ending in "=", i.e. when using non-url-encoded SAS tokens.
closes #1003
> fix truncating signature on SAS

- .github/workflows/dev_pr.yml
- .github/workflows/dev_pr/labeler.yml
Use [labeler](https://github.com/actions/labeler) to automatically label PRs. There are language labels, CI, documentation as well as crate-specific labels.
Closes #1026 & unblocks #997.
> Add PR autolabeling

- .github/workflows/dev_pr.yml
- docker-compose.yml
- python/pyproject.toml
- python/tests/conftest.py
- python/tests/test_fs.py
- rust/src/storage/utils.rs
- rust/src/test_utils.rs
This is intended to fix the issue where the Python CI job is frequently failing. I believe it's because the Docker services haven't fully started up before the tests start running. To address this, I added a function to wait for the services to be responsive.
> test(python): make sure integration tests wait for services to start

- rust/src/delta_arrow.rs
Adds support for UTC timezone.
- relates to #1019
> Fix to support UTC timezone

- rust/src/builder/azure.rs
- rust/src/builder/mod.rs
The object store crate encode the sas key values internally. When passing in an already encoded sas key, they would get double encoded. Since sas keys acquired from the azure portal and azure storage explorer are encoded, and this is "ususally" how a user would get them we decode them before passign them to object store.
I was not completely sure what the desired bahvior should be, alternatively we could update the documentation, to show a sas keys from the portal should be handled.
```py
import deltalake
from urllib.parse import unquote
storage_options = dict(account_name=storage_account, sas_token=unquote(sas))
dt = deltalake.DeltaTable(azure_uri, storage_options=storage_options)
```
closes #910
> fix: azure sas key url encoding

- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_fs.py
- python/tests/test_table_read.py
This PR consolidates the four methods `files()`, `file_paths()`, `file_uris()`, `files_by_partitions()` into just two methods:
* `files()` -> which returns paths as they are in the Delta Log (usually relative, but *can* be absolute, particularly if they are located outside of the delta table root).
* `file_uris()`, which returns absolute URIs for all files.
Both of these now take the `partition_filters` parameter, making `files_by_partitions()` obsolete. That latter function has been marked deprecated, but it also returns it to its original behavior of returning absolute file paths and not relative ones, resolving #894.
Finally, the `partition_filters` parameter now supports passing values other than strings, such as integers and floats.
TODO:
> refactor(api!): refactor Python APIs for getting file list

- rust/src/delta.rs
- rust/src/delta_datafusion.rs
- rust/src/test_utils.rs
- rust/tests/common/datafusion.rs
- rust/tests/common/mod.rs
- rust/tests/datafusion_test.rs
- rust/tests/integration_datafusion.rs
We've recently added Delta table support to [Seafowl](https://github.com/splitgraph/seafowl) using delta-rs, which utilizes the new `OPTIONS` clause in sqlparser/DataFusion. It allows propagating a set of key/values down to the `DeltaTableBuilder`, which in turn can use those to instantiate a corresponding object store client. This means someone can now define a delta table without relying on env vars as:
```sql
CREATE EXTERNAL TABLE my_delta
STORED AS DELTATABLE
OPTIONS ('AWS_ACCESS_KEY_ID' 'secret', 'AWS_SECRET_ACCESS_KEY' 'also_secret', 'AWS_REGION' 'eu-west-3') 
LOCATION 's3://my-bucket/my-delta-table/'
```
I've also changed the existing datafusion integration tests to use this approach to exercise it.
I'm not sure whether it makes sense to merge this PR upstream, but opening this PR …
> feat: enable passing storage options to Delta table builder via DataFusion's CREATE EXTERNAL TABLE

- .github/workflows/build.yml
- .github/workflows/lambda_checkpoint_build.yml
- .github/workflows/lambda_checkpoint_release.yml
- .github/workflows/python_build.yml
- .github/workflows/python_release.yml
- .github/workflows/ruby_build.yml
- .github/workflows/rust_release.yml
Update gihub actions to avoid warnings and deprecations. Unfortunately there is no updated version of `actions-rs/toolchain` (yet?), but at least some warnings will go away.
closes #978
> chore: update github actions to latest versions

- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_checkpoint.py
Current python wrapper hasn't any functionlity to create checkpoints.
This PR exposes rust functionality which is creates checkpoint at current table version.
Sample of usage:
```Python
delta_table = DeltaTable(some_path)
delta_table.create_checkpoint()
```
> Expose checkpoint creation for current table state in python

- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_table_read.py
- rust/Cargo.toml
- rust/src/lib.rs
- rust/src/table_state.rs
- rust/src/table_state_arrow.rs
- rust/tests/add_actions_test.rs
Exposes function to get a dataframe of add actions for selected version of the table. 
TODO:
- closes #1031
> feat: expose function to get table of add actions

- rust/src/builder.rs
- rust/src/delta.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/create.rs
- rust/src/operations/load.rs
- rust/src/operations/transaction.rs
- rust/src/storage/config.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3.rs
- rust/src/storage/utils.rs
- rust/tests/add_actions_test.rs
- rust/tests/checkpoint_writer.rs
- rust/tests/datafusion_test.rs
- rust/tests/fs_common/mod.rs
This PR contains some improvements and refactoring for handling storage locations.
- Removes the `StorageLocation` struct (a left-over from previous clean up)
- allows for creating tables using local file paths (including relative)
- persists options during serialization (this will not work for custom storage backends, but still extends what the previous approach could do)
- adopts `PrefixObjectStore` from upstream crate in favour of maintaining that logic here. 
- run `cargo clippy --fix` on `/rust`
Closes #998
> feat: improve storage location handling

- python/Cargo.toml
- rust/Cargo.toml
- rust/src/delta_arrow.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/load.rs
- rust/src/table_state_arrow.rs
Update datafusion to version 16 and arrow to corresponding version 29. This also fixes a logical error in predicate pushdown and implements missing methods on `TableProvider`, specifically also the one telling datafusion that predicate pushdown is supported :).
Turns out, our tests already cover that predicates are working correctly, when actually being used.
closes #1063
closes #1064
> fix: datafusion predicate pushdown and dependencies

- rust/src/action/mod.rs
- rust/tests/command_optimize.rs
- rust/tests/commit_info_format.rs
Currently writing "operationParameters" in commit info is misaligned with delta io connector. 
[Here](https://github.com/delta-io/delta/blob/36a7edb8cf507e713700ba827c5fb5ad32b9163e/core/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala#L695) the sample of structure which is used in delta io. 
So the goal of this PR is to align with delta io approach and the PR do two thins: convert all values to string and delete keys with null values. 
Closes [issue #1017](https://github.com/delta-io/delta-rs/issues/1017)
> Save operational params in the same way with delta io

- rust/Cargo.toml
Add missing metadata fields to `Cargo.toml`:
- `documentation`
- `repository`
- `readme`
This helps to provide more information on certain `crates.io` pages.
Closes #1076
> Add missing documentation metadata to Cargo.toml

- .github/workflows/dev_pr/labeler.yml
Several issue and PR labels are merged at the suggestion of @wjones127:
`delta-rs-crate` -> `binding/rust`
`python` -> `binding/python`
`ruby` -> `binding/ruby`
`aws` -> `storage/aws`
Note that we will still have a `rust` label for anything that changes any of the Rust crates outside Python & Ruby bindings. Also `storage/gcp` and `storage/azure` labels do not get automatically added.
If the new labels are acceptable I will file another PR to relabel old issues and PRs.
Closes #1051.
> ci: Merge several automatically generated labels

- .github/workflows/python_build.yml
- .gitmodules
- python/.gitignore
- python/Makefile
- python/tests/data_acceptance/test_reader.py
> test: add Data Acceptance Tests

- python/Cargo.toml
In preparation for new release.
> Bump deltalake-python version to 0.7.0

- delta-inspect/Cargo.lock
- delta-inspect/src/main.rs
- dynamodb_lock/src/lib.rs
- glibc_version/src/lib.rs
- python/src/filesystem.rs
- python/src/lib.rs
- python/src/schema.rs
- rust/examples/read_delta_table.rs
- rust/src/action/mod.rs
- rust/src/action/parquet_read/mod.rs
- rust/src/checkpoints.rs
- rust/src/delta.rs
- rust/src/delta_arrow.rs
- rust/src/delta_config.rs
- rust/src/operations/create.rs
- rust/src/operations/transaction.rs
- rust/src/optimize.rs
- rust/src/partitions.rs
- rust/src/schema.rs
- rust/src/storage/file.rs
- rust/src/table_state.rs
- rust/src/table_state_arrow.rs
- rust/src/writer/mod.rs
- rust/src/writer/stats.rs
- rust/src/writer/utils.rs
- rust/tests/checkpoint_writer.rs
- rust/tests/read_delta_partitions_test.rs
The latest rust release comes with new more opinionated clippy :). This PR fixes the new clippy errors and and runs `cargo clippy --fix` on all our crates.
> chore: clippy

- .github/CODEOWNERS
- .github/workflows/dev_pr/labeler.yml
- .ignore
- README.adoc
- dev/release/update_change_log.sh
Looks like recently closed [PR#1102](https://github.com/delta-io/delta-rs/pull/1102) missed some Ruby references.
This PR cleaned the rest.
> Delete lasted Ruby references

- rust/src/delta_datafusion.rs
Adds a test for the `left_larger_than_right` function and rewrites the function match expression to match on both the `left` and `right` argument
> add test for left_larger_than_right

- rust/src/action/parquet_read/mod.rs
logging this error per row is too verbose when reading newer unsupported versions of delta log
closes https://github.com/delta-io/delta-rs/issues/1093
> fix: change unexpected field logging level to debug

- python/Cargo.toml
- python/deltalake/_internal.pyi
- python/deltalake/table.py
- rust/Cargo.toml
- rust/src/action/parquet_read/mod.rs
A simple maintenance PR to update datafusion to the latest version.
> chore: update datafusion

- rust/src/action/mod.rs
- rust/src/operations/filesystem_check.rs
- rust/src/operations/mod.rs
- rust/src/test_utils.rs
- rust/tests/command_filesystem_check.rs
Implementation of the filesystem check operation.
The implementation is fairly straight forward with a HEAD call being made for each active file to check if it exists.
A remove action is then made for each file that is orphaned.
An alternative solution is instead to maintain a hashset with all active files and then recursively list all files. If the file exists then remove from the set. All remaining files in the set are then considered orphaned.
Looking for feedback and if the second approach is preferred I can make the changes
- closes #1092
> Implement filesystem check

- rust/src/operations/vacuum.rs
Avoid resolving table partition inside the file iteration loop
> minor: optimize partition lookup for vacuum loop

- rust/src/delta_config.rs
Adds a test for `get_boolean_from_metadata` from the `DeltaConfig`
> add test for get_boolean_from_metadata

- CONTRIBUTING.md
> Move roadmap to a pinned issue

- rust/src/delta_arrow.rs
Adds tests for `min_max_schema_for_fields`
> add test for min_max_schema_for_fields

- rust/src/action/mod.rs
- rust/src/delta.rs
- rust/src/operations/transaction.rs
- rust/src/schema.rs
- rust/src/table_state_arrow.rs
JSON serde errors are very hard to debug because they are usually displayed with the following vague error messages:
```
Error: Invalid JSON in log record: EOF while parsing a value at line 1 column 1                                                                                                              
Caused by:                                                                                                                                                                                   
EOF while parsing a value at line 1 column 1  
```
This PR separates JSON ser/de errors by different scenarios as well as adding more context to each error whenever applicable.
> improve debuggability of json ser/de errors

- python/deltalake/writer.py
- python/tests/test_writer.py
Updates timestamp for AddActions to use milliseconds.
- closes #1124 
\
> Set AddAction timestamps to milliseconds. Fixes #1124

- CHANGELOG-old.md
- CHANGELOG.md
- delta-inspect/Cargo.toml
- dev/release/update_change_log.sh
- rust/Cargo.toml
FYI I am merging `CHANGELOG.md` and `CHANGELOG-old.md`, since I think people would rather scroll through all past version in one file. (Otherwise, what's the benefit over looking at the Releases tab on GitHub?) This merge happens manually, not in the script.
I went over and pruned the release log manually, removing any internal facing issues or Python-specific pull requests (which don't get filtered out since we only tag issues not PRs).
- closes #1035
> chore(rust): update rust changelog for 0.7.0

- python/deltalake/table.py
- python/deltalake/writer.py
- python/docs/source/conf.py
- python/tests/test_writer.py
Adds a more specific ValueError if a wrong `table_or_uri` is provided in the `write_delta_lake` function. It also adds support for a pathlib `Path` object.
- closes #1123
> add function & test for parsing table_or_uri

- python/tests/test_writer.py
Now that #1138 is merged, we can use `pathlib.Path` instead of `str` in `write_deltalake()` and `DeltaTable.__init__()`
> use Path object in writer tests

- .github/workflows/python_build.yml
- python/Makefile
- python/deltalake/schema.py
- python/deltalake/writer.py
- python/docs/source/_ext/edit_on_github.py
- python/docs/source/conf.py
- python/pyproject.toml
- python/tests/conftest.py
- python/tests/pyspark_integration/test_write_to_pyspark.py
- python/tests/pyspark_integration/test_writer_readable.py
- python/tests/test_fs.py
- python/tests/test_schema.py
- python/tests/test_table_read.py
- python/tests/test_vacuum.py
- python/tests/test_writer.py
This PR sets up ruff for python linting. It also enables isort from within ruff and removes the standalone isort. 
closes #1149
> first setup of ruff for python linting

- python/Cargo.toml
- python/deltalake/table.py
- python/src/filesystem.rs
- python/src/lib.rs
- python/src/schema.rs
- rust/Cargo.toml
- rust/examples/recordbatch-writer.rs
- rust/src/lib.rs
- rust/src/operations/mod.rs
- rust/src/operations/optimize.rs
- rust/src/operations/writer.rs
- rust/src/storage/mod.rs
- rust/src/storage/utils.rs
- rust/src/writer/json.rs
- rust/tests/command_optimize.rs
This PR moves the optimize operation into the operations module. As part of this we do a few updates to the operation as well
- adopt `IntoFuture` pattern
- use writer from operations module
- replace `SerializedFileReader` with `ParquetRecordBatchStream`
As part of this we also update datafusion and arrow, which in turn requires updating pyo3. This requires updating some deprecated features. i.e. how function signatures are annotated. It also leads to a breaking change in the python funcitons - specifically the order of arguments in `dataset_partitions`. 
There is one more thing is was considering while doing these updates. Essentially we may be getting some undesired behaviour, as the writer in the operations module already considers file size, so not all data in a bin might actually …
> feat: move and update Optimize operation

- python/deltalake/writer.py
- python/src/lib.rs
- python/tests/test_writer.py
Currently high-level python writer isn't support partial partition overwrite. 
This PR enable usage of partitions filtering for writing data
The functionlity is similar to:
https://docs.databricks.com/delta/selective-overwrite.html
The logic checks that data should contains only partitions that passing filtering.  
```python
write_deltalake(
delta_path,
sample_data,
mode="overwrite",
partitions_filters=[("partition_a", ">", "1")],
)
```
> Selectively overwrite data with python

- rust/src/operations/write.rs
- rust/tests/datafusion_test.rs
The session state can keep some context pertinent to the [input plan](https://github.com/delta-io/delta-rs/blob/main/rust/src/operations/write.rs#L153-L157), so passing it allows for building useful `TaskContext`s for executing the plan.
This is especially the case when the input plan references another Delta table, which has previously registered it's object store (that needs to be accessible during the execution of the physical plan).
Closes #1186 
Curiously, if in the test I use `delta-0.8.0-partitioned` the final `SELECT` query fails with:
```
External(Execution("Failed to map column projection for field year. Incompatible data types Dictionary(UInt16, Utf8) and Utf8"))
```
I'm not sure yet why this happens, but I think it has nothing to do with this change.
> Enable passing Datafusion session state to WriteBuilder

- .github/dependabot.yml
Let dependabot ignore Arrow and DataFusion updates since we usually update them manually.
Closes #1193.
> chore: let dependabot ignore arrow and datafusion

- python/CONTRIBUTING.md
- python/README.md
- python/deltalake/writer.py
- python/docs/source/index.rst
- python/docs/source/usage.rst
- python/tests/test_writer.py
> docs(python): update docs

- rust/src/operations/load.rs
This is just a quick fix for #1157. There are likely some more revisions to our operations once I finally get done with #632, but until then I'd be nice if the load command can load local tables :)
closes #1157
> fix: load command for local tables

- python/deltalake/writer.py
- python/tests/test_writer.py
Python write_deltalake fails if pyarrow table contains binary columns ending with 0x5c
Python write_deltalake fails if pyarrow table contains binary columns ending with 0x5c #1146
> Python write_deltalake fails if pyarrow table contains binary columns

- rust/src/action/mod.rs
- rust/src/action/parquet2_read/mod.rs
- rust/src/delta.rs
- rust/src/operations/create.rs
- rust/src/operations/filesystem_check.rs
- rust/src/operations/optimize.rs
- rust/src/operations/transaction.rs
- rust/src/operations/write.rs
- rust/src/storage/mod.rs
- rust/src/table_state.rs
- rust/tests/command_optimize.rs
- rust/tests/commit_info_format.rs
Another PR on the road to #632 - ~~keeping it a draft, as it is based on #1206~~
While the `commitInfo` action is defined as completely optional, spark and delta-rs write at the very least interesting, but often also quite helpful information into the commit info. To make it easier to work with and centralize some conventions, we introduce a `CommitInfo` struct, that exposes some of the fields at the top level. Additionally we harmonize a bit between spark and delta-rs conventions.
part of #632
> feat: typed commit info

- rust/src/builder.rs
- rust/src/delta_datafusion.rs
- rust/src/writer/record_batch.rs
- rust/tests/datafusion_test.rs
Exposes partition columns in Datafusion's `PruningStatistics` which will reduce the number of files scanned when the table is queried.
This also resolves another partition issues where involving `null` partitions. Previously  `ScalarValue::Null` was used which would cause an error when the actual datatype was obtained from the physical parquet files.
- closes #1175
> Implement pruning on partition columns

- rust/src/delta_datafusion.rs
- rust/src/storage/mod.rs
- rust/tests/datafusion_test.rs
Make the object store url be unique for stores created via `DeltaObjectStore::new`, by generating it from the location instead of the prefix (which was previously hard-coded to `/`), in the same manner as for `try_new`.
Also, in the (unlikely) case that I'm not mistaken about `DeltaScan::execute` logic being redundant (see #1188 for more details), I've removed it and added a couple of tests.
Closes #1188
> Unique delta object store url

- python/Cargo.toml
- python/deltalake/_internal.pyi
- python/deltalake/writer.py
- python/src/lib.rs
- python/tests/test_writer.py
This PR fixes a few issues with the overwrite partition functionality:
1. We weren't handling serializing the partition values correctly when matching partitions, so we would get false positives when checking for incorrect data being written.
2. We were considering partition values independently, rather than as a tuple of values. This could lead to subtle issues when there are multiple partition columns.
3. The errors returned when our partition filters used incorrect column names were confusing.
Since this is an important new feature, I will cut a new bugfix release as soon as this is merged.
For example:
- closes #1220
- closes #1219
> fix: make sure we handle data checking correctly

- python/tests/test_table_read.py
- rust/src/delta.rs
- rust/src/table_state.rs
Updates the error message when trying to use a partition filter with a column that is not partitioned. 
Code to trigger the error (adapted from #1219):
```python
from datetime import date
import numpy as np
import numpy.random
import pandas as pd
from deltalake import DeltaTable, write_deltalake
nrows = 9
data = pd.DataFrame(
{
"year": np.repeat(2023, nrows),
"month": np.repeat([1, 2, 3], nrows / 3),
"values": numpy.random.normal(size=nrows),
}
)
table_path = "tables/monthly"
write_deltalake(
table_path,
data,
partition_by=["year", "month"],
mode="overwrite",
)
nrows = 4
new_data = pd.DataFrame(
{
"year": np.repeat(2023, nrows),
"month": np.repeat([4], nrows),
"values": numpy.random.normal(size=nrows) + 10,
}
)
write_deltalake(
table_path,
new_data,
mode="overwrite", …
```
> improve err msg on use of non-partitioned column

- .github/workflows/python_release.yml
We changed default to make our workspace harmonious, but didn't mean to change this for the Python release.
- closes #1224
> fix: use native-tls for python deltalake releases

- python/deltalake/writer.py
- python/tests/test_writer.py
Add optional max partitions arg to be passed to pyArrow dataset.write_dataset.
This resolves an issue where users are unable to write more than 1024 partitions and have no way of overriding the parameter
```
File "/lib/python3.8/site-packages/deltalake/writer.py", line 293, in write_deltalake
ds.write_dataset(
File "/lib/python3.8/site-packages/pyarrow/dataset.py", line 900, in write_dataset
_filesystemdataset_write(
File "pyarrow/_dataset.pyx", line 2479, in pyarrow._dataset._filesystemdataset_write
File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Fragment would be written into 1246 partitions. This exceeds the maximum of 1024
```
https://arrow.apache.org/docs/python/generated/pyarrow.dataset.write_dataset.html
> Add Max Partitions Arg to Write

- python/deltalake/__init__.py
- python/deltalake/_internal.pyi
- python/src/lib.rs
Low maintenance way to expose package version. It will come from the `cargo.toml`.
Note that we have a separate function already called `rust_core_version` that provides the version of the `deltalake` Rust crate. That currently matches the Python library, but I don't think we provide any guarantee it will continue to.
For example:
- closes #1227
> feat: add package version

- python/deltalake/table.py
Fixed Documentation for `get_add_actions` function
The code example uses `get_add_actions_df` as the method name instead of the correct `get_add_actions` method name.
None
The [[examples](https://delta-io.github.io/delta-rs/python/api_reference.html#deltalake.table.DeltaTable.get_add_actions)] section contains the incorrect method name.
> Fixed Documentation for `get_add_actions` function

- rust/src/storage/config.rs
- rust/src/storage/mod.rs
Purpose of this PR is to simplify the Store Backend Configuration code by removing ObjectStoreImpl enum.
> Simplify the Store Backend Configuration code

- rust/src/delta_arrow.rs
When creating a RecordBatch with one of the columns being a MapArray, there are issues with naming of sub-columns, as well as nullability of the "elements/key_value" sub-column.
- closes #1257
See https://www.rustexplorer.com/b/o7bfm4 for a breaking example.
I initially thought that the issue is specifically for array with 0-length maps, but `nullable` mismatch happens even when all of the map elements have values.
> Fix names and nullability when creating RecordBatch from MapArray

- python/src/lib.rs
- python/tests/test_writer.py
- rust/src/operations/transaction/conflict_checker.rs
- rust/src/operations/transaction/mod.rs
Switches Python implementation over to the new transaction API.
* Closes #1254
> feat: use new conflict checker in Python

- rust/src/schema.rs
Add description of `decimal` primitive into the documentation comment of `schema::SchemaDataType`
- closes #1280 
[schema::SchemaDataType](https://docs.rs/deltalake/latest/deltalake/schema/enum.SchemaDataType.html)
> Add description of decimal primitive to SchemaDataType

- rust/src/delta_datafusion.rs
- rust/src/operations/load.rs
- rust/src/operations/mod.rs
- rust/src/operations/transaction/state.rs
- rust/tests/datafusion_test.rs
This PR updates table scans with datafusion to read the file schema from the parquet file within the latest add action of the table. This is to work around some issues, where the schema we derive from metadata does not match the data in the parquet files - e.g. nanosecond timestamps vs. micorsoecond.
We also update the `Load` command to handle column selections and make it more consistent with the other operations.
closes #441
> feat: read schema from parquet files in datafusion scans

- rust/Cargo.toml
- rust/src/delta_arrow.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/transaction/state.rs
- rust/tests/datafusion_test.rs
@rtyler - this updates some more arrow / datafusion stuff that broke after the update. Had to downgrade to arrow 36 again, since its used with datafusion 22.
> chore: df / arrow changes after update

- rust/Cargo.toml
- rust/README.md
@houqp merged my previous pull request too fast :)
> Hide the parquet/json feature behind our own JSON feature

- .github/workflows/dev_pr.yml
This PR adds enforcement for [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) PR titles. This will allow us to totally automate the release process for the main Rust crate, so we can do more frequent releases.
The script is based on the substrait-io/substrait repo ([script](https://github.com/substrait-io/substrait/blob/main/.github/workflows/pr_title.yml)), which does weekly automated release ([release script](https://github.com/substrait-io/substrait/blob/main/.github/workflows/release.yml)).
Once we have the next release after this one, all commit messages will be compliant and we will be able to implement the release script.
> ci: enforce conventional commit PR titles

- python/src/lib.rs
- python/src/schema.rs
- rust/Cargo.toml
- rust/src/delta_arrow.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/transaction/state.rs
- rust/src/test_utils.rs
Lots of fun API changes, `Fields` is the biggest impact in terms of lines of code however.
BREAKING CHANGE:  new major versions for arrow and datafusion
> feat: upgrade to Arrow 37 and Datafusion 23

- rust/src/builder.rs
- rust/src/delta.rs
- rust/src/storage/config.rs
- rust/src/storage/file.rs
- rust/src/storage/mod.rs
- rust/src/test_utils.rs
- rust/tests/integration_concurrent_writes.rs
- rust/tests/integration_object_store.rs
- rust/tests/integration_read.rs
Continues work in #1274. Adds tests, and handles characters besides spaces.
- closes https://github.com/delta-io/delta-rs/issues/1189
> fix: allow special characters in storage prefix

- rust/src/operations/optimize.rs
We addressed the issues with our commit logic in https://github.com/delta-io/delta-rs/pull/632, so I think we can remove this disclaimer now from the optimize command.
For example:
- closes #1125
> docs: update message since we fixed the commit logic

- rust/src/builder.rs
- rust/src/storage/config.rs
Fixes regressions in handling local paths on windows.
> fix: handle local paths on windows

- python/src/lib.rs
- python/tests/test_writer.py
- rust/examples/recordbatch-writer.rs
- rust/src/delta.rs
- rust/src/delta_config.rs
- rust/src/lib.rs
- rust/src/operations/create.rs
- rust/src/writer/mod.rs
- rust/src/writer/test_utils.rs
- rust/tests/command_optimize.rs
- rust/tests/commit_info_format.rs
- rust/tests/common/mod.rs
- rust/tests/fs_common/mod.rs
Now that we have a decent test coverage to the low-level commit logic in the transactions module, we should deprecate the commit logic exposed directly on `DeltaTable`.
In some places I also updated internal call sites, however did not go through all of them.
> chore: add deprecation notices for commit logic on `DeltaTable`

- rust/src/delta_datafusion.rs
- rust/src/operations/transaction/state.rs
- rust/src/storage/utils.rs
- rust/tests/read_delta_partitions_test.rs
This PR is fixing #1228.
-  #1228
> fix: double url encode of partition key

- python/docs/source/usage.rst
Changes "partitionColumns" reference in documentation to corrected "partition_columns"
> fix: documentation typo fix

- python/Cargo.toml
- python/deltalake/data_catalog.py
- python/docs/source/usage.rst
- rust/Cargo.toml
- rust/src/data_catalog/mod.rs
- rust/src/data_catalog/unity/mod.rs
I'm currently working with Azure Databricks which uses Unity Catalog for storing Delta Lake table paths and I thought it would be nice if `delta-rs` provided basic support for it.
There isn't any Databricks SDK library for Rust as far as I know, so this change introduces direct dependency to `reqwest`, `reqwest-middleware` and `reqwest-retry` crates when the `unity` feature flag is enabled.
https://docs.databricks.com/api-explorer/workspace/tables/get
I manually tested against Azure Databricks workspace but the implementation should work with any cloud provider offering Databricks.
This is my first contribution, so I welcome any feedback. Thanks.
> feat: added support for Databricks Unity Catalog

- python/deltalake/table.py
- python/deltalake/writer.py
- python/tests/test_optimize.py
- python/tests/test_writer.py
It can be really confusing when writing to a Delta Table that afterwards the `DeltaTable` still needs to have `update_incremental` to reflect the changes. I felt this myself in #1336.
So this adds `update_incremental` at the end of write and optimize.
I also add it to the beginning of write, since I discovered you could get commit errors if you are passing in an old table state.
Also, made it so the `partition_by` argument can handle just a single string. (I think PyArrow does the same, which must be why I have muscle memory for it.)
No issue.
> feat: update incremental after operations

- rust/Cargo.toml
- rust/src/delta_datafusion.rs
- rust/src/operations/filesystem_check.rs
- rust/src/operations/mod.rs
- rust/src/operations/write.rs
- rust/tests/datafusion_test.rs
This PR updates the write operation, specifically:
* makes handling state consistent with other operations
* avoids some IO when creating updated table state
One potentially more controversial change is that we now try to case all batches written to either the physical schema (derived from latest parquet file) or the schema derived from the table. I feel this logic may eventually need some updating or at least we need to make sure this is consistently handled across all write paths. In any case, using the file schema we dis already see some schema mis-matches in current tests, so that I included some casting for record batches here.
> feat: write command improvements

- .github/workflows/python_release.yml
- python/pyproject.toml
mac os and windows jobs failed due to this environment variable not being referenced properly https://github.com/delta-io/delta-rs/actions/runs/4902626950/jobs/8754581863
> ci(python): fix release script to use environment variable

- .github/workflows/python_release.yml
The docs release is stuck because the Linux wheel publication is failing. The publication is failing because they already exist. We should just continue if it already exists instead.
> ci(python): make release idempotent

- rust/src/partitions.rs
I was using this for a project today and noticed no tests, oops.
> test: add some missing unit and doc tests for DeltaTablePartition

- rust/src/delta_datafusion.rs
- rust/src/operations/delete.rs
- rust/src/operations/mod.rs
- rust/src/operations/write.rs
- rust/src/writer/test_utils.rs
- rust/tests/datafusion_test.rs
This is a full implementation of the Delta Delete Command. Users can now delete records that match a predicate. This implementation is not limited to only partition columns and allows non-partition columns.
This also implements a `find_files` function  which can be used to implement the Update command.
- closes #832
> feat: delete operation

- rust/src/builder.rs
- rust/src/storage/config.rs
According to [this page](https://learn.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-use-blob-storage#access-files-from-within-cluster) `wasbs` is a legit and in fact recommended scheme for Azure Blob Storage. However we currently do not include it in `KNOWN_SCHEMES` which should lead to automatic detection of storage backend  to fail if we use `wasbs`.
This PR solves the problem.
> feat: add `wasbs` to known schemes

- python/deltalake/table.py
- python/stubs/pyarrow/dataset.pyi
- python/stubs/pyarrow/parquet/core.pyi
- python/tests/test_table_read.py
This pull request adds support for filtering to the `to_pandas` method of `DeltaTable`. The new filters argument allows
users to specify filtering criteria in a format that is compatible with `pyarrow.compute.Expression`.
- Adding the `filters` argument to `DeltaTable.to_pandas`.
- Adding the `_filters_to_expression` function to `table` module, which is based on [this implementation](https://github.com/apache/arrow/blob/b9cc5df8a4f7c7fe09f40ba92a74981dee5e536a/python/pyarrow/parquet/core.py#LL155C5-L155C26), but with improved type consistency.
- ~~Based on [the existing conventional unit tests](https://github.com/delta-io/delta-rs/blob/b5230835bc1d1b01d59da3649033f1180232ddb7/python/tests/test_table_read.py#L392), I did not add any additional test cases for this feature. Instead, I tested …
> feat(python): add filters argument to DeltaTable.to_pandas() for filter pushdown

- CHANGELOG.md
Update changelog for Rust 0.11.0 release
> docs: update changelog for `0.11.0`

- rust/src/table_state_arrow.rs
- rust/tests/add_actions_test.rs
This is a proposal for how #1223 could be fixed.
- fixes #1223
The current implementation excludes all columns that lack statistical information. The proposed fix will generate information for all columns, with missing statistical values being replaced by 'null' values. However, it is unclear if this is the correct behavior since the `stats_as_batch` function lacks documentation.
> fix: include stats for all columns (#1223)

- python/src/lib.rs
- python/tests/test_writer.py
- rust/src/operations/create.rs
When switching to the create operation to back `write_deltalake` we allowed only known configuration keys on metadata. THis fixed that regression.
closes #1353
> fix: allow user defined config keys

- rust/src/action/parquet_read/mod.rs
Add a match statement to handle the case when timestamp is encoded as `TimestampMicros` in the parquet file.
- resolves #1372.
N/A
> fix: add conversion for string for `Field::TimestampMicros` (#1372)

- python/src/schema.rs
docs: Minor change in the docs. The documentation says Decimal(\<scale\>, \<precision\>) but it should be Decimal(\<precision\>, \<scale\>)
> docs: updated schema.rs to use the right signature for decimal data type in documentation

- rust/src/operations/delete.rs
- rust/src/operations/transaction/state.rs
The deletion operation fails when a predicate contains partition and non-partition columns.
Datafusion currently raises an error about comparing a dictionary to a scalar
E.G The expression `col("partition_col").eq(lit"2023-05-16"))` fails since the literal is a UTF8 and not a dictionary.
This is fixed by creating the physical expression using the table schema where partition columns are not wrapped. Otherwise, the wrapped schema is used elsewhere.
> fix: delete operation when partition and non partition columns are used

- rust/src/operations/vacuum.rs
We don't yet have batch deletes in object store (but will soon). In the meantime, we can at least issue multiple requests in parallel. Set the default at 10. I think that should be reasonable for now; later we can optimize to try to find the right rate to avoid rate-limiting.
* helps with #1366
> feat: vacuum with concurrent requests

- aws/delta-checkpoint/src/main.rs
- python/src/lib.rs
- rust/src/action/mod.rs
- rust/src/action/parquet2_read/mod.rs
- rust/src/builder.rs
- rust/src/checkpoints.rs
- rust/src/delta.rs
- rust/src/operations/delete.rs
- rust/src/operations/filesystem_check.rs
- rust/src/operations/optimize.rs
- rust/src/operations/transaction/conflict_checker.rs
- rust/src/operations/transaction/mod.rs
- rust/src/operations/vacuum.rs
- rust/src/schema.rs
- rust/src/storage/mod.rs
- rust/src/table_state.rs
- rust/src/table_state_arrow.rs
- rust/src/writer/mod.rs
- rust/src/writer/stats.rs
Removing the aliases in favor of the actual type to improve readability of the code and reduce confusion around the existence of the types.
`DeltaDataTypeLong` replaced with `i64`
`DeltaDataTypeVersion` replaced with `i64`
`DeltaDataTypeTimestamp` replaced with `i64`
`DeltaDataTypeInt` replaced with `i32`
N/A
N/A
> refactor!: remove `DeltaDataType` aliases

- rust/Cargo.toml
- rust/src/writer/record_batch.rs
Some time ago, the arrow-row crate was published, specifically with use cases like multi-column ordering / sorting in mind. We need to do this whenever we write data to a table to partition batches according to their partition values. In this PR we adopt this. As a drive-by I also updated the imports in the module to import from the respective sub-crates.
> perf: improve record batch partitioning

- rust/src/operations/writer.rs
- rust/src/writer/json.rs
- rust/src/writer/mod.rs
- rust/src/writer/record_batch.rs
- rust/src/writer/stats.rs
- rust/src/writer/test_utils.rs
* Removed the data copies in a tight loop, which were extremely bad for performance when writing files > 100MB.
* Rewrote statistics handling to collect null values from metadata, just like min and max.
* Added support for more types in statistics.
- closes #1394
- closes #1209 
- closes #1208
> feat: more efficient parquet writer and more statistics

- rust/Cargo.toml
- rust/src/data_catalog/mod.rs
- rust/src/data_catalog/storage/mod.rs
Adds a datafusion `SchemaProvider` implementation based on discovering Delta tables in a storage location via `_delta_log` folders.
> feat: add datafusion storage catalog

- python/deltalake/__init__.py
- python/deltalake/_internal.pyi
- python/pyproject.toml
- python/src/lib.rs
Some static type checker (i.e. pyright) consider imports as internal to the module unless explicitly stated otherwise - by adding it to `__all__` or using the "redundant alias" (not sure that's an official term 😆) form. I opted for the second, as I think it looks a bit nicer..
We were also exporting `RawDeltaTable` at the root, which I thogtht would be an internal class, that we do not want to expose to users?
Took the opportunity to also add a few more docstrings.
> chore: type-check friendlier exports

- rust/src/storage/mod.rs
Adds the `list_with_offset` delegation method to `DeltaObjectStore`.
- closes #1252 
https://github.com/apache/arrow-rs/issues/3970
> feat: add list_with_offset to DeltaObjectStore

- rust/src/checkpoints.rs
- rust/tests/integration_checkpoint.rs
Update cleanup regex to include `checkpoint.parquet` files
- closes #1420
https://regex101.com/r/OmoZMz/2
> fix: update cleanup regex to include `checkpoint.parquet` files

- README.adoc
Updated the Slack and YouTube links as the Slack invite no longer works.
> docs: update README.adoc to fix expired Slack link

- rust/src/operations/delete.rs
- rust/src/operations/write.rs
- rust/src/writer/test_utils.rs
Suppose a user has a table with column of type int. A user can create a record batch with type Uft8 and write the value to table. My expectation is that either the writer returns an error or ansi sql behavior is implemented where non-numeric strings are turned into nulls.
> fix: casting when data to be written does not match table schema

- .github/workflows/build.yml
- .github/workflows/python_build.yml
With our current integration tests being close to unusable due to the very frequent failures of the HDFS tests, I took the liberty to disable HDFS in the integration tests for now. While at it I also sprinkled a couple of `RUSTFLAG`s in the hopes of improving the overall experience with our CI/CD.
Last but not least, I added python 3.11 to the test matrix, in the hopes that it may just work :).
related #1428
> ci: prune CI/CD pipelines

- rust/Cargo.toml
- rust/src/operations/optimize.rs
- rust/tests/command_optimize.rs
Implements Z-order in Rust. This is a very basic version that requires loading the whole partition into memory for sorting. In the future, we can implement a DataFusion-based code path that allows sorting with spilling to disk for even larger optimize jobs.
The Z-order function here is based on Arrow's row format. We truncate to take the first 16 bytes of data (padding with zeros at end as necessary). So for variable-width columns like strings, this means that we are only using the first 15 bytes of the string (the first byte is used to differentiate null and empty strings, [see row format docs](https://docs.rs/arrow-row/40.0.0/arrow_row/struct.RowConverter.html#variable-length-bytes-including-strings-encoding)). If a user has a string column where they all share the same prefix, this …
> feat: add z-order optimize

- python/src/error.rs
- rust/src/action/mod.rs
- rust/src/delta.rs
- rust/src/errors.rs
- rust/src/storage/utils.rs
- rust/src/table_state.rs
This PR removes `LoadCheckpointError` and  `ApplyLogError` as well as moves some more checkpoint related functions into the checkpoint module.
Aside from cleaning up errors, this moves us a little bit closer to isolating log handling related logic in preparation for some upcoming work.
part of: #1136
> refactor: remove `LoadCheckpointError` and `ApplyLogError`

- rust/src/operations/writer.rs
- rust/src/writer/json.rs
- rust/src/writer/record_batch.rs
- rust/src/writer/utils.rs
The compression name was hard-coded to include snappy however users can now  specify their own methods which will cause a disconnect in the the name and the method used.
The naming convention is used as a hint by spark and hive to create the correct reader without reading having read the header of the file.
> feat: update writers to include compression method in file name

- python/deltalake/table.py
- python/docs/source/usage.rst
- python/src/lib.rs
- python/tests/test_optimize.py
Updated the API to:
```python
DeltaTable.optimize.compact()
DeltaTable.optimize.z_order()
```
The old API of `DeltaTable.optimize()` still works, but now issues a deprecation warning.
- closes #1442
> feat(python): expose z-order in Python

- python/src/schema.rs
- python/tests/test_schema.py
Field signatures are not identical on the `type` field, which makes instantiating deltalake Fields with the `type` keyword impossible in python - and the `name` keyword as well for that matter.
> fix(python): match Field signatures

- rust/src/action/checkpoints.rs
- rust/src/action/mod.rs
- rust/src/delta.rs
The `size` field should be the number of actions stored in the checkpoint while `sizeInBytes` is used for the total size in bytes.
Added `CheckPointBuilder` to make the creation of these easier to use.
- Closes #1468 
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#last-checkpoint-file
> fix: add `sizeInBytes` to _last_checkpoint and change `size` to # of actions

- rust/src/errors.rs
- rust/src/writer/mod.rs
- rust/src/writer/stats.rs
This PR exposes create_add to the public
- closes #1458
> feat: expose create_add to the public

- rust/src/writer/stats.rs
This PR adds support for calculating statistics of FixedLenByteArray UUID columns.
- closes #1483
> feat: add UUID statistics handling

- python/Makefile
- rust/examples/basic_operations.rs
- rust/examples/recordbatch-writer.rs
- rust/src/operations/write.rs
- rust/src/operations/writer.rs
- rust/src/writer/record_batch.rs
Adds the capability to pass a configured WriterProperties to the `RecordBatchWriter` and `DeltaWriter` similar to how the `OptimizeBuilder` can be updated.
- closes #1469 
- closes #1235
> feat(rust): expose WriterProperties method on RecordBatchWriter and DeltaWriter

- python/deltalake/table.py
- python/deltalake/writer.py
- python/src/lib.rs
- rust/src/operations/optimize.rs
- rust/tests/command_optimize.rs
Fixes the base implementation so that is doesn't materialize the entire result in one record batch. It will still require materializing the full input for each partition in memory. This is mostly a problem for unpartitioned table, since that means materializing the entire table in memory.
Adds a new datafusion-based implementation enabled by the `datafusion` feature. In theory, this should support spilling to disk.
For example:
- closes #1459
- closes #1460
> feat: handle larger z-order jobs with streaming output and spilling

- rust/src/action/mod.rs
- rust/src/operations/mod.rs
- rust/src/operations/restore.rs
- rust/src/operations/transaction/mod.rs
- rust/tests/command_restore.rs
This is a implementation of the Restore Command.
https://github.com/delta-io/delta-rs/issues/837
> feat: implement restore operation

- docker-compose.yml
- python/Cargo.toml
- python/src/lib.rs
- python/src/schema.rs
- rust/Cargo.toml
- rust/src/action/checkpoints.rs
- rust/src/data_catalog/storage/mod.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/delete.rs
- rust/src/operations/transaction/state.rs
- rust/src/operations/update.rs
- rust/src/storage/config.rs
- rust/src/storage/file.rs
- rust/src/storage/mod.rs
- rust/src/storage/s3.rs
- rust/src/storage/utils.rs
- rust/src/writer/json.rs
- rust/tests/datafusion_test.rs
- rust/tests/repair_s3_rename_test.rs
Updating datafusion and related crates to latest version. With the updated object store, we unfortunately loose support for `aws-profile`. Since object sore now also contains logic for parsing urls, that we currently maintain here, I was planning on adopting these new APIs and recovering profile support in a follow up PR. This will then also remove the ignored deprecations from this PR.
> chore: update datafusion and related crates

- rust/src/writer/stats.rs
This PR fix typo in AggregatedStats.
- closes #1515
> fix: tiny typo in AggregatedStats

- rust/src/operations/delete.rs
- rust/src/operations/mod.rs
- rust/src/operations/update.rs
A small refactor on the delete op to have the same interface as the update op
Allows a single method to be used for predicates represented as an Datafusion `Expr` or as a string.
> refactor: unify with_predicate for delete ops

- .github/workflows/python_build.yml
- python/pyproject.toml
- python/src/lib.rs
- python/tests/test_table_read.py
Fixes issue where predicate pushdown isn't working for null values. This adds tests for both columns and partition columns.
- closes #1496
> fix: handle nulls in file-level stats

- python/deltalake/data_catalog.py
This PR shows the available options from the DataCatalog `Enum`, with links to their respective catalogs' documentation.
- Resolves: #1347.
> docs: show data catalog options in Python API reference

- rust/src/operations/write.rs
- rust/src/writer/test_utils.rs
This PR adds nested struct supports.
- closes #1518
> feat: add nested struct supports

- rust/src/action/checkpoints.rs
- rust/src/action/parquet_read/mod.rs
- rust/src/writer/stats.rs
- rust/tests/checkpoint_writer.rs
Avoid writing statistics for binary columns to fix JSON error thrown by Arrow
- closes #1493
> fix: avoid writing statistics for binary columns to fix JSON error

- CHANGELOG.md
- rust/Cargo.toml
- rust/src/action/checkpoints.rs
- rust/src/action/parquet_read/mod.rs
- rust/src/writer/stats.rs
- rust/tests/checkpoint_writer.rs
> fix: revert premature merge of an attempted fix for binary column statistics

- .github/workflows/build.yml
- .github/workflows/python_build.yml
Rumor has it that this will help with some of the space consumption during GitHub Actions
> chore: disable incremental builds in CI for saving space

- .github/workflows/python_release.yml
The bleeding edge features we are using caused the macos Python release to fail, because the GH runners are still on 1.70. https://github.com/delta-io/delta-rs/actions/runs/5676317320/job/15382866806
The Windows runner already has 1.71 and the Linux are fresh installing in a manylinux container already, so it's just MacOS that's the problem.
> ci: install newer rust for macos python release

- python/deltalake/table.py
- python/src/lib.rs
- rust/src/operations/vacuum.rs
Bulk delete was added to the object store https://github.com/apache/arrow-rs/issues/2615 which deletes multiple files within a single API call if the underlying store supports it. If it is not supported then concurrent requests are performed underneath.
This PR updates vacuum with the object store changes. Currently on S3 will see any benefits since the default bulk delete is not overridden for other backends.
- progresses #393
> feat!: bulk delete for vacuum

- rust/src/delta_datafusion.rs
Make the find_files API public, same as public API for connectors' [`markFilesAsRead`](https://delta-io.github.io/connectors/latest/delta-standalone/api/java/io/delta/standalone/OptimisticTransaction.html#markFilesAsRead-io.delta.standalone.expressions.Expression-): 
closes #1559
> feat: make find_files public

- .github/workflows/python_build.yml
I realized our Python CI is very slow because we are running the benchmarks in debug mode. We already have a separate CI job that runs them in release mode (which is actually useful), so just disabling it in the main job.
> ci: don't run benchmark in debug mode

- python/Cargo.toml
- rust/Cargo.toml
- rust/src/action/parquet_read/mod.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/update.rs
- rust/src/table_state.rs
- rust/tests/checkpoint_writer.rs
Update `datafusion` to `28` and arrow to `43` and sprinkle some `.unwraps()` on the new result types. 
- https://github.com/apache/arrow-datafusion/blob/branch-28/dev/changelog/28.0.0.md
- https://github.com/apache/arrow-rs/blob/43.0.0/CHANGELOG.md
> chore: update `datafusion` to `28` and arrow to `43`

- Cargo.toml
- python/Cargo.toml
- rust/Cargo.toml
This commit moves a common set of dependencies from `rust/` and `python/` Cargo.toml files in favor of using the `workspace = true` variation.
The goal of this commit if merely organization. Pruning features, bumping versions are not goals of this commit.
- Closes #1572
> chore: move deps to `[workspace.dependencies]`

- python/deltalake/table.py
Currently the `DeltaProtocolError` given by an unsupported minimum reader version reads:
`DeltaProtocolError: The table's minimum reader version is 2but deltalake only supports up to version 1.`
This just adds a space between the min reader version number and the following word ("but") so that it reads
`DeltaProtocolError: The table's minimum reader version is 2 but deltalake only supports up to version 1.`
> fix: correct whitespace in delta protocol reader minimum version error message

- python/pyproject.toml
Should the project remove the alpha classifier? or is it still considerer an alpha project?
I am asking that because the alpha classifier currently associated with the project might be creating some hesitation among prospective users or partners. The alpha classifier suggests that the project is not ready for a wider use.
If the maintainers still think that the project should be classified as a alpha please feel free to close this PR
> fix: remove alpha classifier

- python/deltalake/schema.py
I noticed that `pa.Table.from_pandas` was called twice even after the schema was constructed. Seems more efficient to just cast the existing that data has been read into memory with the newly created schema.
> refactor: use pa.table.cast in delta_arrow_schema_from_pandas

- rust/src/operations/write.rs
This PR simply provides a way to add commit metadata during `DeltaOps::write()` operation similar to `DeltaOps::update()`.
None
None
> feat: add metadata for operations::write::WriteBuilder

- rust/src/delta_arrow.rs
The Arrow schema definitions in `delta_log_schema_for_table` are currently a bit tricky to read -- it's not straightforward to tell from looking at, say, [this line](https://github.com/delta-io/delta-rs/blob/502b7d5b043b3bb7f62f99f31174246d7c3296a9/rust/src/delta_arrow.rs#L387C12-L387C13) to which field that particular `true` belongs. This adds a few helper macros that hopefully make this a little more readable, and replaces the existing definitions with calls to those macros that result in equivalent code.
These macros are fairly tailored to these specific schema definitions, so I just included them in the delta_arrow module, but happy to break them off into their own module and include tests for them. I mostly wanted to see if this sort of a refactor would be welcome given that I've …
> refactor: clean up arrow schema defs

- python/deltalake/writer.py
- python/pyproject.toml
- python/src/lib.rs
- python/tests/conftest.py
- rust/src/action/checkpoints.rs
- rust/src/action/mod.rs
- rust/src/delta.rs
- rust/src/delta_arrow.rs
- rust/src/delta_datafusion.rs
- rust/src/operations/transaction/state.rs
- rust/src/storage/file.rs
This is a temporary fix until I have more time to finish #1602.
> fix: just make pyarrow 12 the max

- rust/src/action/mod.rs
Allows the min_values, max_values and null_count in the JSON file statistics to be null without changing the public API of the Stats struct.
- closes #582
> fix: support partial statistics in JSON

- python/tests/test_table_read.py
- rust/src/delta_datafusion.rs
- rust/src/storage/utils.rs
- rust/tests/command_restore.rs
Fixes new failure by simplifying the test case.
> fix: update python test

- Cargo.toml
- rust/Cargo.toml
- rust/src/operations/optimize.rs
- rust/tests/command_restore.rs
Updates datafusion to 30, and arrow to 45.
N/A
N/A
> chore: update datafusion to 30, arrow to 45

- .github/workflows/python_build.yml
- python/Cargo.toml
- python/src/filesystem.rs
- python/tests/test_benchmark.py
I'm not sure yet this is the root cause of the performance issues we are seeing in #1569, but this seems like an obvious change that might help.
Any method that takes `&mut self` implicitly holds the GIL, so we'll need to allow threads explicitly in those methods.
> perf: avoid holding GIL in DeltaFileSystemHandler

- CHANGELOG.md
- dev/release/update_change_log.sh
Generated with `SINCE_VERSION=0.13.0 FUTURE_RELEASE=0.15.0 ./dev/release/update_change_log.sh`
> Introduce the changelog for the last couple releases

- rust/src/delta_arrow.rs
- rust/tests/integration_datafusion.rs
This value was true but where arrow defines it as always false https://github.com/apache/arrow-rs/blob/master/arrow-schema/src/field.rs#L230.
This is also described in apache/arrow-rs#1697.
This also replaces `key_value` as the struct name with `entries` to remain consistent with https://github.com/apache/arrow-rs/blob/878217b9e330b4f1ed13e798a214ea11fbeb2bbb/arrow-schema/src/datatype.rs#L247-L250
- closes #1619
> fix: change map nullable value to false

- python/src/filesystem.rs
- python/tests/data_acceptance/test_reader.py
- python/tests/test_table_read.py
- rust/src/delta.rs
- rust/src/lib.rs
- rust/src/table_state.rs
In the delta log, paths are percent encoded. We decode them here:
https://github.com/delta-io/delta-rs/blob/787c13a63efa9ada96d303c10c093424215aaa80/rust/src/action/mod.rs#L435-L437
Which is good. But then we've been re-encoding them with `Path::from`. This PR changes to use `Path::parse` when possible instead. Instead of propagating errors, we just fallback to `Path::from` for now. Read more here: https://docs.rs/object_store/0.7.0/object_store/path/struct.Path.html#encode
* closes #1533
* closes #1446 
* closes #1079
* closes #1393
* closes #1228
> fix: don't re-encode paths

- Cargo.toml
0.4.31 deprecates timestamp_nanos() which we'll have to figure out what to do with.
> chore: pin the chrono dependency

- rust/src/operations/optimize.rs
- rust/tests/command_optimize.rs
Currently "optimize" executes the whole plan in one commit, which might fail. The larger the table, the more likely it is to fail and the more expensive the failure is.
Add an option in OptimizeBuilder that allows specifying a commit interval. If that is provided, the plan executor will periodically commit the accumulated actions.
> feat: allow multiple incremental commits in optimize

- Cargo.toml
The Python binding relies on `timestamp_nanos_opt()` which requires 0.4.31 or greater from chroni since it did not previously exist.
As a [cargo dependency refresher](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio) this version range is >=0.4.31, < 0.5.0 which is I believe what we need for optimal downstream compatibility.
Related to #1635 and #1631
(silly chrono!)
> fix: explicitly require chrono 0.4.31 or greater

- rust/src/delta.rs
In `get_latest_version`, start listing from the currently loaded version when it's newer than the last checkpoint.
- closes https://github.com/delta-io/delta-rs/issues/1643
> fix: avoid excess listing of log files

- python/deltalake/_internal.pyi
- python/deltalake/fs.py
- python/deltalake/table.py
- python/src/filesystem.rs
- python/src/lib.rs
- python/tests/test_file_system_handler.py
- python/tests/test_table_read.py
Currently the Filesystem implementation always makes a HEAD request when opening a file, to determine the file size. The proposed change is to read the file sizes from the delta log instead, and to pass them down to the `open_input_file` call, eliminating the HEAD request.
> feat: pass known file sizes to filesystem in Python

- rust/src/storage/config.rs
- rust/src/test_utils.rs
- rust/tests/integration_object_store.rs
This is a rebase and update of #1564 which already has some robust discussion. 
Closes #1564
> fix: introduce support for Microsoft OneLake

- README.md
not sure what the deal with the go.delta.io service, no idea where that lives
Fixes #1636
> chore: fix the incorrect Slack link in our readme

- rust/Cargo.toml
I was confused that I could not find the documentation integrating datafusion with delta-rs.
With this PR, everything should show up. Perhaps docs for a feature gated method should also mention which feature is required. Similar to what Tokio does. Perhaps it could be done in followup PRs.
> docs: make docs.rs build docs with all features enabled

- python/deltalake/table.py
Adds a docstring to the `DeltaTable#protocol()` method, so it shows up in the documentation.
Partially addresses #1657
We will want to update the `protocol()` method to return the list of table features that are supported by a given table.
N/A
> docs: add docstring to protocol method

- .github/workflows/python_release.yml
- python/Cargo.toml
> chore: increment python library version

- python/deltalake/writer.py
The exception message when comparing schemas in `deltalake.writer.write_deltalake` is ambiguous as it interchanges the table and data schemas.
> fix: exception string in writer.py

- python/deltalake/writer.py
Currently it was always checking the schema for non-large types, I didn't know before we could change it so in polars we added some schema casting from large to non-large, this however became a problem today when I wanted to write 200M records at once because the array was too big the fit in normal string type.
```python
ArrowInvalid: Failed casting from large_string to string: input array too large
```
Adding this flag will allow libraries like polars to write directly with their large dtypes in arrow. If this is merged, I can work on fix in polars to remove the schema casting for these large types.
> feat: allow to set large dtypes for the schema check in `write_deltalake`

- python/deltalake/writer.py
- python/tests/test_writer.py
If pyarrow is below v12.0.0 it changes the partitioning schema fields from large_string to string.
closes #1669 
https://github.com/apache/arrow/issues/34546#issuecomment-1466587443
> fix: change partitioning schema from large to normal string for pyarrow<12

- rust/Cargo.toml
- rust/src/data_catalog/unity/mod.rs
Long-term fix will be for Databricks to release a Rust SDK for Unity :smile:
Fixes #1627
> fix: unify environment variables referenced by Databricks docs

- rust/Cargo.toml
The docs build was changed in #1658 to compile on docs.rs with all features, but our crate cannot compile with all-features due to the TLS features, which are mutually exclusive.
For example:
- closes #1692
This has been tested locally with the following command:
```
cargo doc --features azure,datafusion,datafusion,gcs,glue,json,python,s3,unity-experimental
```
> docs: get docs.rs configured correctly again

- rust/src/delta_datafusion/expr.rs
- rust/src/delta_datafusion/mod.rs
- rust/src/operations/delete.rs
- rust/src/operations/merge.rs
- rust/src/operations/mod.rs
- rust/src/operations/transaction/conflict_checker.rs
- rust/src/operations/transaction/state.rs
- rust/src/operations/update.rs
Resolves two issues that impact Datafusion implemented operators
1. When a user has an expression with a scalar built-in scalar function we are unable parse the output predicate since the `DummyContextProvider`'s methods are unimplemented. The provider now uses the user provided state or a default. More work is required in the future to allow a user provided Datafusion state to be used during the conflict checker.
2. The string representation was not parsable by sqlparser since it was not valid SQL. New code was written to transform an expression into a parsable sql string. Current implementation is not exhaustive however common use cases are covered. 
The delta_datafusion.rs file is getting large so I transformed it into a module.
This implementation makes reuse of some code from …
> fix!: ensure predicates are parsable

- python/deltalake/table.py
- python/src/lib.rs
- python/tests/test_delete.py
- rust/src/operations/delete.rs
Naively expose the delete operation, with the option to provide a predicate.
I first tried to expose a richer API with the Python `FilterType` and DNF expressions, but from what I understand delta-rs doesn't implement generic filters but only `PartitionFilter`. The `DeleteBuilder` also only accepts datafusion expressions. So Instead of hacking my way around or proposing a refactor I went for the simpler approach of sending a string predicate to the rust lib.
If this implementation is OK I will add tests.
- closes #1417
> feat(python): expose delete operation

- rust/src/operations/create.rs
add support for `SaveMode::Overwrite` (`CREATE OR REPLACE`)
closes #1689
full working example: 
```rust
use deltalake::{
operations::create::CreateBuilder, protocol::SaveMode, DeltaOps, SchemaDataType, SchemaField,
};
fn get_table_columns() -> Vec<SchemaField> {
vec![SchemaField::new(
String::from("date"),
SchemaDataType::primitive(String::from("date")),
false,
Default::default(),
)]
}
fn get_table_columns_2() -> Vec<SchemaField> {
vec![
SchemaField::new(
String::from("date"),
SchemaDataType::primitive(String::from("date")),
false,
Default::default(),
),
SchemaField::new(
String::from("utf8"),
SchemaDataType::primitive(String::from("utf8")),
false,
Default::default(),
),
]
}
#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), deltalake::errors::DeltaTableError> {
let …
```
> feat: support CREATE OR REPLACE

- python/deltalake/table.py
- python/stubs/pyarrow/dataset.pyi
Enable prebuffer in the pyarrow.dataset.ParquetFragmentScanOptions. Relevant PR in [Arrow ](https://github.com/apache/arrow/pull/37854)repo, where they changed it to be default behavior. However, this won't be the case for older versions for PyArrow, so we need to set it to True.: 
It improves read speed by 6-7x on Azure in one dataset that I have.
Before:
1min 4s ± 3.48 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
After:
8.99 s ± 786 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Closes #https://github.com/delta-io/delta-rs/issues/1569
> feat: improve read performance by 7x with prebuffer

- python/src/lib.rs
- rust/src/lib.rs
- rust/src/operations/optimize.rs
- rust/src/schema/partitions.rs
- rust/src/table/mod.rs
- rust/src/table/state.rs
- rust/tests/read_delta_partitions_test.rs
This commit removes a bunch of lifetime restrictions on the `PartitionFilter` and `PartitionFilterValue` classes to make them easier to use. While the original discussion in Slack and #1501 made mention of using a reference type, there doesn't seem to a need for it. A particular instance of a `PartitionFilter` is created once and just borrowed and read for the remainder of its life.
Functions, when necessary continue to accept the non-container types (i.e, `&str` and `&[&str]`), allowing their containerized counterparts to continue working with them without needing to borrow or clone the containers (i.e, `String` and `Vec<String>`).
- resolves #1501
> refactor!: remove a layer of lifetimes from PartitionFilter

- python/deltalake/_util.py
- python/tests/test_table_read.py
The `isinstance(val, datetime)` check was after `isinstance(val, date)` which meant that it was never found. I added a test for each encoding type.
> fix: reorder encode_partition_value() checks and add tests

- python/deltalake/table.py
These have been deprecated for a while and have obvious replacements.
> chore: remove deprecated functions

- python/pyproject.toml
Relaxes the `pyarrow` pin to allow *any* version 12 as it was likely unintended to *only* allow 12.0.0 and no other 12.* versions.
Resolves #1701
> fix: relax `pyarrow` pin

- .gitignore
- docs/python_api.md
- docs/usage/examining-table.md
- docs/usage/index.md
- mkdocs.yml
- python/deltalake/_internal.pyi
- python/deltalake/fs.py
- python/deltalake/schema.py
- python/deltalake/table.py
- python/deltalake/writer.py
- python/docs/source/conf.py
- python/docs/source/usage.rst
- python/src/schema.rs
Completed the outstanding tasks in #1708
Also changed theme from readthedocs to mkdocs - both are built-in but latter looks sleeker
closes #1708
> docs: convert docs to use mkdocs

- python/deltalake/writer.py
- python/docs/source/usage.rst
- python/pyproject.toml
I have added documentation in the API and also on the Python usage page regarding this configuration. Please let me know if it is satisfactory, and if not, I am more than happy to address any issues or make any necessary adjustments.
- closes #1674
> docs: dynamodb lock configuration

- rust/src/schema/arrow_convert.rs
Currently when trying to checkpoint a table with a binary column, this will fail with `data type Binary not supported`. This appears to be due to an arrow transformation into JSON to serialize the checkpoint format, and that `arrow-json` doesn't support binary (https://github.com/apache/arrow-rs/blob/master/arrow-json/src/writer.rs#L213).
This is a targeted fix that just disables stats generation for binary columns, which (at least to me) doesn't really make sense anyhow. This is a more targeted fix than #1498 and currently all the tests pass.
#1498
> fix: ignore binary columns for stats generation

- README.md
- rust/src/operations/delete.rs
- rust/src/operations/merge.rs
- rust/src/operations/restore.rs
- rust/src/operations/transaction/conflict_checker.rs
- rust/src/operations/transaction/mod.rs
- rust/src/operations/transaction/state.rs
- rust/src/operations/transaction/test_utils.rs
- rust/src/operations/update.rs
- rust/src/operations/write.rs
- rust/src/writer/test_utils.rs
Throw an error if a transaction includes Remove action with data change but the Delta Table is append-only.
- closes #352
> feat: honor appendOnly table config

- rust/src/operations/optimize.rs
This looks like an oversight that our CI didn't test because we have the datafusion feature typically enabled for our tests. The build error would only show up when building tests without it.
> chore: fix building/running tests without the datafusion feature

- python/deltalake/writer.py
Adds explicitly write support for pyarrow.dataset.Dataset. Currently, it would work on the first write because the writer wouldn't go inside if the table is not None condition, so it would not return an error, and since pyarrow.write_dataset supports Datasets it worked for the first write but not the second write.
- Closes https://github.com/delta-io/delta-rs/issues/1779
> fix(python): add write support explicitly for pyarrow dataset

- python/deltalake/writer.py
- python/tests/test_writer.py
Infinity can't be represented in JSON, so it should not be placed in statistics. It's also not semantically different from not having a min/max, so we can safely omit it.
- closes #1411
> fix(python): ignore infinity in stats

- .github/workflows/python_release.yml
Yet again, one of the linux release builds broke.
> ci(python): add aarch64 python release fix

- crates/deltalake-core/Cargo.toml
- crates/deltalake-core/src/storage/s3.rs
The new version of this crate properly sets a lease duration such that the locks can actually expire
> chore: upgrade to the latest dynamodb-lock crate

- .github/workflows/build.yml
- .github/workflows/dev_pr/labeler.yml
- crates/deltalake-core/tests/repair_s3_rename_test.rs
For our integrations tests we we selecting the `deltalake` crate. After splitting the crate into smaller crates, integration tests are no longer defined there, and thus are currently not executed in CI.
> fix: run integration tests in CI

- crates/deltalake-core/src/kernel/schema.rs
- crates/deltalake-core/src/operations/convert_to_delta.rs
- crates/deltalake-core/src/operations/mod.rs
- crates/deltalake-core/src/schema/partitions.rs
- crates/deltalake-core/src/writer/utils.rs
Add a convert_to_delta operation for converting a Parquet table to a Delta Table in place. 
- closes #1041
- closes #1682
> feat: add convert_to_delta

- python/Makefile
- python/pyproject.toml
- python/tests/test_table_read.py
Not a terribly important change, but since its one less dependency and behaves more or less like `black`, I thought maybe using the somewhat recently released `ruff format` command for formatting makes sense.
> ci: adopt `ruff format` for formatting

- crates/deltalake-core/src/operations/optimize.rs
Fix compile error in main when not activating datafusion feature.
- closes #1843
> fix: compile error with lifetime issues on optimize (#1843)

- .github/workflows/issue_comments.yml
Users can use `take` as comment to auto-assign the issue to them. Will require the `github.GITHUB_TOKEN` used by the Action to have write access to Issues. The action will check if the issues can be assigned to user before attempting.
Closes #1791
> feat: implement issue auto-assign on `take` comment

- crates/deltalake-core/src/protocol/checkpoints.rs
In some situations where the same writer is issuing append transactions using the operations API, which returns the newly created version, such as 10.
If the caller then attempts to create a checkpoint for version 10, the operation will produce an inconsistency in the `_last_checkpoint` file, if the callers in-memory table state has *not* been reloaded since the append operation completed.
In this scenario the _delta_log/ directory may contain: .
├── 00000000000000000000.json
├── 00000000000000000001.json
├── 00000000000000000002.json
├── 00000000000000000003.json
├── 00000000000000000004.json
├── 00000000000000000005.json
├── 00000000000000000006.json
├── 00000000000000000007.json
├── 00000000000000000008.json
├── 00000000000000000009.json
├── 00000000000000000010.checkpoint.parquet
├── …
> fix: prevent writing checkpoints with a version that does not exist in table state

- .github/workflows/python_build.yml
- README.md
- python/Cargo.toml
- python/pyproject.toml
This change is mainly motivated by the current build failures on main. Since 3.7 is EOL and we have been meaning to drop it for a while, I thought maybe its good to give that a try before diving deeper into the inners of openssl build failures.
Closes #1703
> feat: drop python 3.7 and adopt 3.12

- crates/deltalake-core/src/operations/update.rs
- crates/deltalake-core/src/table/mod.rs
Modify Checkpoint stuct not to serialize optional fields if null.
- closes #1847
> fix: checkpoint error with Azure Synapse

- .github/workflows/docs.yml
- .github/workflows/python_release.yml
Moved the requirement for contents write permission from release action to docs deployment. The same permission was  used in the previous release action (sphinx) so I'm not introducing any extra permission requirements. 
One thing I don't really like here is that such permission is only needed for the `Deploy` step but the lowest level it can be defined is job. This should be fine because other steps in the job don't do any git operations.
Alternative would be creating a separate Deploy job but then I'd have to duplicate all the steps from the Build part which would effectively be the same thing as now but with a longer/redundant config.
Deployment logic remains the same - docs are deployed only when the Build Documentation is run manually or via the Release Python action.
#1867
I am …
> fix: docs deployment action

- crates/deltalake-core/Cargo.toml
- crates/deltalake-core/benches/read_checkpoint.rs
- crates/deltalake-core/src/kernel/actions/types.rs
- crates/deltalake-core/src/operations/create.rs
- crates/deltalake-core/src/operations/delete.rs
- crates/deltalake-core/src/operations/load.rs
- crates/deltalake-core/src/operations/merge.rs
- crates/deltalake-core/src/operations/mod.rs
- crates/deltalake-core/src/operations/optimize.rs
- crates/deltalake-core/src/operations/restore.rs
- crates/deltalake-core/src/operations/transaction/mod.rs
- crates/deltalake-core/src/operations/transaction/protocol.rs
- crates/deltalake-core/src/operations/transaction/test_utils.rs
- crates/deltalake-core/src/operations/update.rs
- crates/deltalake-core/src/operations/write.rs
- crates/deltalake-core/tests/integration_concurrent_writes.rs
In preparation for further improvements to protocol support, this PR introduces a `ProtocolChecker` which validates that we can read form / write to / commit to a specific table. So far everything is expressed in table features in the hopes, that this keeps on giving correct behaviours as we add more table features. 
The existing support for append only is integrated and extended to handle enablement logic according to the protocol.
> feat: handle protocol compatibility

- docs/usage/installation.md
- mkdocs.yml
Move installation instructions to usage and include instructions for installing `deltalake` via Cargo.
> docs: add Rust installation instructions

- python/index.html
Old (sphynx) docs are not longer updated during the release so adding a message directly to home page of the old docs
closes: #1865
> docs: add a message to old docs with a link new docs

- crates/deltalake-core/src/operations/convert_to_delta.rs
- crates/deltalake-core/src/protocol/mod.rs
- python/deltalake/__init__.py
- python/deltalake/_internal.pyi
- python/deltalake/writer.py
- python/src/lib.rs
- python/tests/test_convert_to_delta.py
Exposes added `convert to delta` functionality by @junjunjd to Python API.  
- closes #1767
> feat(python): expose `convert_to_deltalake`
